### ISSUE TITLE
 Argument list too long

### ISSUE THREAD

**Issue by JSmythSSG** [rfennell/AzurePipelines#1024]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Describe the bug

```bash
2021-06-18T09:59:20.8281584Z ##[section]Starting: Wiki
2021-06-18T09:59:20.8293194Z ==============================================================================
2021-06-18T09:59:20.8293579Z Task         : Git based WIKI Single File Updater from Black Marble
2021-06-18T09:59:20.8293961Z Description  : A tools to update or create a file in a WIKI based in a Git repo 
2021-06-18T09:59:20.8294237Z Version      : 1.26.2
2021-06-18T09:59:20.8294450Z Author       : Richard Fennell
2021-06-18T09:59:20.8294831Z Help         : Version: 1.26.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2021-06-18T09:59:20.8295268Z ==============================================================================
2021-06-18T09:59:20.8957772Z ##[error]Argument list too long
2021-06-18T09:59:20.8973355Z ##[section]Finishing: Wiki
```

### Repo Steps

```bash
When using it in Releases it gets error ##[error]Argument list too long.

It works when I copy the yaml into a Pipeline though
```

### Logging Information

```bash
2021-06-18T10:03:53.3786417Z ##[debug]Evaluating condition for step: 'Wiki'
2021-06-18T10:03:53.3788627Z ##[debug]Evaluating: succeeded()
2021-06-18T10:03:53.3789192Z ##[debug]Evaluating succeeded:
2021-06-18T10:03:53.3790601Z ##[debug]=> True
2021-06-18T10:03:53.3791208Z ##[debug]Result: True
2021-06-18T10:03:53.3791862Z ##[section]Starting: Wiki
2021-06-18T10:03:53.3802221Z ==============================================================================
2021-06-18T10:03:53.3802616Z Task         : Git based WIKI Single File Updater from Black Marble
2021-06-18T10:03:53.3802981Z Description  : A tools to update or create a file in a WIKI based in a Git repo 
2021-06-18T10:03:53.3803287Z Version      : 1.26.2
2021-06-18T10:03:53.3803506Z Author       : Richard Fennell
2021-06-18T10:03:53.3803899Z Help         : Version: 1.26.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2021-06-18T10:03:53.3804352Z ==============================================================================
2021-06-18T10:03:53.4377723Z ##[debug]Using node path: /home/ubuntu/myagent/externals/node/bin/node
2021-06-18T10:03:53.4459587Z ##[error]Argument list too long
2021-06-18T10:03:53.4476415Z ##[debug]System.ComponentModel.Win32Exception (7): Argument list too long
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-06-18T10:03:53.4480972Z ##[section]Finishing: Wiki
```

**Comment by rfennell** [comment]
I have just retested the WIKI uploader in a Classic release using both a Windows and Ubuntu hosted agent, they both work.

My task as configured as follows

![image](https://user-images.githubusercontent.com/324718/122545936-53e84e00-d026-11eb-80cc-7055818d95e7.png)

Or exporting the YAML

```
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks-DEV.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI File Updater'
  inputs:
    repo: 'https://richardfennell@dev.azure.com/richardfennell/Dynamics365FO%20mycompany/_git/Dynamics365FO-mycompany.wiki'
    filename: realpage
    replaceFile: false
    contents: '$(Release.ReleaseId)'
    message: 'Commit Msg'
    gitname: name
    gitemail: 'name@domain.com'
    useAgentToken: true
```

The pipeline settings were set as follows to make sure the build agent could access the WIKI

![image](https://user-images.githubusercontent.com/324718/122546096-842fec80-d026-11eb-8708-67a7d7da707e.png)

And the build agent had contributed rights to the WIKI.

So I suspect there must be an issue in the parameters you are passing in, and partial escaped value maybe ?

What is the YAML for the task in the release?

**Comment by JSmythSSG** [comment]
Still getting it using the below settings
`steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI Updater'
  inputs:
    repo: 'https://Six-Star-Global@dev.azure.com/Six-Star-Global/Dev%20Ops/_git/Dev-Ops.wiki'
    filename: realpage
    replaceFile: false
    dataIsFile: false
    contents: '$(Release.ReleaseId)'
    message: 'Commit Msg'
    gitname: name
    gitemail: 'name@domain.com'
    useAgentToken: true`

**Comment by rfennell** [comment]
Looking at your log it would appear you are using a private Ubuntu agent, I make this assumption as the Node path differs from what I see.


> 2021-06-18T10:32:48.9841814Z ##[debug]Evaluating condition for step: 'Git based WIKI File Updater'
> 2021-06-18T10:32:48.9881788Z ##[debug]Evaluating: succeeded()
> 2021-06-18T10:32:48.9891275Z ##[debug]Evaluating succeeded:
> 2021-06-18T10:32:48.9932002Z ##[debug]=> True
> 2021-06-18T10:32:48.9941515Z ##[debug]Result: True
> 2021-06-18T10:32:48.9982966Z ##[section]Starting: Git based WIKI File Updater
> 2021-06-18T10:32:49.0188083Z ==============================================================================
> 2021-06-18T10:32:49.0188610Z Task : Git based WIKI Single File Updater from Black Marble
> 2021-06-18T10:32:49.0189078Z Description : A tools to update or create a file in a WIKI based in a Git repo
> 2021-06-18T10:32:49.0189307Z Version : 1.26.2
> 2021-06-18T10:32:49.0189672Z Author : Richard Fennell
> 2021-06-18T10:32:49.0190301Z Help : Version: 1.26.2. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
> 2021-06-18T10:32:49.0190609Z ==============================================================================
> 2021-06-18T10:32:49.1133474Z ##[debug]Using node path: /home/vsts/agents/2.187.2/externals/node/bin/node
> 2021-06-18T10:32:49.9300303Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
> 2021-06-18T10:32:49.9307704Z ##[debug]loading inputs and endpoints
> 2021-06-18T10:32:49.9308156Z ##[debug]loading INPUT_REPO
> 2021-06-18T10:32:49.9308523Z ##[debug]loading INPUT_FILENAME
> 2021-06-18T10:32:49.9308873Z ##[debug]loading INPUT_REPLACEFILE
> 2021-06-18T10:32:49.9309240Z ##[debug]loading INPUT_APPENDTOFILE
> 2021-06-18T10:32:49.9309607Z ##[debug]loading INPUT_DATAISFILE
> 2021-06-18T10:32:49.9309954Z ##[debug]loading INPUT_CONTENTS
> 2021-06-18T10:32:49.9310311Z ##[debug]loading INPUT_MESSAGE
> 2021-06-18T10:32:49.9310691Z ##[debug]loading INPUT_TAGREPO
> 2021-06-18T10:32:49.9311034Z ##[debug]loading INPUT_GITNAME
> 2021-06-18T10:32:49.9311391Z ##[debug]loading INPUT_GITEMAIL
> 2021-06-18T10:32:49.9311754Z ##[debug]loading INPUT_USEAGENTTOKEN
> 2021-06-18T10:32:49.9312103Z ##[debug]loading INPUT_LOCALPATH
> 2021-06-18T10:32:49.9312796Z ##[debug]loading INPUT_INJECTEXTRAHEADER
> 2021-06-18T10:32:49.9313174Z ##[debug]loading INPUT_RETRIES
> 2021-06-18T10:32:49.9313539Z ##[debug]loading INPUT_TRIMLEADINGSPECIALCHAR
> 2021-06-18T10:32:49.9314131Z ##[debug]loading INPUT_FIXLINEFEEDS
> 2021-06-18T10:32:49.9314806Z ##[debug]loading INPUT_FIXSPACES
> 2021-06-18T10:32:49.9315189Z ##[debug]loading INPUT_INSERTLINEFEED
> 2021-06-18T10:32:49.9315590Z ##[debug]loading INPUT_UPDATEORDERFILE
> 2021-06-18T10:32:49.9316000Z ##[debug]loading INPUT_PREPENDENTRYTOORDERFILE
> 2021-06-18T10:32:49.9316423Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
> 2021-06-18T10:32:49.9317149Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
> 2021-06-18T10:32:49.9317595Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN

As I can't repo the issue it is pointing to a local agent problem, so some things to try
- Do you get the same problem using Microsoft hosted agents?
- Do you get the same issue with a private Window based agent?

**Comment by JSmythSSG** [comment]
I tried it using the Azure hosted agent and it worked, I then switched back and it worked on my private hosted one and it worked. 

I haven't changed anything in the task settings and the yaml looks the same.

I've been slowly adding back the custom variables and it still works. I have not idea why it was throwing that error before 

```
steps:
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI Updater'
  inputs:
    repo: 'https://Six-Star-Global@dev.azure.com/Six-Star-Global/Dev%20Ops/_git/Dev-Ops.wiki'
    filename: 'Manage/Release-Notes/Staging/$(Release.ReleaseName).md'
    replaceFile: true
    dataIsFile: true
    sourceFile: '$(System.DefaultWorkingDirectory)/inline.md'
    message: 'Commit Msg'
    gitname: '$(Build.RequestedFor)'
    gitemail: '$(Build.RequestedForEmail)'
    useAgentToken: true
```

**Comment by rfennell** [comment]
Glad you are unblocked, hope you find the root issue
