### ISSUE TITLE
Argument List too long

### ISSUE THREAD

**Issue by mashraf92** [rfennell/AzurePipelines#1150]
### Azure DevOps Extensions

WIKI Updater

### Platform

Azure DevOps Services

### Extension Version

1.27.5

### Describe the bug

```
Starting: WikiFolderUpdaterTask
==============================================================================
Task         : Git based WIKI Folder Updater from Black Marble
Description  : A tools to update or create a set of files in a folder in WIKI based in a Git repo 
Version      : 1.27.5
Author       : Richard Fennell
Help         : Version: 1.27.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
==============================================================================
##[error]Argument list too long

```

### Repo Steps

Tried with Private Agent as well Microsoft Pipeline agent issue remain same.

### Logging Information

```
##[debug]Evaluating condition for step: 'WikiFolderUpdaterTask'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: WikiFolderUpdaterTask
==============================================================================
Task         : Git based WIKI Folder Updater from Black Marble
Description  : A tools to update or create a set of files in a folder in WIKI based in a Git repo 
Version      : 1.27.5
Author       : Richard Fennell
Help         : Version: 1.27.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.195.0/externals/node10/bin/node
##[error]Argument list too long
##[debug]System.ComponentModel.Win32Exception (7): Argument list too long
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

```

**Comment by rfennell** [comment]
I am struggling to get a repo on this issue

- Did with task work with the previous release?
- What are all the parameters being passed into task

**Comment by mashraf92** [comment]
This is new pipeline created last week, receiving error from the first build.
```
        replaceFile: false
        appendToFile: false
        useAgentToken: false
```

**Comment by rfennell** [comment]
I am still struggling for a repo of this. I can see the task loads for me and immediately displays all the passed in parameters

```
2021-11-22T13:03:18.4629237Z ##[debug]Evaluating condition for step: 'WikiFolderUpdaterTask'
2021-11-22T13:03:18.4630852Z ##[debug]Evaluating: SucceededNode()
2021-11-22T13:03:18.4631246Z ##[debug]Evaluating SucceededNode:
2021-11-22T13:03:18.4632005Z ##[debug]=> True
2021-11-22T13:03:18.4632446Z ##[debug]Result: True
2021-11-22T13:03:18.4633002Z ##[section]Starting: WikiFolderUpdaterTask
2021-11-22T13:03:18.4794160Z ==============================================================================
2021-11-22T13:03:18.4794446Z Task         : Git based WIKI Folder Updater from Black Marble
2021-11-22T13:03:18.4794702Z Description  : A tools to update or create a set of files in a folder in WIKI based in a Git repo 
2021-11-22T13:03:18.4794931Z Version      : 1.27.5
2021-11-22T13:03:18.4795076Z Author       : Richard Fennell
2021-11-22T13:03:18.4795339Z Help         : Version: 1.27.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2021-11-22T13:03:18.4795640Z ==============================================================================
2021-11-22T13:03:18.4864625Z ##[debug]Using node path: C:\agents\richardfennell\externals\node10\bin\node.exe
2021-11-22T13:03:18.6317295Z ##[debug]agent.TempDirectory=C:\agents\richardfennell\_work\_temp
2021-11-22T13:03:18.6343658Z ##[debug]loading inputs and endpoints
2021-11-22T13:03:18.6360545Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2021-11-22T13:03:18.6402759Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2021-11-22T13:03:18.6405345Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2021-11-22T13:03:18.6407620Z ##[debug]loading INPUT_APPENDTOFILE
2021-11-22T13:03:18.6408334Z ##[debug]loading INPUT_FILTER
2021-11-22T13:03:18.6410693Z ##[debug]loading INPUT_GITEMAIL
2021-11-22T13:03:18.6412377Z ##[debug]loading INPUT_GITNAME
2021-11-22T13:03:18.6414514Z ##[debug]loading INPUT_INJECTEXTRAHEADER
2021-11-22T13:03:18.6417714Z ##[debug]loading INPUT_LOCALPATH
2021-11-22T13:03:18.6420372Z ##[debug]loading INPUT_MESSAGE
2021-11-22T13:03:18.6422355Z ##[debug]loading INPUT_PASSWORD
2021-11-22T13:03:18.6424725Z ##[debug]loading INPUT_REPLACEFILE
2021-11-22T13:03:18.6425466Z ##[debug]loading INPUT_REPO
2021-11-22T13:03:18.6427944Z ##[debug]loading INPUT_RETRIES
2021-11-22T13:03:18.6429273Z ##[debug]loading INPUT_SOURCEFOLDER
2021-11-22T13:03:18.6430608Z ##[debug]loading INPUT_TAGREPO
2021-11-22T13:03:18.6431540Z ##[debug]loading INPUT_TARGETFOLDER
2021-11-22T13:03:18.6434035Z ##[debug]loading INPUT_USEAGENTTOKEN
2021-11-22T13:03:18.6438439Z ##[debug]loading SECRET_PAT
2021-11-22T13:03:18.6440533Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2021-11-22T13:03:18.6446168Z ##[debug]loaded 20
2021-11-22T13:03:18.6450267Z ##[debug]Agent.ProxyUrl=undefined
2021-11-22T13:03:18.6450922Z ##[debug]Agent.CAInfo=undefined
2021-11-22T13:03:18.6451358Z ##[debug]Agent.ClientCert=undefined
2021-11-22T13:03:18.6451767Z ##[debug]Agent.SkipCertValidation=undefined
2021-11-22T13:03:18.6609251Z ##[debug]repo=dev.azure.com/richardfennell/Git%2520project/_git/Git-project.wiki
2021-11-22T13:03:18.6610171Z ##[debug]targetFolder=folder
2021-11-22T13:03:18.6613205Z ##[debug]localpath=C:\agents\richardfennell\_work\21\s\repo
2021-11-22T13:03:18.6615967Z ##[debug]message=Updated as a folder
2021-11-22T13:03:18.6628784Z ##[debug]gitname=Build.RequestedForId
2021-11-22T13:03:18.6630514Z ##[debug]gitemail=Build.RequestedForEmail
2021-11-22T13:03:18.6632138Z ##[debug]user=undefined
2021-11-22T13:03:18.6632705Z ##[debug]password=***
2021-11-22T13:03:18.6633739Z ##[debug]useAgentToken=false
2021-11-22T13:03:18.6635184Z ##[debug]replaceFile=false
2021-11-22T13:03:18.6636271Z ##[debug]appendToFile=false
2021-11-22T13:03:18.6637726Z ##[debug]sourceFolder=${build.sourcesdirectory)
2021-11-22T13:03:18.6638454Z ##[debug]filter=**/*.md
2021-11-22T13:03:18.6640173Z ##[debug]tagRepo=False
2021-11-22T13:03:18.6640561Z ##[debug]tag=undefined
2021-11-22T13:03:18.6640920Z ##[debug]branch=undefined
2021-11-22T13:03:18.6641356Z ##[debug]injectExtraHeader=False
2021-11-22T13:03:18.6642889Z ##[debug]retries=5
2021-11-22T13:03:18.6647630Z Variable: Repo [dev.azure.com/richardfennell/Git%20project/_git/Git-project.wiki]
2021-11-22T13:03:18.6649126Z Variable: TargetFolder [folder]
2021-11-22T13:03:18.6649393Z Variable: Commit Message [Updated as a folder]
2021-11-22T13:03:18.6649634Z Variable: Git Username [Build.RequestedForId]
2021-11-22T13:03:18.6649877Z Variable: Git Email [Build.RequestedForEmail]
2021-11-22T13:03:18.6650092Z Variable: Use Agent Token [false]
2021-11-22T13:03:18.6650304Z Variable: Replace File [false]
2021-11-22T13:03:18.6650500Z Variable: Append to File [false]
2021-11-22T13:03:18.6650710Z Variable: Username [undefined]
2021-11-22T13:03:18.6650915Z Variable: Password [*****]
2021-11-22T13:03:18.6651153Z Variable: Localpath [C:\agents\richardfennell\_work\21\s\repo]
2021-11-22T13:03:18.6651417Z Variable: SourceFolder [${build.sourcesdirectory)]
2021-11-22T13:03:18.6651638Z Variable: Filter [**/*.md]
2021-11-22T13:03:18.6651846Z Variable: Tag Repo [false]
2021-11-22T13:03:18.6652038Z Variable: Tag [undefined]
2021-11-22T13:03:18.6652235Z Variable: Branch [undefined]
2021-11-22T13:03:18.6652438Z Variable: InjectExtraHeader [false]
2021-11-22T13:03:18.6652633Z Variable: Retries [5]
```

Without a repo I can't think what else to check
