### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by pjboardman** [rfennell/AzurePipelines#1176]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

I'm using this successfully in my pipeline across 3 stages but 1 stage has started failing continuously, across multiple builds, with this error:

```
TypeError: Cannot read property 'toString' of null
Total Builds: [0]
    at /agent/_work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/3.76.4/ReleaseNotesFunctions.js:1051:167
Total Commits: [0]
    at Generator.next (<anonymous>)
Total Workitems: [0]
    at fulfilled (/agent/_work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/3.76.4/ReleaseNotesFunctions.js:5:58)
Total Related Workitems (Parent/Children): [0]
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Repo Steps

I ran the testconsole and narrowed down the problem to this: in `ReleaseNotesFunctions.ts / getLastSuccessfulBuildByStage()` (line 1154), `record.result` is null

```javascript
agentApi.logInfo (`Found required stage ${record.name} in the state ${record.state.toString()} with the result ${record.result.toString()} state for build ${build.id}`);

```

```
Comparing 6611 against 6611
Ignore compare against self
Comparing 6610 against 6611
Considering build
Found required stage Deploy qa in the state 2 with the result 4 state for build 6610
Comparing 6609 against 6611
Considering build
The most common runtime reason for the task to fail is due API ECONNRESET issues. To avoid this failing the pipeline these will be treated as warnings and an attempt to generate any release notes possible
TypeError: Cannot read properties of null (reading 'toString')
    at /****/AzurePipelines/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts:1154:168
    at Generator.next (<anonymous>)
    at fulfilled (/***/AzurePipelines/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
here is the `record` object that causes the error:

```javascript
{
  previousAttempts: [
  ],
  id: "**************",
  parentId: null,
  type: "Stage",
  name: "**************",
  startTime: null,
  finishTime: null,
  currentOperation: null,
  percentComplete: null,
  state: 0,
  result: null,
  resultCode: null,
  changeId: 1,
  lastModified: {
  },
  workerName: null,
  order: 4,
  details: null,
  errorCount: 0,
  warningCount: 0,
  url: null,
  log: null,
  task: null,
  attempt: 1,
  identifier: "***********",
}
```

if it helps, here is the prior `record` object:

```javascript
{
  previousAttempts: [
  ],
  id: "********************",
  parentId: null,
  type: "Stage",
  name: "***********",
  startTime: null,
  finishTime: null,
  currentOperation: null,
  percentComplete: null,
  state: 2,
  result: 4,
  resultCode: "Evaluating: succeeded()\r\nResult: False\r\n",
  changeId: 82,
  lastModified: {
  },
  workerName: null,
  order: 4,
  details: null,
  errorCount: 0,
  warningCount: 0,
  url: null,
  log: null,
  task: null,
  attempt: 1,
  identifier: "************",
}
```

### Expected Behavior

Not sure why it is failing on this 1 stage but succeeding on others. Any hints on what else I can look into?

### Logging Information

```
Comparing 6611 against 6611
Ignore compare against self
Comparing 6610 against 6611
Considering build
Found required stage Deploy qa in the state 2 with the result 4 state for build 6610
Comparing 6609 against 6611
Considering build
The most common runtime reason for the task to fail is due API ECONNRESET issues. To avoid this failing the pipeline these will be treated as warnings and an attempt to generate any release notes possible
TypeError: Cannot read properties of null (reading 'toString')
    at /****/AzurePipelines/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts:1154:168
    at Generator.next (<anonymous>)
    at fulfilled (/***/AzurePipelines/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by pjboardman** [comment]
It looks like the stage that is causing the failure is in a "Waiting" state -- waiting for approval. If I cancel that one, then it fails on a prior waiting stage.

**Comment by rfennell** [comment]
Oops, excessive logging the problem then. I will get the PR merged
