### ISSUE TITLE
Changing build source breaks release notes generation.

### ISSUE THREAD

**Issue by CodeGlitcher** [rfennell/AzurePipelines#1333]
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Services

### Describe the bug

We have changed 1 of our build sources from classic pipeline to yaml.

```
from
 - pipeline: app
   branch: master
   project: xxxx
   source: \Docker Containers\pipeline_build
to
 - pipeline: app
   branch: master
   project: xxxx
   source: \Docker Containers\yaml_pipelines/yaml_build
```

### Repo Steps

1. Create a pipeline
2. add generate template step
```
We use:
- task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3
  displayName: 'Generate Release Notes based on Release Comparison API'
  inputs:
    outputfile: '$(System.DefaultWorkingDirectory)/releasenotes-attachments/Technical-release-summary.md'
    templateLocation: InLine
    inlinetemplate: |
     # Notes for release {{buildDetails.definition.name}}   
     **Build Number**  : {{buildDetails.buildNumber}}
     **Build started** : {{buildDetails.startTime}}  
     **Compared Build Number**  : {{compareBuildDetails.buildNumber}}

     # Builds with associated WI/CS ({{builds.length}})
     {{#forEach builds}}
     {{#if isFirst}}## Builds {{/if}}
     -  Build {{this.build.buildNumber}}
     {{#forEach this.workitems}}
        - WI {{this.id}}
           - **Title** {{lookup this.fields 'System.Title'}}
     {{/forEach}} 
     {{#forEach this.tests}}
        - Test {{this.id}} 
           -  **Name** {{this.testCase.name}}
           -  **Outcome** {{this.outcome}}
     {{/forEach}} 
     {{/forEach}}
     
     # Global list of test ({{tests.length}})
     {{#forEach tests}}
     {{#if isFirst}}### Tests {{/if}}
     * ** Name: {{this.testCase.name}} ** 
        -  Outcome: {{this.outcome}}
     {{/forEach}}
    checkStage: true
    dumpPayloadToFile: true
    dumpPayloadFileName: '$(System.DefaultWorkingDirectory)/releasenotes-attachments/handlebars_payload.json'
```
4. Add a artifact
5. Generate release notes
6. change the build of a artifacts
7. rerun pipeline

### Expected Behavior

I would expect the pipeline to use the new build.

### Logging Information

```

  statusCode: 400,
Total Release Tests: [0]
  result:
Total Tests: [0]
   { '$id': '1',
Total Manual Test Runs: [0]
     innerException: null,
Total Manual Test Configurations: [0]
     message:
Total Pull Requests: [0]
      'Build pipeline \'Docker Container - Hashicorp Vault\' does not match build pipeline \'SalvadorVault\'',
Total Indirect Pull Requests: [0]
     typeName:
Total Associated Test WI: [0]
      'Microsoft.TeamFoundation.Build.WebApi.DefinitionNotMatchedException, Microsoft.TeamFoundation.Build2.WebApi',
Total Consumed Artifacts: [30]
     typeKey: 'DefinitionNotMatchedException',
Total WIQL Workitems: [0]
     errorCode: 0,
     eventId: 3000 } }
Writing payload data to file D:\a\1\s/releasenotes-attachments/handlebars_payload.json
Generating the release notes, the are 1 template(s) to process
Using in-line template
Loading handlebars-helpers extension
Completed processing template
Writing output file D:\a\1\s/releasenotes-attachments/Technical-release-summary.md
Finished writing output file D:\a\1\s/releasenotes-attachments/Technical-release-summary.md
Output variable 'undefined' set to value of first generated release notes
##[warning]Release notes generation had an issue and was only partially successful
Finishing: Generate Release Notes based on Release Comparison API

```

**Comment by rfennell** [comment]
Can you upload the bull release notes task log, with the `system.debug=true` diagnostic logging enable.

**Comment by CodeGlitcher** [comment]
sure but not much extra is added
I have found out that this only occours in yaml pipeline, not in the classic release pipeline.

'''
2022-09-07T12:06:23.1111514Z ##[debug]Evaluating condition for step: 'Generate Release Notes based on Release Comparison API'
2022-09-07T12:06:23.1113621Z ##[debug]Evaluating: SucceededNode()
2022-09-07T12:06:23.1114076Z ##[debug]Evaluating SucceededNode:
2022-09-07T12:06:23.1115096Z ##[debug]=> True
2022-09-07T12:06:23.1115501Z ##[debug]Result: True
2022-09-07T12:06:23.1115918Z ##[section]Starting: Generate Release Notes based on Release Comparison API
2022-09-07T12:06:23.1444165Z ==============================================================================
2022-09-07T12:06:23.1444452Z Task         : Generate Release Notes (Crossplatform)
2022-09-07T12:06:23.1444736Z Description  : Generates a release notes file in a format of your choice from the build or release history
2022-09-07T12:06:23.1444982Z Version      : 3.85.2
2022-09-07T12:06:23.1445128Z Author       : Black Marble
2022-09-07T12:06:23.1445462Z Help         : Version: 3.85.2. [More Information](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task/)
2022-09-07T12:06:23.1445887Z ==============================================================================
2022-09-07T12:06:23.2133190Z ##[debug]Using node path: C:\agents\2.210.0\externals\node10\bin\node.exe
2022-09-07T12:06:23.9615456Z ##[debug]agent.TempDirectory=D:\a\_temp
2022-09-07T12:06:23.9735666Z ##[debug]loading inputs and endpoints
2022-09-07T12:06:23.9755971Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2022-09-07T12:06:23.9796621Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2022-09-07T12:06:23.9800649Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2022-09-07T12:06:23.9803997Z ##[debug]loading INPUT_APPENDTOFILE
2022-09-07T12:06:23.9806648Z ##[debug]loading INPUT_CHECKFORMANUALLYLINKEDWI
2022-09-07T12:06:23.9809084Z ##[debug]loading INPUT_CHECKSTAGE
2022-09-07T12:06:23.9812276Z ##[debug]loading INPUT_CONSIDERPARTIALLYSUCCESSFULRELEASES
2022-09-07T12:06:23.9815487Z ##[debug]loading INPUT_CUSTOMHANDLEBARSEXTENSIONFILE
2022-09-07T12:06:23.9818185Z ##[debug]loading INPUT_DUMPPAYLOADFILENAME
2022-09-07T12:06:23.9820587Z ##[debug]loading INPUT_DUMPPAYLOADTOCONSOLE
2022-09-07T12:06:23.9822883Z ##[debug]loading INPUT_DUMPPAYLOADTOFILE
2022-09-07T12:06:23.9825172Z ##[debug]loading INPUT_GETALLPARENTS
2022-09-07T12:06:23.9827552Z ##[debug]loading INPUT_GETINDIRECTPULLREQUESTS
2022-09-07T12:06:23.9829930Z ##[debug]loading INPUT_GETPARENTSANDCHILDREN
2022-09-07T12:06:23.9832184Z ##[debug]loading INPUT_GETPRDETAILS
2022-09-07T12:06:23.9835589Z ##[debug]loading INPUT_GETTESTEDBY
2022-09-07T12:06:23.9838082Z ##[debug]loading INPUT_INLINETEMPLATE
2022-09-07T12:06:23.9840322Z ##[debug]loading INPUT_MAXRETRIES
2022-09-07T12:06:23.9842649Z ##[debug]loading INPUT_OUTPUTFILE
2022-09-07T12:06:23.9845117Z ##[debug]loading INPUT_PAUSETIME
2022-09-07T12:06:23.9847396Z ##[debug]loading INPUT_REPLACEFILE
2022-09-07T12:06:23.9849647Z ##[debug]loading INPUT_SEARCHCROSSPROJECTFORPRS
2022-09-07T12:06:23.9937771Z ##[debug]loading INPUT_SHOWONLYPRIMARY
2022-09-07T12:06:23.9940560Z ##[debug]loading INPUT_SORTCS
2022-09-07T12:06:23.9942967Z ##[debug]loading INPUT_SORTWI
2022-09-07T12:06:23.9945297Z ##[debug]loading INPUT_STOPONERROR
2022-09-07T12:06:24.0006871Z ##[debug]loading INPUT_STOPONREDEPLOY
2022-09-07T12:06:24.0007816Z ##[debug]loading INPUT_TEMPLATEFILE
2022-09-07T12:06:24.0008379Z ##[debug]loading INPUT_TEMPLATELOCATION
2022-09-07T12:06:24.0008837Z ##[debug]loading INPUT_WIQLFROMTARGET
2022-09-07T12:06:24.0047420Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2022-09-07T12:06:24.0074053Z ##[debug]loaded 31
2022-09-07T12:06:24.0105509Z ##[debug]Agent.ProxyUrl=undefined
2022-09-07T12:06:24.0106653Z ##[debug]Agent.CAInfo=undefined
2022-09-07T12:06:24.0107708Z ##[debug]Agent.ClientCert=undefined
2022-09-07T12:06:24.0108175Z ##[debug]Agent.SkipCertValidation=undefined
2022-09-07T12:06:24.1955149Z ##[debug]Starting Tag XplatGenerateReleaseNotes task
2022-09-07T12:06:24.1956346Z ##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/xxxx/
2022-09-07T12:06:24.1958529Z ##[debug]System.TeamProject=xxx
2022-09-07T12:06:24.1967005Z ##[debug]templateLocation=InLine
2022-09-07T12:06:24.1969197Z ##[debug]templatefile=D:\a\1\s
2022-09-07T12:06:24.1972752Z ##[debug]inlinetemplate=# Notes for release {{buildDetails.definition.name}}   
**Build Number**  : {{buildDetails.buildNumber}}
**Build started** : {{buildDetails.startTime}}  
**Compared Build Number**  : {{compareBuildDetails.buildNumber}}

# Builds with associated WI/CS ({{builds.length}})
{{#forEach builds}}
{{#if isFirst}}## Builds {{/if}}
-  Build {{this.build.buildNumber}}
{{#forEach this.workitems}}
   - WI {{this.id}}
      - **Title** {{lookup this.fields 'System.Title'}}
{{/forEach}} 
{{#forEach this.tests}}
   - Test {{this.id}} 
      -  **Name** {{this.testCase.name}}
      -  **Outcome** {{this.outcome}}
{{/forEach}} 
{{/forEach}}

# Global list of test ({{tests.length}})
{{#forEach tests}}
{{#if isFirst}}### Tests {{/if}}
* ** Name: {{this.testCase.name}} ** 
   -  Outcome: {{this.outcome}}
{{/forEach}}
2022-09-07T12:06:24.1974866Z ##[debug]outputfile=D:\a\1\s/releasenotes-attachments/Technical-release-summary.md
2022-09-07T12:06:24.1975800Z ##[debug]outputVariableName=undefined
2022-09-07T12:06:24.1976463Z ##[debug]showOnlyPrimary=False
2022-09-07T12:06:24.1977135Z ##[debug]replaceFile=True
2022-09-07T12:06:24.1977759Z ##[debug]appendToFile=True
2022-09-07T12:06:24.1978581Z ##[debug]getParentsAndChildren=False
2022-09-07T12:06:24.1980257Z ##[debug]searchCrossProjectForPRs=False
2022-09-07T12:06:24.1981065Z ##[debug]overrideStageName=undefined
2022-09-07T12:06:24.1982750Z ##[debug]stopOnRedeploy=False
2022-09-07T12:06:24.1983748Z ##[debug]SortWi=False
2022-09-07T12:06:24.1985697Z ##[debug]SortCS=False
2022-09-07T12:06:24.1986834Z ##[debug]customHandlebarsExtensionCode=undefined
2022-09-07T12:06:24.1987686Z ##[debug]customHandlebarsExtensionFile=customHandlebarsExtension
2022-09-07T12:06:24.1988210Z ##[debug]customHandlebarsExtensionFolder=undefined
2022-09-07T12:06:24.1988942Z ##[debug]gitHubPat=undefined
2022-09-07T12:06:24.1989662Z ##[debug]bitbucketSecret=undefined
2022-09-07T12:06:24.1990445Z ##[debug]bitbucketUser=undefined
2022-09-07T12:06:24.1991115Z ##[debug]dumpPayloadToFile=true
2022-09-07T12:06:24.1991792Z ##[debug]dumpPayloadToConsole=false
2022-09-07T12:06:24.1992876Z ##[debug]dumpPayloadFileName=D:\a\1\s/releasenotes-attachments/handlebars_payload.json
2022-09-07T12:06:24.1994049Z ##[debug]checkStage=true
2022-09-07T12:06:24.1995673Z ##[debug]getAllParents=False
2022-09-07T12:06:24.1996435Z ##[debug]tags=undefined
2022-09-07T12:06:24.1997135Z ##[debug]overridePat=undefined
2022-09-07T12:06:24.1997883Z ##[debug]overrideBuildReleaseId=undefined
2022-09-07T12:06:24.1998692Z ##[debug]getIndirectPullRequests=False
2022-09-07T12:06:24.1999437Z ##[debug]stopOnError=False
2022-09-07T12:06:24.2000493Z ##[debug]considerPartiallySuccessfulReleases=False
2022-09-07T12:06:24.2001386Z ##[debug]checkForManuallyLinkedWI=False
2022-09-07T12:06:24.2001931Z ##[debug]wiqlWhereClause=undefined
2022-09-07T12:06:24.2003081Z ##[debug]getPRDetails=true
2022-09-07T12:06:24.2004943Z ##[debug]getTestedBy=true
2022-09-07T12:06:24.2005864Z ##[debug]wiqlFromTarget=WorkItems
2022-09-07T12:06:24.2007516Z ##[debug]maxRetries=20
2022-09-07T12:06:24.2044450Z ##[debug]Build.BuildId=65226
2022-09-07T12:06:24.2045246Z ##[debug]Release.ReleaseId=undefined
2022-09-07T12:06:24.2045969Z ##[debug]Release.DefinitionId=undefined
2022-09-07T12:06:24.2046511Z ##[debug]Release_EnvironmentName=undefined
2022-09-07T12:06:24.2046974Z ##[debug]ReleaseNotes.Fix349=undefined
2022-09-07T12:06:24.2132202Z Creating Azure DevOps API connections for https://dev.azure.com/xxxx/ with 'allowRetries' set to 'true' and 'maxRetries' count to '20'
2022-09-07T12:06:24.2134989Z ##[debug]Getting System.AccessToken
2022-09-07T12:06:24.2135618Z ##[debug]Getting credentials the agent is running as
2022-09-07T12:06:24.2139585Z ##[debug]SYSTEMVSSCONNECTION exists true
2022-09-07T12:06:24.2140845Z ##[debug]Found an OAUTH token
2022-09-07T12:06:24.2141178Z Creating the credential handler from the OAUTH token
2022-09-07T12:06:24.5565689Z Getting the current build details
2022-09-07T12:06:24.7154792Z ##[debug]System.StageName=ReleaseNotes
2022-09-07T12:06:24.7155342Z Getting items associated the builds since the last successful build to the stage 'ReleaseNotes'
2022-09-07T12:06:24.7719039Z Found '3' matching builds to consider
2022-09-07T12:06:24.7719574Z Matching 'successful' builds only 
2022-09-07T12:06:24.7719972Z Comparing 65226 against 65226
2022-09-07T12:06:24.7720250Z Ignore compare against self
2022-09-07T12:06:24.7721807Z Comparing 65223 against 65226
2022-09-07T12:06:24.7722203Z Considering build
2022-09-07T12:06:25.0333749Z Found required stage Release notes in the state 2 with the result 0 state for build 65223
2022-09-07T12:06:25.0334366Z Using the build 65223
2022-09-07T12:06:25.0334619Z Getting the details between 65223 and 65226
2022-09-07T12:06:25.1136615Z Using workaround for build API limitation (see issue #349)
2022-09-07T12:06:25.1579829Z ##[debug]ReleaseNotes.Fix349.MaxCommits=undefined
2022-09-07T12:06:25.1580500Z ##[debug]ReleaseNotes.Fix349.MaxWorkItems=undefined
2022-09-07T12:06:25.3274772Z Processing commits found
2022-09-07T12:06:25.4452323Z Getting changes for the 'Pipeline' artifact 'ActiveMQArtemisBase' between 55440 and 55440
2022-09-07T12:06:25.7293914Z Enriched change fa6e31296636c3e346f0b3684e115c385cfb2661 of type TfsGit
2022-09-07T12:06:25.9285809Z Enriched with details of 38 files
2022-09-07T12:06:51.7762205Z Adding [1] items
2022-09-07T12:06:51.7762779Z Getting changes for the 'Pipeline' artifact 'SalvadorVault' between 64406 and 64410
2022-09-07T12:06:51.8409463Z The most common runtime reason for the task to fail is due API ECONNRESET issues. To avoid this failing the pipeline these will be treated as warnings and an attempt to generate any release notes possible
2022-09-07T12:06:51.8432624Z { Error: Build pipeline 'Docker Container - Hashicorp Vault' does not match build pipeline 'SalvadorVault'
2022-09-07T12:06:51.8434343Z Total Builds: [0]
2022-09-07T12:06:51.8434735Z Total Commits: [1]
2022-09-07T12:06:51.8435071Z Total Workitems: [0]
2022-09-07T12:06:51.8435448Z Total Related Workitems (Parent/Children): [0]
2022-09-07T12:06:51.8435876Z Total Release Tests: [0]
2022-09-07T12:06:51.8437205Z     at RestClient.<anonymous> (D:\a\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.85.2\node_modules\typed-rest-client\RestClient.js:202:31)
2022-09-07T12:06:51.8438297Z     at Generator.next (<anonymous>)
2022-09-07T12:06:51.8439265Z     at fulfilled (D:\a\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.85.2\node_modules\typed-rest-client\RestClient.js:6:58)
2022-09-07T12:06:51.8440365Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2022-09-07T12:06:51.8440944Z   statusCode: 400,
2022-09-07T12:06:51.8441316Z   result:
2022-09-07T12:06:51.8441687Z    { '$id': '1',
2022-09-07T12:06:51.8442086Z      innerException: null,
2022-09-07T12:06:51.8442472Z      message:
2022-09-07T12:06:51.8443146Z       'Build pipeline \'Docker Container - Hashicorp Vault\' does not match build pipeline \'SalvadorVault\'',
2022-09-07T12:06:51.8443765Z      typeName:
2022-09-07T12:06:51.8445064Z       'Microsoft.TeamFoundation.Build.WebApi.DefinitionNotMatchedException, Microsoft.TeamFoundation.Build2.WebApi',
2022-09-07T12:06:51.8445941Z      typeKey: 'DefinitionNotMatchedException',
2022-09-07T12:06:51.8446438Z      errorCode: 0,
2022-09-07T12:06:51.8446829Z      eventId: 3000 } }
2022-09-07T12:06:51.8447197Z Total Tests: [0]
2022-09-07T12:06:51.8447562Z Total Manual Test Runs: [0]
2022-09-07T12:06:51.8448029Z Total Manual Test Configurations: [0]
2022-09-07T12:06:51.8448763Z Total Pull Requests: [0]
2022-09-07T12:06:51.8449244Z Total Indirect Pull Requests: [0]
2022-09-07T12:06:51.8449706Z Total Associated Test WI: [0]
2022-09-07T12:06:51.8450187Z Total Consumed Artifacts: [24]
2022-09-07T12:06:51.8450633Z Total WIQL Workitems: [0]
2022-09-07T12:06:51.8740235Z Writing payload data to file D:\a\1\s/releasenotes-attachments/handlebars_payload.json
2022-09-07T12:06:51.9133340Z Generating the release notes, the are 1 template(s) to process
2022-09-07T12:06:51.9137180Z ##[debug]Using template mode InLine
2022-09-07T12:06:51.9138914Z Using in-line template
2022-09-07T12:06:51.9139888Z ##[debug]Loading handlebar template
2022-09-07T12:06:51.9146298Z ##[debug]Processing template
2022-09-07T12:06:51.9147062Z ##[debug]  WI: 0
2022-09-07T12:06:51.9147700Z ##[debug]  CS: 1
2022-09-07T12:06:51.9148141Z ##[debug]  PR: 0
2022-09-07T12:06:51.9148520Z ##[debug]  Builds: 0
2022-09-07T12:06:51.9148931Z ##[debug]  Manual Tests: 0
2022-09-07T12:06:51.9149389Z ##[debug]  Manual TestConfigurations: 0
2022-09-07T12:06:51.9149821Z ##[debug]  Release Tests: 0
2022-09-07T12:06:51.9150236Z ##[debug]  Related WI: 0
2022-09-07T12:06:51.9150651Z ##[debug]  Related Tests: 0
2022-09-07T12:06:51.9151047Z ##[debug]  Indirect PR: 0
2022-09-07T12:06:51.9151472Z ##[debug]  Consumed Artifacts: 24
2022-09-07T12:06:51.9151892Z ##[debug]  Query WI: 0
2022-09-07T12:06:51.9152332Z ##[debug]Processing handlebar template
2022-09-07T12:06:51.9850647Z Loading handlebars-helpers extension
2022-09-07T12:06:52.1193314Z ##[debug]Attempting to load custom handlebars extension from D:\a\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.85.2\customHandlebarsExtension.js}
2022-09-07T12:06:52.1194803Z ##[debug]Custom handlebars extension file does not exist
2022-09-07T12:06:52.2785409Z Completed processing template
2022-09-07T12:06:52.2786268Z Writing output file D:\a\1\s/releasenotes-attachments/Technical-release-summary.md
2022-09-07T12:06:52.2788592Z Finished writing output file D:\a\1\s/releasenotes-attachments/Technical-release-summary.md
2022-09-07T12:06:52.2789324Z Output variable 'undefined' set to value of first generated release notes
2022-09-07T12:06:52.2791974Z ##[debug]task result: SucceededWithIssues
2022-09-07T12:06:52.2820773Z ##[warning]Release notes generation had an issue and was only partially successful
2022-09-07T12:06:52.2831221Z ##[debug]Processed: ##vso[task.issue type=warning;]Release notes generation had an issue and was only partially successful
2022-09-07T12:06:52.2838417Z ##[debug]Processed: ##vso[task.complete result=SucceededWithIssues;]Release notes generation had an issue and was only partially successful
2022-09-07T12:06:52.3035642Z ##[section]Finishing: Generate Release Notes based on Release Comparison API 
'''
