### ISSUE TITLE
Versioning/VersionAssembliesTask not supported on MacOS agents

### ISSUE THREAD

**Issue by jasells** [rfennell/AzurePipelines#1507]
Is there any chance of getting an update to allow this to run on MacOS agent?  I am using several of the other versioning tools on Mac agents, but this one blows up, and it would be useful to version some Android libraries that I am packing together.  As of now, I can version the one .net standard assembly in the package, just not the platform-specifc ones, since they don't show up as .net core.  

Don't know if this helps any: 

```
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
##[debug]System.InvalidOperationException: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /Users/runner/work/1/s/src/Agent.Worker/TaskRunner.cs:line 117
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /Users/runner/work/1/s/src/Agent.Worker/StepsRunner.cs:line 219

```

**Comment by rfennell** [comment]
The `VersionAssemblies` task will never support MacOS as it is the original .NET Framework (2, 3, 4) only. But the good news is for .NET Core and all the modern variants i.e. 5 onward use the `VersionDotNetCoreAssemblies`
