### ISSUE TITLE
Tool Erroring out on temp file - System.IO.IOException: The process cannot access the file '...Local\Temp\tmp1F05.html' because it is being used by another process.

### ISSUE THREAD

**Issue by annabelspain** [rfennell/AzurePipelines#2043]
### Azure DevOps Extensions

WIKI PDF Generator

### Platform

Azure DevOps Services

### Extension Version

3

### Describe the bug

When running the tool to export my wiki to PDF, both locally and when using DevOps pipeline I am getting the same error on each run relating to the process not be able to access a temp file, even though this temp file does not exist.

**Local Method:**
The wiki has been cloned, saved locally, with version 4.6.0 WikiPDFExport downloaded and used within the folder structure. The steps mentioned within the "quick start" guide were followed (https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport?tab=readme-ov-file#-quickstart). After running the tool, the error appears briefly within the console before exiting the run and closing the command prompt. Please see below the error seen using the local method:

![image](https://github.com/user-attachments/assets/72007199-4c48-4845-a69e-4988b630af11)

**DevOps Method:**
The wiki is saved as "wiki as code" repository in DevOps. A yaml pipeline has been created which uses the Wiki PDF Export Tasks (https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-WikiPDFExport-Tasks&ssr=false#overview), that wraps the WikiPDFExport tool. The pipeline contains three tasks, one to install dotnet 6 onto the build agent, then to run the task as follows below, and the final task publishes the private wiki export as a pipeline artifact. :
- task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@3 displayName: 'Export a private Azure DevOps WIKI'

System.IO.IOException: The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\Temp\tmp1F05.html' because it is being used by another process.
at System.IO.FileSystem.DeleteFile(String fullPath)
at System.IO.FileInfo.Delete()
at azuredevops_export_wiki.SelfDeletingTemporaryFile.Dispose(Boolean disposing)
at azuredevops_export_wiki.SelfDeletingTemporaryFile.Dispose()
at azuredevops_export_wiki.WikiPDFExporter.Export()

##[error]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s/repo/Documentation" -o "D:\a\1\a/PDF/Wiki-As-Code.pdf" -v

##[error]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s/repo/Documentation" -o "D:\a\1\a/PDF/Wiki-As-Code.pdf" -v

Finishing: Export a private Azure DevOps WIKI

![image](https://github.com/user-attachments/assets/70b2469a-f3b0-46c7-b718-19f760be1e8f)

Other points to note:

- The .order files sit within each section of the folder structure to define the sort order of pages.
- Verbose logging has also been activated within the DevOps method, showing that the pipeline iterates through all pages within the wiki, until completing the final page conversion before erroring out on the temp file error seen in the screenshots above.
- Additional PowerShell logic has also been tested within the DevOps pipeline, including; checking for concurrent processes, ignore flags on temporary files, remove flags on temporary files, updating to use a unique temporary directory, retry logic to attempt the process three times before sending the error, additional verbose logging and adding delays before and after conversion.
- Each time the process is ran across both methods the same error occurs, but the name of each temporary file is different each time.

Any suggestions to get around this error would be really appreciated, thank you for your time!

### Repo Steps

1. Run a pipeline which include the task in DevOps
2. The pipeline logs show that the tool iterates through all pages of the wiki 
3. On the final export stage the pipeline fails on the error

### Expected Behavior

The last successful pipeline run utilizes the same DevOps method mentioned above, but since then the wiki has been updated to include many additional folders and pages. The expected behavior is that once the pipeline has run successfully, a PDF artifact will be available to download. 

### Logging Information

<img width="763" alt="image" src="https://github.com/user-attachments/assets/bbebdec2-ab6b-4af7-8987-39f0984a8a7b" />

**Comment by rfennell** [comment]
I can see from the logs you provided that the command line tool is running but failing. 

My task is just a wrapper around Max Melcher's [AzureDevOps.WikiPDFExport command line tool](https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport), and processing issue with the command line tool need to be logged at https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/issues
