### ISSUE TITLE
Sporadic failures in setup of Pester test runner task (ManagementException)

### ISSUE THREAD

**Issue by bergmeister** [rfennell/AzurePipelines#364]
### VSTS Extension you are using
Pester test runner
### Where are you running it?
`VSTS`

### Version of Extension/Task
8.5.1 (latest public)

### Description

In the last days we started to see errors in the Pester task runner setup. It can still run all tests OK, but the fact that the thrown ManagementException gets reported as an error, results in orange builds.

```
2018-08-24T09:35:05.4959395Z ##[section]Starting: Pester Test Runner
2018-08-24T09:35:05.5009870Z ==============================================================================
2018-08-24T09:35:05.5010108Z Task         : Pester Test Runner from Black Marble
2018-08-24T09:35:05.5010388Z Description  : Run Pester tests by either installing the latest version of Pester at run time (if possible) or using the version shipped with the task (4.3.1)
2018-08-24T09:35:05.5010627Z Version      : 8.5.1
2018-08-24T09:35:05.5010799Z Author       : Richard Fennell
2018-08-24T09:35:05.5011032Z Help         : Version: 8.5.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/Pester-Task/)
2018-08-24T09:35:05.5011286Z ==============================================================================
2018-08-24T09:35:05.5135611Z Preparing task execution handler.
2018-08-24T09:35:06.1246001Z Executing the powershell script: D:\_Builds\RCSSV-EM20-005T.01\_tasks\Pester_31ef0033-64e3-4c55-b888-f446541474a6\8.5.1\Pester.ps1
2018-08-24T09:35:06.3225910Z Running in AMD64 PowerShell
2018-08-24T09:35:06.3226168Z 
2018-08-24T09:35:06.3226259Z 
2018-08-24T09:35:06.3264351Z Adding additional module path [] to $env:PSModulePath
2018-08-24T09:35:06.3264642Z 
2018-08-24T09:35:06.3264820Z 
2018-08-24T09:35:07.7267011Z ##[error]System.Management.ManagementException: Generic failure 
2018-08-24T09:35:07.7276375Z    at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
2018-08-24T09:35:07.7276672Z    at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
2018-08-24T09:35:07.7277164Z    at Microsoft.PowerShell.Commands.TestConnectionCommand.processDCOMProtocolForTestConnection()
2018-08-24T09:35:15.9312539Z Running Pester from the folder [H:\Integration Test\Tests\PowerShellCmdlets.PesterTests] output sent to [D:\_Builds\RCSSV-EM20-005T.01\r1\a\Pester_NUnit_Outputfile.xml]
2018-08-24T09:35:15.9313037Z 
2018-08-24T09:35:15.9313133Z 
2018-08-24T09:35:16.2886239Z Executing all tests in 'H:\Integration Test\Tests\PowerShellCmdlets.PesterTests'
... [Test execute fine as usual...]
```

The System is a fully patched WinServer 2012R2 with PS 5.1:
```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLGardner** [comment]
I'll try to have a look at this in the next few days. I have my suspicions on what's causing this but could you drop a full debug log in here or via email/slack?

**Comment by bergmeister** [comment]
@ChrisLGardner Because the tests are in a release definition, there is no equivalent option to `New build with diagnostic logs` similar to builds (or I am not aware of it yet). Otherwise I have already included all logs I can.

**Comment by ChrisLGardner** [comment]
You can manually set the system.debug value to true on a release and it will generate the logs. You can do this within a release you've already created rather than the definition to save you needing to update that and do a full release, that would also allow you to disable all but the test step and save a full redeploy.
________________________________

**Comment by ChrisLGardner** [comment]
Tracking over in the new repo in case it reappears.
