### ISSUE TITLE
Multiple Version Layout Support - multiple test folders

### ISSUE THREAD

**Issue by jdholbrook81** [rfennell/AzurePipelines#389]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*
Pester Test Runner from Black Marble v8.*

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
8.* (currently available public)

### Expected behaviour and actual behaviour
I have multiple versions of my task available as documented here: https://docs.microsoft.com/en-us/azure/devops/extend/develop/build-task-schema?view=vsts#bundle-multiple-versions-of-build-tasks-within-one-extension

I'm using the "Multiple version layout" So I have Tests folder beneath each version folder. Ex: 
extensionManifest.json
extensionIcon.png
Task1
--Task1V1
----Tests
------InterestingTestName.tests.ps1
----task.json
----icon.png
----taskScript.ps1
--Task1V2
----Tests
------InterestingTestName.tests.ps1
----task.json
----icon.png
----taskScript.ps1

Expected result:
If I provide a path using a minimatch globstar to multiple folders containing *test.ps1 I expect them to execute. I do not expect to have to hardcode to specific subfolders or run the task multiple times.

### Steps to reproduce the problem
Input:
$(Build.SourcesDirectory)\Tasks\\**\Tests\\*.tests.ps1

Results:
2018-10-22T14:27:03.9635728Z Running Pester from using the script parameter [D:\a\1\s\Tasks\**\Tests\*.tests.ps1] output sent to [D:\a\1\s\Test-Pester.XML]
2018-10-22T14:27:03.9636019Z 
2018-10-22T14:27:03.9636174Z 
2018-10-22T14:27:04.0917989Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2018-10-22T14:27:04.0928923Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2018-10-22T14:27:04.0929315Z    at CallSite.Target(Closure , CallSite , Object )
2018-10-22T14:27:04.0929392Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2018-10-22T14:27:04.0929491Z    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
2018-10-22T14:27:04.0929560Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by ChrisLGardner** [comment]
Hi

Can you run the build with system.debug set to true and post the logs for this task?

Is there any reason you're specifying the path all the way to the tests? You could just point it at /Task1 and pester will find all of the *.tests.ps1 for you.

I'll look into this further when I get a chance but it might be a few days or a little more.
________________________________

**Comment by jdholbrook81** [comment]
Hi Chris. I glossed over in your document that "Scripts Folder or Script" takes in the "root" folder for test scripts. I was explicit with the path because I thought I had to get all the way to the folder that contained the tests.ps1 files. I tried your suggestion and that works fine, thank you. 

Maybe an example in the doc would help others?

**Comment by rfennell** [comment]
Closing this as on re-reading I think we have a work around. 

Reopen if this is not the case
