### ISSUE TITLE
A parameter cannot be found that matches parameter name 'VersionRegex'.

### ISSUE THREAD

**Issue by paljen** [rfennell/AzurePipelines#394]
Hi,

After the version 2.1.7 im having trouble with the extension - Manifest Versioning Build Tasks

I have a build in Azure DevOps (VSTS) where i use the task - Version PowerShell Module and im getting the following error (debug output) :

2018-10-31T14:20:04.6829069Z ##[debug]Evaluating condition for step: 'Version PowerShell Modules'
2018-10-31T14:20:04.6829531Z ##[debug]Evaluating: succeeded()
2018-10-31T14:20:04.6829639Z ##[debug]Evaluating succeeded:
2018-10-31T14:20:04.6829789Z ##[debug]=> True
2018-10-31T14:20:04.6830124Z ##[debug]Result: True
2018-10-31T14:20:04.6830277Z ##[section]Starting: Version PowerShell Modules
2018-10-31T14:20:04.6833122Z ==============================================================================
2018-10-31T14:20:04.6833170Z Task         : Version PowerShell Module
2018-10-31T14:20:04.6833199Z Description  : Applies specified version number to one or more PowerShell modules in a target folder.
2018-10-31T14:20:04.6833246Z Version      : 2.1.7
2018-10-31T14:20:04.6833275Z Author       : Black Marble
2018-10-31T14:20:04.6833304Z Help         : Version: 2.1.7. [More Information](https://github.com/rfennell/vNextBuild/wiki/Version-Assemblies-and-Packages-Tasks/)
2018-10-31T14:20:04.6833510Z ==============================================================================
2018-10-31T14:20:04.6839117Z Preparing task execution handler.
2018-10-31T14:20:04.8803278Z Executing the powershell script: D:\a\_tasks\VersionPowerShellModule_036278fe-8a47-426b-b5b3-bef05334db00\2.1.7\Update-PowerShellModuleVersion.ps1
2018-10-31T14:20:04.8804962Z ##[debug]PowerShellHandler.Execute - AddCommand(D:\a\_tasks\VersionPowerShellModule_036278fe-8a47-426b-b5b3-bef05334db00\2.1.7\Update-PowerShellModuleVersion.ps1)
2018-10-31T14:20:04.8805147Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2018-10-31T14:20:04.8805708Z ##[debug]PowerShellHandler.Execute - AddParameter(Path=D:\a\1\s)
2018-10-31T14:20:04.8806210Z ##[debug]PowerShellHandler.Execute - AddParameter(VersionNumber=1.0.0.219)
2018-10-31T14:20:04.8806640Z ##[debug]PowerShellHandler.Execute - AddParameter(OutputVersion=OutputedVersion)
2018-10-31T14:20:04.8807033Z ##[debug]PowerShellHandler.Execute - AddParameter(VersionRegex=\d+\.\d+\.\d+\.\d+)
2018-10-31T14:20:04.9622691Z ##[debug]PowerShellHandler.Execute - Invoke
2018-10-31T14:20:05.1930952Z ##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'VersionRegex'.
2018-10-31T14:20:05.1944907Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'VersionRegex'.
2018-10-31T14:20:05.1945152Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-10-31T14:20:05.1945213Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-10-31T14:20:05.1945272Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-10-31T14:20:05.1992114Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-31T14:20:05.1992245Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-10-31T14:20:05.1992293Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-10-31T14:20:05.2052839Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2018-10-31T14:20:05.2055910Z ##[section]Finishing: Version PowerShell Modules

This is not the fist time im getting this error with 2.1.7 but last time i got help from one of you it magically got solved by it self somehow, but this time it wont go away ;)

prior to 2.1.7 i had no problem and everything worked as it should, the success would be that the .*psd1 manifest file would be updated with the build version like 1.0.0.($buildnumber), in this case 1.0.0.219

Regards

Palle Jensen

### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

Manifest Versioning Build Tasks

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

**Comment by ChrisLGardner** [comment]
Hi

The problem is we've actually removed that parameter so that's why it's failing. If you open your build definition you should be able to expand the Advanced section and see it's not there. I'd suggest making a change to the definition, add a variable or something similar, and save it and that should update it to use the new definition for the task. 

If you're using yaml builds then just remove the parameter from the yaml file.

**Comment by paljen** [comment]
Hi Chris

Thank you for the quick reply!

I exported the build, adjusted the json file by removing the VersionRegex parameter as described above and re-imported the json file.

That did solve the issue, thank you!

Best regards

Palle Jensen

**Comment by ChrisLGardner** [comment]
This should no longer be an issue.
