### ISSUE TITLE
Missing comma in param block

### ISSUE THREAD

**Issue by mcowley5** [rfennell/AzurePipelines#406]
Missing comma in the param block

https://github.com/rfennell/AzurePipelines/blob/89989eb27fbbabc87881604665f90cd526d5c47f/Extensions/Versioning/VersionSharepointAppManifestTask/ApplyBuildVersionToSharepointAppManifest.ps1#L23

Causes error:
```
2018-12-14T12:18:49.4242817Z ##[error]System.Management.Automation.ParseException: At F:\AGENT1\_work\_tasks\VersionSharepointAppManifest_2d932e86-7068-4a1e-ab4d-f104fad6db37\2.3.21\ApplyBuildVersionToSharepointAppManifest.ps1:23 char:19
2018-12-14T12:18:49.4243149Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParseException: At F:\AGENT1\_work\_tasks\VersionSharepointAppManifest_2d932e86-7068-4a1e-ab4d-f104fad6db37\2.3.21\ApplyBuildVersionToSharepointAppManifest.ps1:23 char:19
2018-12-14T12:18:49.4243441Z +     $InjectVersion
2018-12-14T12:18:49.4243502Z +                   ~
2018-12-14T12:18:49.4243551Z Missing ')' in function parameter list.
2018-12-14T12:18:49.4243578Z 
2018-12-14T12:18:49.4243624Z At F:\AGENT1\_work\_tasks\VersionSharepointAppManifest_2d932e86-7068-4a1e-ab4d-f104fad6db37\2.3.21\ApplyBuildVersionToSharepointAppManifest.ps1:28 char:1
2018-12-14T12:18:49.4243661Z + )
2018-12-14T12:18:49.4243708Z + ~
2018-12-14T12:18:49.4243747Z Unexpected token ')' in expression or statement.
2018-12-14T12:18:49.4243788Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-12-14T12:18:49.4243838Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-12-14T12:18:49.4243894Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-12-14T12:18:49.4243942Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-12-14T12:18:49.4244765Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-12-14T12:18:49.4244814Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-12-14T12:18:49.4347667Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
```

**Comment by ChrisLGardner** [comment]
Released as part of 2.4.x
