### ISSUE TITLE
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'AllowPrerelease'.

### ISSUE THREAD

**Issue by JamieTaffurelli** [rfennell/AzurePipelines#415]
### Azure DevOps Extension
Pester Test Runner

### Where am I running it?

- Azure DevOps Service (VSTS)

### Version of Extension/Task
8.9.1

### Expected behaviour and actual behaviour
Expected pester tests to run, task fails with following error:

2019-01-07T10:04:18.4945939Z ##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'AllowPrerelease'.
2019-01-07T10:04:18.4956622Z    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
2019-01-07T10:04:18.4957680Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
2019-01-07T10:04:18.4957857Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
2019-01-07T10:04:18.4958034Z    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
2019-01-07T10:04:18.4958299Z    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
2019-01-07T10:04:18.4958540Z    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
2019-01-07T10:04:18.4958694Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2019-01-07T10:04:18.4958858Z --- End of stack trace from previous location where exception was thrown ---
2019-01-07T10:04:18.4960184Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-07T10:04:18.4960615Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2019-01-07T10:04:18.4960798Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-07T10:04:18.4960987Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-07T10:04:18.4961126Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-07T10:04:18.4961272Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

### Steps to reproduce the problem
Looks to be related to the fact that PR 413 added a switch parameter that is only supported in PowerShellGet versions 1.6 and above. The servers that we provision have a lower version than this.

**Comment by ChrisLGardner** [comment]
I'm working on fixing this now and should have a new version out in the next hour or so. I should have #414 merged soon.

**Comment by JamieTaffurelli** [comment]
Great, thanks very much

**Comment by ChrisLGardner** [comment]
I've reverted the change I'd made and 8.10.x should be available now. I'm going to work on a better fix for the issue in #412 and hopefully have that out soon.

Which version of PowerShellGet are you running?
