### ISSUE TITLE
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by Emil-H** [rfennell/AzurePipelines#429]
### Azure DevOps Extension you are using
Generate Release Notes

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.23.1

### Steps to reproduce the problem
I've been using Generate release notes for a while now. We are using our own local build agent. After reinstalling build agent to a new folder, we started to get the following errors when generating release logs:
2019-02-06T14:50:18.6035423Z ##[section]Starting: Generate release notes
2019-02-06T14:50:18.6041159Z ==============================================================================
2019-02-06T14:50:18.6041236Z Task         : Generate Release Notes
2019-02-06T14:50:18.6041280Z Description  : Generates a release notes file in a format of your choice
2019-02-06T14:50:18.6041334Z Version      : 2.23.1
2019-02-06T14:50:18.6041395Z Author       : Black Marble
2019-02-06T14:50:18.6041438Z Help         : Version: 2.23.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2019-02-06T14:50:18.6041480Z ==============================================================================
2019-02-06T14:50:18.6183912Z Preparing task execution handler.
2019-02-06T14:50:18.9894762Z Executing the powershell script: D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\GenerateReleaseNotes.ps1
2019-02-06T14:50:18.9895523Z $(($releases | select-object -ExpandProperty name) -join ", " )   
2019-02-06T14:50:18.9895638Z ##Builds   
2019-02-06T14:50:18.9895690Z @@BUILDLOOP@@   
2019-02-06T14:50:18.9895739Z **Build Number**: $($build.buildnumber)   
2019-02-06T14:50:18.9895788Z ###Associated work items   
2019-02-06T14:50:18.9895836Z @@WILOOP@@   
2019-02-06T14:50:18.9895914Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo'.'displayName')]  $($widetail.fields.'System.Title')   
2019-02-06T14:50:18.9895982Z @@WILOOP@@   
2019-02-06T14:50:18.9896031Z ### Associated change sets/commits   
2019-02-06T14:50:18.9896095Z @@CSLOOP@@   
2019-02-06T14:50:18.9896144Z * $($csdetail.author.name): $($csdetail.comment)   
2019-02-06T14:50:18.9896192Z @@CSLOOP@@   
2019-02-06T14:50:18.9896239Z @@BUILDLOOP@@)
2019-02-06T14:50:19.6863702Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
2019-02-06T14:50:19.6888784Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2019-02-06T14:50:19.6889530Z    at System.Net.WebClient.DownloadString(Uri address)
2019-02-06T14:50:19.6890136Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-06T14:50:19.6890958Z    --- End of inner exception stack trace ---
2019-02-06T14:50:19.6892183Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2019-02-06T14:50:19.6892388Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-06T14:50:19.6892583Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2019-02-06T14:50:19.6892753Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-02-06T14:50:19.6892935Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-06T14:50:19.8791685Z ##[error]PowerShell script completed with 1 errors.
2019-02-06T14:50:19.8798775Z ##[section]Finishing: Generate release notes

**Comment by Emil-H** [comment]
When running on hosted agent everything is fine, the build succeeds. After this I did a new release on our private agent which failed.

Could the double slash be the problem here?

> 2019-02-07T07:29:24.1027292Z ##[debug]Getting details of release by definition [4] from server [https://dev.azure.com/juladevelopment//StoreInformation]

-------------

2019-02-07T07:29:22.8949581Z ##[debug]Evaluating condition for step: 'Generate release notes'
2019-02-07T07:29:22.8950474Z ##[debug]Evaluating: succeeded()
2019-02-07T07:29:22.8950587Z ##[debug]Evaluating succeeded:
2019-02-07T07:29:22.8950785Z ##[debug]=> True
2019-02-07T07:29:22.8951003Z ##[debug]Result: True
2019-02-07T07:29:22.8951224Z ##[section]Starting: Generate release notes
2019-02-07T07:29:22.8957193Z ==============================================================================
2019-02-07T07:29:22.8957288Z Task         : Generate Release Notes
2019-02-07T07:29:22.8957332Z Description  : Generates a release notes file in a format of your choice
2019-02-07T07:29:22.8957376Z Version      : 2.23.1
2019-02-07T07:29:22.8957434Z Author       : Black Marble
2019-02-07T07:29:22.8957480Z Help         : Version: 2.23.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2019-02-07T07:29:22.8957524Z ==============================================================================
2019-02-07T07:29:22.9114365Z Preparing task execution handler.
2019-02-07T07:29:24.0463813Z Executing the powershell script: D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\GenerateReleaseNotes.ps1
2019-02-07T07:29:24.0738687Z ##[debug]PowerShellHandler.Execute - AddCommand(D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\GenerateReleaseNotes.ps1)
2019-02-07T07:29:24.0743900Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2019-02-07T07:29:24.0744398Z ##[debug]PowerShellHandler.Execute - AddParameter(outputfile=D:\vsts_build\_work\r3\a\releasenotes.md)
2019-02-07T07:29:24.0759269Z ##[debug]PowerShellHandler.Execute - AddParameter(outputVariableName=)
2019-02-07T07:29:24.0760270Z ##[debug]PowerShellHandler.Execute - AddParameter(templateLocation=InLine)
2019-02-07T07:29:24.0760575Z ##[debug]PowerShellHandler.Execute - AddParameter(templatefile=D:\vsts_build\ReleaseLogTemplate.txt)
2019-02-07T07:29:24.0760816Z ##[debug]PowerShellHandler.Execute - AddParameter(inlinetemplate=Changes since last successful release to **'$stagename'** Including releases:   
2019-02-07T07:29:24.0761030Z $(($releases | select-object -ExpandProperty name) -join ", " )   
2019-02-07T07:29:24.0761196Z ##Builds   
2019-02-07T07:29:24.0761340Z @@BUILDLOOP@@   
2019-02-07T07:29:24.0761501Z **Build Number**: $($build.buildnumber)   
2019-02-07T07:29:24.0761644Z ###Associated work items   
2019-02-07T07:29:24.0761784Z @@WILOOP@@   
2019-02-07T07:29:24.0761950Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo'.'displayName')]  $($widetail.fields.'System.Title')   
2019-02-07T07:29:24.0762092Z @@WILOOP@@   
2019-02-07T07:29:24.0762234Z ### Associated change sets/commits   
2019-02-07T07:29:24.0762388Z @@CSLOOP@@   
2019-02-07T07:29:24.0762530Z * $($csdetail.author.name): $($csdetail.comment)   
2019-02-07T07:29:24.0762679Z @@CSLOOP@@   
2019-02-07T07:29:24.0762816Z @@BUILDLOOP@@)
2019-02-07T07:29:24.0763016Z ##[debug]PowerShellHandler.Execute - AddParameter(usedefaultcreds=False)
2019-02-07T07:29:24.0763192Z ##[debug]PowerShellHandler.Execute - AddParameter(emptySetText=None)
2019-02-07T07:29:24.0763379Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForOnlyPrimary=False)
2019-02-07T07:29:24.0763551Z ##[debug]PowerShellHandler.Execute - AddParameter(generateForCurrentRelease=false)
2019-02-07T07:29:24.0763736Z ##[debug]PowerShellHandler.Execute - AddParameter(overrideStageName=)
2019-02-07T07:29:24.0763907Z ##[debug]PowerShellHandler.Execute - AddParameter(maxWi=50)
2019-02-07T07:29:24.0764095Z ##[debug]PowerShellHandler.Execute - AddParameter(maxChanges=50)
2019-02-07T07:29:24.0764268Z ##[debug]PowerShellHandler.Execute - AddParameter(appendToFile=False)
2019-02-07T07:29:24.0764456Z ##[debug]PowerShellHandler.Execute - AddParameter(showParents=False)
2019-02-07T07:29:24.0764627Z ##[debug]PowerShellHandler.Execute - AddParameter(wiFilter=)
2019-02-07T07:29:24.0765688Z ##[debug]PowerShellHandler.Execute - AddParameter(wiStateFilter=)
2019-02-07T07:29:24.0765872Z ##[debug]PowerShellHandler.Execute - AddParameter(unifiedList=False)
2019-02-07T07:29:24.0766066Z ##[debug]PowerShellHandler.Execute - Invoke
2019-02-07T07:29:24.0766248Z ##[debug]Loading module from path 'D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\GenerateReleaseNotes.psm1'.
2019-02-07T07:29:24.0766447Z ##[debug]Loading module from path 'D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\Get-CallerPreference.ps1'.
2019-02-07T07:29:24.0766624Z ##[debug]Dot-sourcing the script file 'D:\vsts_build\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\Get-CallerPreference.ps1'.
2019-02-07T07:29:24.0766819Z ##[debug]
2019-02-07T07:29:24.0766964Z 	 public enum Mode
2019-02-07T07:29:24.0767102Z 	 {
2019-02-07T07:29:24.0767701Z 			BODY,
2019-02-07T07:29:24.0767845Z 			WI,
2019-02-07T07:29:24.0767991Z 			CS,
2019-02-07T07:29:24.0768143Z 			BUILD
2019-02-07T07:29:24.0768281Z 	 }
2019-02-07T07:29:24.0768464Z ##[debug]Exporting function 'Get-CallerPreference'.
2019-02-07T07:29:24.0768659Z ##[debug]Exporting function 'Use-SystemWebProxy'.
2019-02-07T07:29:24.0768854Z ##[debug]Exporting function 'Get-WorkItemDataFromBuild'.
2019-02-07T07:29:24.0769042Z ##[debug]Exporting function 'Get-CommitInfoFromGitRepo'.
2019-02-07T07:29:24.0769216Z ##[debug]Exporting function 'Expand-WorkItemData'.
2019-02-07T07:29:24.0769400Z ##[debug]Exporting function 'Get-BuildChangeSets'.
2019-02-07T07:29:24.0769571Z ##[debug]Exporting function 'Get-Detail'.
2019-02-07T07:29:24.0769758Z ##[debug]Exporting function 'Get-Build'.
2019-02-07T07:29:24.0769931Z ##[debug]Exporting function 'Get-BuildsByDefinitionId'.
2019-02-07T07:29:24.0770112Z ##[debug]Exporting function 'Get-ReleaseDefinitionByName'.
2019-02-07T07:29:24.0770283Z ##[debug]Exporting function 'Get-Release'.
2019-02-07T07:29:24.0770462Z ##[debug]Exporting function 'Get-BuildReleaseArtifacts'.
2019-02-07T07:29:24.0770656Z ##[debug]Exporting function 'ConvertFrom-JsonUsingDOTNET'.
2019-02-07T07:29:24.0770826Z ##[debug]Exporting function 'Expand-Tree'.
2019-02-07T07:29:24.0771015Z ##[debug]Exporting function 'Add-Space'.
2019-02-07T07:29:24.0771186Z ##[debug]Exporting function 'Invoke-GetCommand'.
2019-02-07T07:29:24.0771371Z ##[debug]Exporting function 'Invoke-PostCommand'.
2019-02-07T07:29:24.0771542Z ##[debug]Exporting function 'Render'.
2019-02-07T07:29:24.0771724Z ##[debug]Exporting function 'Get-Template'.
2019-02-07T07:29:24.0771896Z ##[debug]Exporting function 'Get-Mode'.
2019-02-07T07:29:24.0772082Z ##[debug]Exporting function 'Add-StackItem'.
2019-02-07T07:29:24.0772468Z ##[debug]Exporting function 'Invoke-Template'.
2019-02-07T07:29:24.0772672Z ##[debug]Exporting function 'Get-BuildDataSet'.
2019-02-07T07:29:24.0772848Z ##[debug]Exporting function 'Get-ReleaseByDefinitionId'.
2019-02-07T07:29:24.0773031Z ##[debug]Importing function 'Add-Space'.
2019-02-07T07:29:24.0773231Z ##[debug]Importing function 'Add-StackItem'.
2019-02-07T07:29:24.0773400Z ##[debug]Importing function 'ConvertFrom-JsonUsingDOTNET'.
2019-02-07T07:29:24.0773588Z ##[debug]Importing function 'Expand-Tree'.
2019-02-07T07:29:24.0773759Z ##[debug]Importing function 'Expand-WorkItemData'.
2019-02-07T07:29:24.0773944Z ##[debug]Importing function 'Get-Build'.
2019-02-07T07:29:24.0774115Z ##[debug]Importing function 'Get-BuildChangeSets'.
2019-02-07T07:29:24.0774303Z ##[debug]Importing function 'Get-BuildDataSet'.
2019-02-07T07:29:24.0774475Z ##[debug]Importing function 'Get-BuildReleaseArtifacts'.
2019-02-07T07:29:24.0774665Z ##[debug]Importing function 'Get-BuildsByDefinitionId'.
2019-02-07T07:29:24.0774840Z ##[debug]Importing function 'Get-CallerPreference'.
2019-02-07T07:29:24.0775028Z ##[debug]Importing function 'Get-CommitInfoFromGitRepo'.
2019-02-07T07:29:24.0775199Z ##[debug]Importing function 'Get-Detail'.
2019-02-07T07:29:24.0775395Z ##[debug]Importing function 'Get-Mode'.
2019-02-07T07:29:24.0775918Z ##[debug]Importing function 'Get-Release'.
2019-02-07T07:29:24.0776119Z ##[debug]Importing function 'Get-ReleaseByDefinitionId'.
2019-02-07T07:29:24.0776313Z ##[debug]Importing function 'Get-ReleaseDefinitionByName'.
2019-02-07T07:29:24.0776483Z ##[debug]Importing function 'Get-Template'.
2019-02-07T07:29:24.0776668Z ##[debug]Importing function 'Get-WorkItemDataFromBuild'.
2019-02-07T07:29:24.0776837Z ##[debug]Importing function 'Invoke-GetCommand'.
2019-02-07T07:29:24.0777023Z ##[debug]Importing function 'Invoke-PostCommand'.
2019-02-07T07:29:24.0777196Z ##[debug]Importing function 'Invoke-Template'.
2019-02-07T07:29:24.0777387Z ##[debug]Importing function 'Render'.
2019-02-07T07:29:24.0777561Z ##[debug]Importing function 'Use-SystemWebProxy'.
2019-02-07T07:29:24.0777823Z ##[debug]Using system web proxy.
2019-02-07T07:29:24.0920982Z ##[debug]collectionUrl = [https://dev.azure.com/juladevelopment/]
2019-02-07T07:29:24.0922775Z ##[debug]teamproject = [StoreInformation]
2019-02-07T07:29:24.0923913Z ##[debug]releaseid = [18]
2019-02-07T07:29:24.0925341Z ##[debug]releasedefid = [4]
2019-02-07T07:29:24.0926780Z ##[debug]stageName = [PRODDMZ]
2019-02-07T07:29:24.0928552Z ##[debug]overrideStageName = []
2019-02-07T07:29:24.0930282Z ##[debug]buildid = [1621]
2019-02-07T07:29:24.0932028Z ##[debug]builddefname = [StoreInformationAPI]
2019-02-07T07:29:24.0933742Z ##[debug]releasedefname = [StoreInformationAPI]
2019-02-07T07:29:24.0935959Z ##[debug]buildnumber = [20190207.1]
2019-02-07T07:29:24.0937350Z ##[debug]outputVariableName = []
2019-02-07T07:29:24.0938986Z ##[debug]generateForOnlyPrimary = [False]
2019-02-07T07:29:24.0940640Z ##[debug]generateForCurrentRelease = [false]
2019-02-07T07:29:24.0942337Z ##[debug]maxWi = [50]
2019-02-07T07:29:24.0944018Z ##[debug]maxChanges = [50]
2019-02-07T07:29:24.0945821Z ##[debug]showParents  =[False]
2019-02-07T07:29:24.0947449Z ##[debug]wiFilter = []
2019-02-07T07:29:24.0949102Z ##[debug]wiStateFilter = []
2019-02-07T07:29:24.0955639Z ##[debug]appendToFile = [False]
2019-02-07T07:29:24.0956211Z ##[debug]In Release mode
2019-02-07T07:29:24.1008608Z ##[debug]Processing all releases back to the last successful release in stage [PRODDMZ]
2019-02-07T07:29:24.1027292Z ##[debug]Getting details of release by definition [4] from server [https://dev.azure.com/juladevelopment//StoreInformation]
2019-02-07T07:29:24.2406807Z ##[debug]Loading module from path 'D:\vsts_build\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll'.
2019-02-07T07:29:24.2504163Z ##[debug]Importing cmdlet 'Invoke-ResultPublisher'.
2019-02-07T07:29:24.2504291Z ##[debug]Importing cmdlet 'Publish-TestResults'.
2019-02-07T07:29:24.2504470Z ##[debug]Importing cmdlet 'Add-BuildArtifactLink'.
2019-02-07T07:29:24.2504831Z ##[debug]Importing cmdlet 'Add-BuildAttachment'.
2019-02-07T07:29:24.2505025Z ##[debug]Importing cmdlet 'Convert-String'.
2019-02-07T07:29:24.2505244Z ##[debug]Importing cmdlet 'Copy-BuildArtifact'.
2019-02-07T07:29:24.2505474Z ##[debug]Importing cmdlet 'Get-JavaDevelopmentKitPath'.
2019-02-07T07:29:24.2505647Z ##[debug]Importing cmdlet 'Get-MSBuildLocation'.
2019-02-07T07:29:24.2505834Z ##[debug]Importing cmdlet 'Get-ServiceEndpoint'.
2019-02-07T07:29:24.2506040Z ##[debug]Importing cmdlet 'Get-TaskVariable'.
2019-02-07T07:29:24.2506228Z ##[debug]Importing cmdlet 'Get-TfsClientCredentials'.
2019-02-07T07:29:24.2506396Z ##[debug]Importing cmdlet 'Get-ToolPath'.
2019-02-07T07:29:24.2506659Z ##[debug]Importing cmdlet 'Get-VisualStudioPath'.
2019-02-07T07:29:24.2506845Z ##[debug]Importing cmdlet 'Get-VssConnection'.
2019-02-07T07:29:24.2507011Z ##[debug]Importing cmdlet 'Invoke-Ant'.
2019-02-07T07:29:24.2507231Z ##[debug]Importing cmdlet 'Invoke-BatchScript'.
2019-02-07T07:29:24.2507406Z ##[debug]Importing cmdlet 'Invoke-Maven'.
2019-02-07T07:29:24.2507591Z ##[debug]Importing cmdlet 'Invoke-MSBuild'.
2019-02-07T07:29:24.2507812Z ##[debug]Importing cmdlet 'Invoke-Tool'.
2019-02-07T07:29:24.2508213Z ##[debug]Importing cmdlet 'Invoke-VSTest'.
2019-02-07T07:29:24.2508392Z ##[debug]Importing cmdlet 'Publish-BuildArtifact'.
2019-02-07T07:29:24.2508650Z ##[debug]Importing cmdlet 'Register-XamarinLicense'.
2019-02-07T07:29:24.2508826Z ##[debug]Importing cmdlet 'Unregister-XamarinLicense'.
2019-02-07T07:29:24.2508993Z ##[debug]Importing cmdlet 'Get-X509Certificate'.
2019-02-07T07:29:24.2509176Z ##[debug]Importing cmdlet 'Invoke-DeployTestAgent'.
2019-02-07T07:29:24.2509379Z ##[debug]Importing cmdlet 'Invoke-RunDistributedTests'.
2019-02-07T07:29:24.2509565Z ##[debug]Importing cmdlet 'Invoke-BlockEnvironment'.
2019-02-07T07:29:24.2509731Z ##[debug]Importing cmdlet 'Copy-FilesToAzureBlob'.
2019-02-07T07:29:24.2509954Z ##[debug]Importing cmdlet 'Copy-FilesToTargetMachine'.
2019-02-07T07:29:24.2510140Z ##[debug]Importing cmdlet 'Copy-ToAzureMachines'.
2019-02-07T07:29:24.2510322Z ##[debug]Importing cmdlet 'Remove-Environment'.
2019-02-07T07:29:24.2510663Z ##[debug]Importing cmdlet 'Remove-EnvironmentResources'.
2019-02-07T07:29:24.2510866Z ##[debug]Importing cmdlet 'Complete-EnvironmentOperation'.
2019-02-07T07:29:24.2511047Z ##[debug]Importing cmdlet 'Complete-EnvironmentResourceOperation'.
2019-02-07T07:29:24.2511229Z ##[debug]Importing cmdlet 'Complete-ResourceOperation'.
2019-02-07T07:29:24.2511466Z ##[debug]Importing cmdlet 'Get-Environment'.
2019-02-07T07:29:24.2511651Z ##[debug]Importing cmdlet 'Get-EnvironmentProperty'.
2019-02-07T07:29:24.2511811Z ##[debug]Importing cmdlet 'Get-EnvironmentResources'.
2019-02-07T07:29:24.2511984Z ##[debug]Importing cmdlet 'Get-ExternalIpAddress'.
2019-02-07T07:29:24.2512187Z ##[debug]Importing cmdlet 'Get-ParsedSessionVariables'.
2019-02-07T07:29:24.2512349Z ##[debug]Importing cmdlet 'Get-ProviderData'.
2019-02-07T07:29:24.2512524Z ##[debug]Importing cmdlet 'Invoke-EnvironmentOperation'.
2019-02-07T07:29:24.2512717Z ##[debug]Importing cmdlet 'Invoke-ResourceOperation'.
2019-02-07T07:29:24.2512909Z ##[debug]Importing cmdlet 'Invoke-PsOnRemote'.
2019-02-07T07:29:24.2513079Z ##[debug]Importing cmdlet 'New-OperationLog'.
2019-02-07T07:29:24.2513290Z ##[debug]Importing cmdlet 'Copy-FilesToRemote'.
2019-02-07T07:29:24.2513451Z ##[debug]Importing cmdlet 'Register-Environment'.
2019-02-07T07:29:24.2513627Z ##[debug]Importing cmdlet 'Register-EnvironmentDefinition'.
2019-02-07T07:29:24.2513818Z ##[debug]Importing cmdlet 'Register-Provider'.
2019-02-07T07:29:24.2513996Z ##[debug]Importing cmdlet 'Register-ProviderData'.
2019-02-07T07:29:24.2514187Z ##[debug]Importing cmdlet 'Invoke-UnblockEnvironment'.
2019-02-07T07:29:24.2514366Z ##[debug]Importing cmdlet 'Add-TaskIssue'.
2019-02-07T07:29:24.2514556Z ##[debug]Importing cmdlet 'Complete-Task'.
2019-02-07T07:29:24.2514734Z ##[debug]Importing cmdlet 'Find-Files'.
2019-02-07T07:29:24.2514926Z ##[debug]Importing cmdlet 'Get-LocalizedString'.
2019-02-07T07:29:24.2515086Z ##[debug]Importing cmdlet 'Set-TaskProgress'.
2019-02-07T07:29:24.2515413Z ##[debug]Importing cmdlet 'Set-TaskVariable'.
2019-02-07T07:29:24.2515586Z ##[debug]Importing cmdlet 'Write-TaskDetail'.
2019-02-07T07:29:24.2515785Z ##[debug]Importing cmdlet 'Enable-CodeCoverage'.
2019-02-07T07:29:24.2515973Z ##[debug]Importing cmdlet 'Publish-CodeCoverage'.
2019-02-07T07:29:24.2622337Z ##[debug]Exporting cmdlet 'Add-BuildArtifactLink'.
2019-02-07T07:29:24.2622485Z ##[debug]Exporting cmdlet 'Add-BuildAttachment'.
2019-02-07T07:29:24.2622627Z ##[debug]Exporting cmdlet 'Convert-String'.
2019-02-07T07:29:24.2622906Z ##[debug]Exporting cmdlet 'Copy-BuildArtifact'.
2019-02-07T07:29:24.2623094Z ##[debug]Exporting cmdlet 'Get-JavaDevelopmentKitPath'.
2019-02-07T07:29:24.2623405Z ##[debug]Exporting cmdlet 'Get-MSBuildLocation'.
2019-02-07T07:29:24.2623597Z ##[debug]Exporting cmdlet 'Get-ServiceEndpoint'.
2019-02-07T07:29:24.2623923Z ##[debug]Exporting cmdlet 'Get-TaskVariable'.
2019-02-07T07:29:24.2624126Z ##[debug]Exporting cmdlet 'Get-TfsClientCredentials'.
2019-02-07T07:29:24.2624359Z ##[debug]Exporting cmdlet 'Get-ToolPath'.
2019-02-07T07:29:24.2624732Z ##[debug]Exporting cmdlet 'Get-VisualStudioPath'.
2019-02-07T07:29:24.2624926Z ##[debug]Exporting cmdlet 'Get-VssConnection'.
2019-02-07T07:29:24.2625120Z ##[debug]Exporting cmdlet 'Invoke-Ant'.
2019-02-07T07:29:24.2625313Z ##[debug]Exporting cmdlet 'Invoke-BatchScript'.
2019-02-07T07:29:24.2625524Z ##[debug]Exporting cmdlet 'Invoke-Maven'.
2019-02-07T07:29:24.2625783Z ##[debug]Exporting cmdlet 'Invoke-MSBuild'.
2019-02-07T07:29:24.2626040Z ##[debug]Exporting cmdlet 'Invoke-Tool'.
2019-02-07T07:29:24.2626327Z ##[debug]Exporting cmdlet 'Invoke-VSTest'.
2019-02-07T07:29:24.2626665Z ##[debug]Exporting cmdlet 'Publish-BuildArtifact'.
2019-02-07T07:29:24.2627004Z ##[debug]Exporting cmdlet 'Register-XamarinLicense'.
2019-02-07T07:29:24.2627367Z ##[debug]Exporting cmdlet 'Unregister-XamarinLicense'.
2019-02-07T07:29:24.2627672Z ##[debug]Exporting cmdlet 'Get-X509Certificate'.
2019-02-07T07:29:24.2653746Z ##[debug]Processed: ##vso[task.setprogress value=-1;] 
2019-02-07T07:29:24.4398347Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
2019-02-07T07:29:24.4405518Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found." ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
2019-02-07T07:29:24.4406436Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2019-02-07T07:29:24.4406665Z    at System.Net.WebClient.DownloadString(Uri address)
2019-02-07T07:29:24.4406842Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-07T07:29:24.4407129Z    --- End of inner exception stack trace ---
2019-02-07T07:29:24.4407309Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2019-02-07T07:29:24.4407478Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-07T07:29:24.4407622Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2019-02-07T07:29:24.4407763Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-02-07T07:29:24.4407922Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-07T07:29:24.4822913Z ##[debug]Discovered [0] releases for processing after checking a total of [0] releases
2019-02-07T07:29:24.4858787Z ##[debug]Found 0 build artifacts to check for builds that fall in range
2019-02-07T07:29:24.4915362Z ##[debug]In release mode so checking if wi/commits should be returned as unified lists
2019-02-07T07:29:24.4917342Z ##[debug]Return a nested set of builds each with their own WI/Commits, hence report can have duplicated workitems and commits
2019-02-07T07:29:24.4932703Z ##[debug]Using template mode [InLine]
2019-02-07T07:29:24.4943806Z ##[debug]Using in-line template
2019-02-07T07:29:24.5063561Z ##[debug]Processing template
2019-02-07T07:29:24.5086997Z ##[debug]There are [1] builds to process
2019-02-07T07:29:24.5516944Z ##[debug]   Starting block BUILD
2019-02-07T07:29:24.5596790Z ##[debug]      1 items
2019-02-07T07:29:24.5724154Z ##[debug]      Getting first build 
2019-02-07T07:29:24.5815139Z ##[debug]      Starting block WI
2019-02-07T07:29:24.5831934Z ##[debug]         1 items
2019-02-07T07:29:24.5834708Z ##[debug]         Getting first workitem 
2019-02-07T07:29:24.5861592Z ##[debug]      Ending block WI
2019-02-07T07:29:24.5870263Z ##[debug]      Starting block CS
2019-02-07T07:29:24.5885335Z ##[debug]         1 items
2019-02-07T07:29:24.5888179Z ##[debug]         Getting first changeset/commit 
2019-02-07T07:29:24.5892781Z ##[debug]      Ending block CS
2019-02-07T07:29:24.5895941Z ##[debug]   Ending block BUILD
2019-02-07T07:29:24.5900280Z ##[debug]Writing to output file [D:\vsts_build\_work\r3\a\releasenotes.md].
2019-02-07T07:29:24.5982066Z ##[debug]Skipping setting output variable name as parameter was not set.
2019-02-07T07:29:24.6216752Z ##[error]PowerShell script completed with 1 errors.
2019-02-07T07:29:24.6223272Z ##[section]Finishing: Generate release notes

**Comment by rfennell** [comment]
Sounds like a firewall issue, 404 can't find the URL could be explained this way. If it works on a hosted agent, but fails on an on-prem one

**Comment by Emil-H** [comment]
@rfennell By enabling "Generate for only this Release" under Advanced it works all the time. This is however not how we want to use it. Can you help me getting which call that fail with 404?

By comparing the logs from our local Agent and the Hosted Agent, I noted that they get different collectionUrl. Hosted agent get the "old" url which we still use: https://juladevelopment.visualstudio.com and the local Agent gets: https://dev.azure.com/juladevelopment. Why this is happening I don't know.

So I'm guessing that this is the error. Doing the following call works:
https://juladevelopment.vsrm.visualstudio.com/JulaPro/_apis/release/releases?api-version=5.0&definitionId=4
and this doesn't:
https://dev.azure.com/juladevelopment/JulaPro/_apis/release/releases?api-version=5.0&definitionId=4 (returns 404).

This however works fine:
https://vsrm.dev.azure.com/juladevelopment/JulaPro/_apis/release/releases?api-version=5.0&definitionId=4

**Comment by Emil-H** [comment]
I reinstalled the agent now and instead of entering https://dev.azure.com/{your-organization} as it says in the docs (https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops) I entered the old url (visualstudio.com). First test shows that it works just fine now. Will look more next week.

**Comment by rfennell** [comment]
interesting, I will check the code to make sure URls are built right, it was based on some preview APIs originally

**Comment by MattRames** [comment]
@Emil-H 
I ran into this issue as well. Reinstalling the agents with the older visualstudio.com url fixed the issue.

**Comment by rfennell** [comment]
Does your pipeline use the new V3 version of the agent, it should fixed in that version but not in V2

**Comment by MattRames** [comment]
We are currently using V2, I guess I didn't notice V3 was out.

**Comment by rfennell** [comment]
Has V3 helped?

**Comment by MattRames** [comment]
@rfennell I've updated back to the new url and I've tested the task with V2 and V3, V3 does indeed fix the issue.

Thanks

**Comment by rfennell** [comment]
Great news

**Comment by mesheets** [comment]
On TFS 2017 Version 15.117.27414.0, I was encountering this issue and seemed to have traced it down to this commit to [Update to use api-version4](https://github.com/rfennell/AzurePipelines/commit/19f489ba140456c66174b385ca85120db2fed544#diff-765596521f90e301d3fd98e2a7f78de7) that broke compatibility with TFS 2017.  If the api-version is 2.0 (as it was prior to that commit) or even 3.0, it works, but with api-version set to 4.0, the action fails and the error message cited in this issue title is returned.

**Comment by rfennell** [comment]
I am a bit confused @mesheets this issue has been about generating release note, but you mention the build updating task. Could you log a separate issue for this problem.

I have all the old VSIX package in the build systems, so can upload the one previous to the one you want, I think it will 1.4.1 judging by the date, so around April of last year

**Comment by mesheets** [comment]
Sure, I can create a separate issue; the error message encountered was exactly the same, so I ended up putting it here first.

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
