### ISSUE TITLE
[GenerateReleaseNotes] Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32"

### ISSUE THREAD

**Issue by mrdwright** [rfennell/AzurePipelines#432]
### Azure DevOps Extension you are using
GenerateReleaseNotes, from Marketplace

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
(2.23.1)

### Expected behaviour and actual behaviour

2019-02-08T00:18:24.3757763Z ##[error]System.Management.Automation.RuntimeException: Could not compare "9811" to "9811 9811". Error: "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32"."
2019-02-08T00:18:24.3773535Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-08T00:18:24.3775868Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2019-02-08T00:18:24.3778417Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-02-08T00:18:24.3781012Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

### Steps to reproduce the problem
check the following
Generate for only this Release
Show parent workitems

Template used
# Release notes for build $(Build.DefinitionName)   
**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  
### Associated work items  
@@WILOOP@@  
* **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
@@WILOOP@@  
### Associated change sets/commits  
@@CSLOOP@@  
* **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
@@CSLOOP@@

**Comment by rfennell** [comment]
That's strange, look like an ID has doubled up. Can you re-run the failing release with the system.debug-true variable set, this will provide better logging and so hopefully should explain where the IDs came from

**Comment by mrdwright** [comment]
Does this help ?

```
2019-02-10T04:17:01.1176825Z ##[error]System.Management.Automation.RuntimeException: Could not compare "9833" to "9833 9833". Error: "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32"."
2019-02-10T04:17:01.1234504Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-10T04:17:01.1235593Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2019-02-10T04:17:01.1237578Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-02-10T04:17:01.1244064Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-10T04:17:01.1248695Z ##[error]System.Management.Automation.RuntimeException: Could not compare "9832" to "9833 9833". Error: "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32"."
2019-02-10T04:17:01.1252609Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-10T04:17:01.1253899Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2019-02-10T04:17:01.1255271Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
...
...
...
2019-02-10T04:17:01.8288939Z ##[error]System.Management.Automation.RuntimeException: Could not compare "9832" to "9833 9833". Error: "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32"."
2019-02-10T04:17:01.8292913Z    at CallSite.Target(Closure , CallSite , Object , Object )
2019-02-10T04:17:01.8293826Z    at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
...
...
...
2019-02-10T04:17:02.5280100Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
2019-02-10T04:17:02.5679913Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-02-10T04:17:02.5685110Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-02-10T04:17:02.5690134Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-10T04:17:02.5693185Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-10T04:17:02.5695814Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-10T04:17:02.5698504Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-10T04:17:02.8040672Z 
2019-02-10T04:17:02.8041094Z 
2019-02-10T04:17:02.8733936Z ##[error]PowerShell script completed with 123 errors.
2019-02-10T04:17:02.8748064Z ##[section]Finishing: Generate release notes
```

**Comment by rfennell** [comment]
Sorry I made a typo the variable should be **system.debug = true**

You should see loads of [debug] lines in the log. It allows me to see which line is causing the issue. 

Strange thing is that this has not been reported before as this is a fairly old tasks and has not been edited for a while. Wonder if there is an API change?

Other thing to try is my newer [Cross Platform release notes](https://marketplace.visualstudio.com/manage/publishers/richardfennellbm/extensions/bm-vsts-xplatgeneratereleasenotes/hub?_a=acquisition) that use the MS API as opposed to my own old logic that predates the current API. Does that meet your needs

**Comment by mrdwright** [comment]
> Sorry I made a typo the variable should be **system.debug = true**

I caught that, but maybe I had a typo :(
 
> Other thing to try is my newer [Cross Platform release notes](https://marketplace.visualstudio.com/manage/publishers/richardfennellbm/extensions/bm-vsts-xplatgeneratereleasenotes/hub?_a=acquisition) that use the MS API as opposed to my own old logic that predates the current API. Does that meet your needs

I will give it a shot

**Comment by rfennell** [comment]
Did the Xplat version do the job for you?

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
