### ISSUE TITLE
Upload wiki file in a folder

### ISSUE THREAD

**Issue by rajbos** [rfennell/AzurePipelines#442]
### Azure DevOps Extension you are using
Git based WIKI Updater from Black Marble`

### Where are you running it?
- Azure DevOps Service

### Version of Extension/Task
1.1.2

### Expected behaviour and actual behaviour
Is it possible to use this extension and upload the md file with the release notes into a folder structure instead of the root ? I would like to push all the release notes into a `release notes` folder.

**Comment by rfennell** [comment]
Don't see any reason why not, and if it doesn't it should. Just not tested it.

Have you tried just adding a path into 'Name of the file/page'?

**Comment by rajbos** [comment]
If I do that, I get an error that it cannot find the file in that location, so it seems to be searching for it with that path:

The setting here was `ReleaseNotes\release notes.md`

``` 
##[error]System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\agents\3\_work\4\s\ReleaseNotes\release notes.md'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.PowerShell.Commands.FileSystemContentReaderWriter.CreateStreams(String filePath, String streamName, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Encoding fileEncoding)
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetContentWriter(String path)
##[error]PowerShell script completed with 1 errors.
```

If I give it `\ReleaseNotes\release notes.md` then I get an HTML text error indicating ` We could not find the requested page`.

Even if I create that file first, it returns the same error.

**Comment by rfennell** [comment]
path 'C:\agents\3\_work\4\s\ReleaseNotes\release notes.md is where it is looking on the client, which seems wrong. 

I will have to look at the code and get back to you, I assume an update will be needed

**Comment by rajbos** [comment]
Correct, I didn't change the path of the wiki repo that is checked out, so that would just be the source folder or `C:\agents\3_work\4\s\`. If I just place to release notes file there and only use the name, it will find it. 
So that is not how you can change the destination apparently.

**Comment by rfennell** [comment]
Looked at the code, it needs to create any missing folder, I have marked it as an enhancement and will have a look at ASAP

**Comment by wpschaub** [comment]
Picked up the same issue. As a workaround we create the wiki folders and create a placeholder file within, as Git does not like empty folders.

**Comment by rfennell** [comment]
There is a new version in test that fixes this issue. Should be out next day or so

**Comment by rfennell** [comment]
I have just released a new 1.2.8 that should handle the folder creation. Seems to work OK, but if using the Azure DevOps wiki the UI seems to block seeing pages in a folder. It is fine for Github or generic repos.

Let me know how it goes

**Comment by rajbos** [comment]
Just tested it and I am getting the `ENOENT` error. Running on a Windows based agent. Any idea how to fix that?

Log
```
2019-03-09T10:55:57.4756324Z Cleaned C:\agents\3\_work\r8\a\repo
2019-03-09T10:55:57.4966692Z ##[error]Error: Error: spawn git ENOENT
2019-03-09T10:55:57.4974901Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT
2019-03-09T10:55:57.4975118Z     at exports._errnoException (util.js:1018:11)
2019-03-09T10:55:57.4975177Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-03-09T10:55:57.4975227Z     at onErrorNT (internal/child_process.js:367:16)
2019-03-09T10:55:57.4975291Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-03-09T10:55:57.4975344Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-03-09T10:55:57.4975390Z     at Module.runMain (module.js:606:11)
2019-03-09T10:55:57.4975462Z     at run (bootstrap_node.js:390:7)
2019-03-09T10:55:57.4975524Z     at startup (bootstrap_node.js:150:9)
2019-03-09T10:55:57.4975573Z     at bootstrap_node.js:505:3
2019-03-09T10:55:57.4975738Z ##[debug]task result: Failed
2019-03-09T10:55:57.4975984Z ##[error]Error: Error: spawn git ENOENT
2019-03-09T10:55:57.4976156Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT
2019-03-09T10:55:57.4976258Z     at exports._errnoException (util.js:1018:11)
2019-03-09T10:55:57.4976309Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-03-09T10:55:57.4976358Z     at onErrorNT (internal/child_process.js:367:16)
2019-03-09T10:55:57.4976410Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-03-09T10:55:57.4976476Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-03-09T10:55:57.4976522Z     at Module.runMain (module.js:606:11)
2019-03-09T10:55:57.4976578Z     at run (bootstrap_node.js:390:7)
2019-03-09T10:55:57.4976640Z     at startup (bootstrap_node.js:150:9)
2019-03-09T10:55:57.4976687Z     at bootstrap_node.js:505:3
2019-03-09T10:55:57.4976933Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: spawn git ENOENT
2019-03-09T10:55:57.4977001Z     at exports._errnoException (util.js:1018:11)
2019-03-09T10:55:57.4977051Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-03-09T10:55:57.4977114Z     at onErrorNT (internal/child_process.js:367:16)
2019-03-09T10:55:57.4977179Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-03-09T10:55:57.4977229Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-03-09T10:55:57.4977276Z     at Module.runMain (module.js:606:11)
2019-03-09T10:55:57.4977324Z     at run (bootstrap_node.js:390:7)
2019-03-09T10:55:57.4977384Z     at startup (bootstrap_node.js:150:9)
2019-03-09T10:55:57.4977430Z     at bootstrap_node.js:505:3
2019-03-09T10:55:57.4989873Z ##[section]Finishing: Git based WIKI Updater
```

**Comment by rfennell** [comment]
@rajbos stange, I have tested with a WIndows agent (both hosted and private) against Azure DevOps WIKI and GitHub. 

For Github I see

```
2019-03-08T19:03:22.1241789Z Cleaned D:\a\r1\a\githubrepo
2019-03-08T19:03:22.6366547Z Cloned github.com/rfennell/demorepo.wiki to D:\a\r1\a\githubrepo
2019-03-08T19:03:22.7051586Z Set GIT values in D:\a\r1\a\githubrepo
2019-03-08T19:03:22.7059760Z Creating the directory D:\a\r1\a\githubrepo\TestFolder
2019-03-08T19:03:22.7071301Z Working file name is PageFromWikiUpdater.md
2019-03-08T19:03:22.7073764Z Created the PageFromWikiUpdater.md in D:\a\r1\a\githubrepo\TestFolder
2019-03-08T19:03:22.7300192Z Added TestFolder/PageFromWikiUpdater.md to repo D:\a\r1\a\githubrepo
2019-03-08T19:03:22.8232508Z Committed to D:\a\r1\a\githubrepo with message "Update from Release - Release 1.2.8 Attempt 1
2019-03-08T19:03:25.5145790Z Pushed to github.com/rfennell/demorepo.wiki
```
So it looks to me like the Clone failed, so I doubt it has anything to do with the new code.

I assume the previous version of the tasks could do a clone?

A few questions, so I can try to repo

- Did the previous version clone?
- Is the agent hosted (if windows type) or private?
- Where is the Git target repo hosted?

**Comment by rajbos** [comment]
Correct, the previous version did clone. 
Private hosted Windows agent
Git target in Azure DevOps

**Comment by wpschaub** [comment]
@rfennell ito "I have just released a new 1.2.8 that should handle the folder creation. Seems to work OK, but if **using the Azure DevOps wiki the UI seems to block seeing pages in a folder**. It is fine for Github or generic repos."

I did a quick test. If you add a markdown file with the same name as the folder to the wiki, files within the folder light up in Azure DevOps.

**Comment by rfennell** [comment]
@wpschaub that interesting behavior, but given that it work as expected?

**Comment by wpschaub** [comment]
Yes, works as designed. It's s feature request for AzDO wiki.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rfennell** [comment]
@rajbos could you test on a hosted agent, or a different private agent to rule out some strange local issue.

I can't get a repo, and it seems neither can other users

**Comment by rajbos** [comment]
Running on a hosted agent triggers a different error:
```
2019-03-13T20:49:53.9751604Z ##[error]Error: Cloning into 'D:\a\r1\a\repo'...
2019-03-13T20:49:53.9760090Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Cloning into 'D:\a\r1\a\repo'...
2019-03-13T20:49:53.9760818Z fatal: unable to access 'https://buildagent:***@https://***org_name@dev.azure.com/******org_name*****/***projectname****/_git/xxx%20xxx%20xxx.wiki/': Couldn't resolve host 'https'
2019-03-13T20:49:53.9761006Z 
```

This seems to indicate I have the wrong url for the repo, so I am testing with the correct url (without adding my own `https` and `org_name@dev.azure.com`)

**Comment by rajbos** [comment]
Update: On the hosted agent this works like a charm! Yet, on our own agents it still reports the same `ENOENT` error. I'll see if i can retest with a new agent installed on my own laptop, to rule out the agents we currently have.

**Comment by rfennell** [comment]
@rajbos given work I am doing for a client at present my experience says 'always blame the firewall' !

**Comment by rajbos** [comment]
That’s my first guess too 😜. That’s why I’ll test it from an agent on my own laptop from home to see what it does. 
Strange thing is that it didn’t have this problem with the previous version: the clone action there worked just fine. 
I’ll let you know when I tested it.

**Comment by rajbos** [comment]
Great! It ‘works on my machine’ from my home network 👍. Next step is to verify that same agent on my customers network. 

Any idea where to look if that doesn’t work? You’re just performing a regular git clone, right? The regular Azure DevOps tasks can get the other repos just fine.

**Comment by rfennell** [comment]
Have seen an issue where it was related to proxies, tls and node versions. So no obvious, start at the firewall logs

**Comment by rajbos** [comment]
Update from testing:
1. Running on my laptop's agent in the same network as the agent with the error still works.
1. Turning off the windows firewall on the agent with the error , doesn't fix it.

For now, I've chosen to run this step in a different Agent Job and use the hosted agent for it.
Thanks for the help so far 👍

**Comment by rfennell** [comment]
Destroy the old failing agent with fire ?

Just a suggestion

**Comment by rajbos** [comment]
Finally found it! 

Additional steps with no effect:
* Reinstall the agent
* Install NPM on the agent machine

Then, while testing NPM commands and checking the code in the extension, it dawned on me: Git has to be installed on the server to run this task! Installed Git and indeed: the task started working 🎉 !

Suggestion: can you add the demand `Git` to the the list, just like `npm` currently is? That would prevent this error for other users.

**Comment by rfennell** [comment]
Good idea
