### ISSUE TITLE
Pester Task: Running in an isolated env. produces errors

### ISSUE THREAD

**Issue by PsychoticCob** [rfennell/AzurePipelines#464]
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*
Pester Tasks 8.13.3
### Where are you running it?
*You can run the extensions in the cloud or on-premise*

Azure DevOps Server (on-premise TFS, 2017)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
Pester Tasks 8.13.3
### Expected behaviour and actual behaviour

That when pester tasks tries to download and there is no internet connection it falls back to the shipping version that was installed.

What I now see is that it does now skip the download but errors are still generated (Note the tests do still run):

2019-03-22T13:08:18.0992897Z ##[warning]MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
2019-03-22T13:08:25.4900633Z ##[warning]Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
2019-03-22T13:09:00.2090288Z ##[warning]Unable to download the list of available providers. Check your internet connection.
2019-03-22T13:09:29.4905586Z ##[warning]Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
2019-03-22T13:10:11.5378030Z ##[warning]Unable to download the list of available providers. Check your internet connection.

2019-03-22T13:10:11.5378030Z ##vos[task.logissue type=warning]Falling back to version of Pester shipped with extension. To use a newer version please update the version of PowerShellGet available on this machine.
2019-03-22T13:10:11.5378030Z 
2019-03-22T13:10:11.5378030Z 

**2019-03-22T13:10:15.8815691Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "The method or operation is not implemented." ---> System.NotImplementedException: The method or operation is not implemented.**

2019-03-22T13:10:15.8815691Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.InternalPowerShellHostUI.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt, Boolean hasSecurityImpact)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.MshCommandRuntime.DoShouldContinue(String query, String caption, Boolean hasSecurityImpact, Boolean supportsToAllOptions, Boolean& yesToAll, Boolean& noToAll)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.MshCommandRuntime.ShouldContinue(String query, String caption)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.Cmdlet.ShouldContinue(String query, String caption)
2019-03-22T13:10:15.8815691Z    at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
2019-03-22T13:10:15.8815691Z    --- End of inner exception stack trace ---
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2019-03-22T13:10:15.8815691Z    at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
2019-03-22T13:10:15.8815691Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
2019-03-22T13:10:15.8815691Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**2019-03-22T13:10:15.9284607Z ##[error]System.InvalidOperationException: NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of NuGet provider is installed.
2019-03-22T13:10:15.9284607Z    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
**2019-03-22T13**:10:15.9597014Z ##[error]System.IO.FileNotFoundException: The specified module 'Pester' was not loaded because no valid module file was found in any module directory.

### Steps to reproduce the problem

Launch a new build with Pester Tasks in a isolated env.

**Comment by ChrisLGardner** [comment]
Should be resolved in the last release we did, will also be resolved in the first release of the new extension.
