### ISSUE TITLE
Generate Release Notes Build Task fails with a TLS 1.2 exposed TFS server

### ISSUE THREAD

**Issue by Vinzz** [rfennell/AzurePipelines#484]
### Azure DevOps Extension you are using
Generate Release Notes Build Task v3.0.8 for the package, Version : 2.23.1 for the build task

### Where are you running it?

- on-premise TFS 2018.3.2

### Version of Extension/Task
*Generate Release Notes Version : 2.23.1 

### Expected behaviour and actual behaviour

Error message:

```
2019-05-02T09:50:58.6985428Z Task         : Generate Release Notes
2019-05-02T09:50:58.6985755Z Description  : Generates a release notes file in a format of your choice
2019-05-02T09:50:58.6986046Z Version      : 2.23.1
2019-05-02T09:50:58.6986318Z Author       : Black Marble
2019-05-02T09:50:58.6986669Z Help         : Version: 2.23.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2019-05-02T09:50:58.6987082Z ==============================================================================
2019-05-02T09:50:58.7018645Z Preparing task execution handler.
2019-05-02T09:50:59.1494010Z Executing the powershell script: C:\Agt1\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\2.23.1\GenerateReleaseNotes.ps1
2019-05-02T09:50:59.1496968Z **Build Number**  : $($build.buildnumber)    
2019-05-02T09:50:59.1497326Z **Build created** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
2019-05-02T09:50:59.1497570Z **Source Branch** : $($build.sourceBranch) 
2019-05-02T09:50:59.1497799Z ###Associated work items  
2019-05-02T09:50:59.1497988Z @@WILOOP@@  
2019-05-02T09:50:59.1498275Z * **$($widetail.fields.'System.WorkItemType') $($widetail.id)** [Assigned by: $($widetail.fields.'System.AssignedTo')]     $($widetail.fields.'System.Title') 
2019-05-02T09:50:59.1498535Z @@WILOOP@@  
2019-05-02T09:50:59.1498744Z ###Associated change sets/commits  
2019-05-02T09:50:59.1498937Z @@CSLOOP@@  
2019-05-02T09:50:59.1499173Z * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
2019-05-02T09:50:59.1499386Z @@CSLOOP@@)
2019-05-02T09:50:59.7004251Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send." ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
2019-05-02T09:50:59.7005830Z    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
2019-05-02T09:50:59.7006165Z    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
2019-05-02T09:50:59.7006476Z    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
2019-05-02T09:50:59.7006775Z    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
2019-05-02T09:50:59.7007059Z    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
2019-05-02T09:50:59.7007350Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2019-05-02T09:50:59.7007709Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2019-05-02T09:50:59.7008004Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-05-02T09:50:59.7008284Z    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
2019-05-02T09:50:59.7008520Z    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2019-05-02T09:50:59.7008768Z    at System.Net.ConnectStream.WriteHeaders(Boolean async)
2019-05-02T09:50:59.7008989Z    --- End of inner exception stack trace ---
2019-05-02T09:50:59.7009229Z    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
2019-05-02T09:50:59.7009465Z    at System.Net.WebClient.DownloadString(Uri address)
```
**Note:**
I disabled TLS 1.0 and 1.1 on TFS last monday, and since, this task fails, it seems a  TLS .12 instruction is missing:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

### Steps to reproduce the problem
1. Expose a TFS Server on https with TLS 1.2 only
1. Run a build with the Generate Release Note v 2.23.1 task

**Comment by rfennell** [comment]
Obviously you are not on the lastest build in the extension VSIX, but the only difference is the 3.x series is that it uses the PowerShell3 engine and Azure DevOps libraries, as opposed to basic PowerShell web calls. I guess this is worth a try, but I am not sure it will help.

If you are using the task in a release, it is also worth trying is the [node based CrossPlatform version](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes), though note there is a [slight difference in templating](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates.), this has the aadvantage of using the same API calls is the TFS UI, as opposed to my own bespoke logic.

After that I am going to have to experiment as you suggested, but not sure when I will get a chance

**Comment by Vinzz** [comment]
hi @rfennell, the 3.x version of the tasks fails with even less log message.

I'm aware of the XPlat version, but some of my users like to generate their release notes in Build process. Wouldn't it be nice to have the XPlat version with the build visibility?

**Comment by Vinzz** [comment]
Update: forcing Strong Crypto for .NET solved the issue:
More info: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

**Comment by rfennell** [comment]
Happy you found a solution
