### ISSUE TITLE
 [System.Char] does not contain a method named 'Trim'

### ISSUE THREAD

**Issue by saigkill** [rfennell/AzurePipelines#495]
### Azure DevOps Extension you are using
*GenerateReleaseNotes@3

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
last public

### Expected behaviour and actual behaviour
```
##[debug]At line:1 char:1
##[debug]+ . 'D:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0 ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (:) [GenerateReleaseNotes.ps1], RuntimeException
##[debug]    + FullyQualifiedErrorId : MethodNotFound,GenerateReleaseNotes.ps1
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-Mode, D:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.0.8\GenerateReleaseNotes.psm1: line 511
##[debug]at Invoke-Template, D:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.0.8\GenerateReleaseNotes.psm1: line 574
##[debug]at <ScriptBlock>, D:\a\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.0.8\GenerateReleaseNotes.ps1: line 282
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Method invocation failed because [System.Char] does not contain a method named 'Trim'.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Method invocation failed because [System.Char] does not contain a method named 'Trim'.
##[debug]Processed: ##vso[task.logissue type=error]Method invocation failed because [System.Char] does not contain a method named 'Trim'.
##[debug]Processed: ##vso[task.complete result=Failed]
```

### Steps to reproduce the problem
I have added this to my azure-pipelines.yml:

```
- task: GenerateReleaseNotes@3
    inputs:
      outputfile: 'changelog.md'
      templateLocation: 'InLine'
      inlinetemplate: '# Release notes for build $(Build.DefinitionName)   
        **Build Number**  : $($build.buildnumber)    
        **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
        **Source Branch** : $($build.sourceBranch)  
        ### Associated work items  
        @@WILOOP@@  
        * **$($widetail.fields.''System.WorkItemType'') $($widetail.id)** [Assigned by: $($widetail.fields.''System.AssignedTo'')]     $($widetail.fields.''System.Title'') 
        @@WILOOP@@  
        ### Associated change sets/commits  
        @@CSLOOP@@  
        * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
        @@CSLOOP@@'
      generateForOnlyPrimary: False```

**Comment by rfennell** [comment]
What is the template you are using? It looks like stray characters in there as it seems to be struggling on a @@WILOOP@@ line

**Comment by saigkill** [comment]
Hi. It was a InLine Template
```
# Release notes for build $(Build.DefinitionName)   
        **Build Number**  : $($build.buildnumber)    
        **Build started** : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     
        **Source Branch** : $($build.sourceBranch)  
        ### Associated work items  
        @@WILOOP@@  
        * **$($widetail.fields.''System.WorkItemType'') $($widetail.id)** [Assigned by: $($widetail.fields.''System.AssignedTo'')]     $($widetail.fields.''System.Title'') 
        @@WILOOP@@  
        ### Associated change sets/commits  
        @@CSLOOP@@  
        * **ID $($csdetail.changesetid)$($csdetail.commitid)** $($csdetail.comment)    
        @@CSLOOP@@'
      generateForOnlyPrimary: False```

It was one from the wiki page.

**Comment by rfennell** [comment]
Try setting a build variable system.debug=true this will cause a lot more logging. It does look like it is seeing a line around one of the @@WILOOP@@ markers as a char (or empty) as a opposed to a string

**Comment by saigkill** [comment]
The current log with enabled debug is placed there: [https://pastebin.com/Dh8AB0TW](https://pastebin.com/Dh8AB0TW)

**Comment by rfennell** [comment]
Can't see anything obvious, the usual tactic I use here is remove lines from the template until it complete, then add them back. 

Sorry I don't have anything better to offer

**Comment by saigkill** [comment]
The project itself is public. Maybe you have a minute to have a look? [https://dev.azure.com/saigkill/hoe-manns](https://dev.azure.com/saigkill/hoe-manns)

**Comment by rfennell** [comment]
The project is public, but that does not mean I can edit it.

I can, see nothing obvious, but still suggest just removing all the @@CSLOOP@@ and the @@WILOOP@@ blocks and see if there is still an error, then add them back in bit by bit.

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
