### ISSUE TITLE
Bit Based WIKI Updater - Error: spawn git ENOENT

### ISSUE THREAD

**Issue by Frankwin** [rfennell/AzurePipelines#497]
### Azure DevOps Extension you are using
Git Based WIKI Updater

### Where are you running it?
- Azure DevOps Service (VSTS) with local agent

### Version of Extension/Task
current public version

### Expected behaviour and actual behaviour
Expected to work
Actual : Error: spawn git ENOENT

### Steps to reproduce the problem
I added the Wiki Updater task into my Release pipeline and filled out all required parameters. I tried various combinations as well. 

I did install GIT for Windows on the Agent Server, just in case that was needed, but that didn't seem to make a difference.

The error I am getting is:
2019-05-29T22:11:50.4201198Z Cleaned C:\azagent\A2\_work\r1\a\repo
2019-05-29T22:11:50.4321558Z ##[error]Error: Error: spawn git ENOENT
2019-05-29T22:11:50.4331283Z     at exports._errnoException (util.js:1018:11)
2019-05-29T22:11:50.4337026Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-05-29T22:11:50.4340542Z     at onErrorNT (internal/child_process.js:367:16)
2019-05-29T22:11:50.4361211Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-05-29T22:11:50.4362733Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-05-29T22:11:50.4363306Z     at Module.runMain (module.js:606:11)
2019-05-29T22:11:50.4363546Z     at run (bootstrap_node.js:390:7)
2019-05-29T22:11:50.4363708Z     at startup (bootstrap_node.js:150:9)
2019-05-29T22:11:50.4363841Z     at bootstrap_node.js:505:3
2019-05-29T22:11:50.4364589Z ##[error]Error: Error: spawn git ENOENT
2019-05-29T22:11:50.4365214Z     at exports._errnoException (util.js:1018:11)
2019-05-29T22:11:50.4365363Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-05-29T22:11:50.4365521Z     at onErrorNT (internal/child_process.js:367:16)
2019-05-29T22:11:50.4365671Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-05-29T22:11:50.4365808Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-05-29T22:11:50.4365958Z     at Module.runMain (module.js:606:11)
2019-05-29T22:11:50.4366090Z     at run (bootstrap_node.js:390:7)
2019-05-29T22:11:50.4366219Z     at startup (bootstrap_node.js:150:9)
2019-05-29T22:11:50.4366736Z     at bootstrap_node.js:505:3
2019-05-29T22:11:50.4367309Z     at exports._errnoException (util.js:1018:11)
2019-05-29T22:11:50.4367459Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-05-29T22:11:50.4367613Z     at onErrorNT (internal/child_process.js:367:16)
2019-05-29T22:11:50.4367745Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-05-29T22:11:50.4367899Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2019-05-29T22:11:50.4368049Z     at Module.runMain (module.js:606:11)
2019-05-29T22:11:50.4370085Z     at run (bootstrap_node.js:390:7)
2019-05-29T22:11:50.4370251Z     at startup (bootstrap_node.js:150:9)
2019-05-29T22:11:50.4370384Z     at bootstrap_node.js:505:3

**Comment by rfennell** [comment]
All the Git operations are done with [simple-git](https://github.com/steveukx/git-js) and it does all the base git work, I only pass commands.

A search on that projects repo's issues shows the common case for the [Error: spawn git ENOENT](https://github.com/steveukx/git-js/issues?utf8=%E2%9C%93&q=spawn+git+ENOENT) is valid paths

- Any of to those issue help
- What settings are you using for the task?
- Is there a chance a path is wrong, or read only 
- Can you run the build or release with the variable system.debug=true to get more detailed logging

**Comment by Frankwin** [comment]
Ok after debugging this some more what seems to happen is that it removes "The local folder to clone into" in the cleaning step and then when it tries to actually clone into it, the folder no longer exists. 
`2019-05-30T15:43:38.7069123Z Cleaned C:\repo
2019-05-30T15:43:38.7187766Z ##[error]Error: Error: spawn git ENOENT
2019-05-30T15:43:38.7201456Z     at exports._errnoException (util.js:1018:11)
2019-05-30T15:43:38.7205758Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2019-05-30T15:43:38.7226419Z     at onErrorNT (internal/child_process.js:367:16)
2019-05-30T15:43:38.7227873Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-05-30T15:43:38.7228433Z     at process._tickCallback (internal/process/next_tick.js:104:9)`

The C:\repo folder that I had no longer exists now on disk, even though I had created it prior to running this. So not sure why it is able to delete it, but then not able to re-create it to then actually clone the repo into?. My agent service is running under the NT-AUTHORITY\SYSTEM account

**Comment by rfennell** [comment]
I make sure my folder to clone is under the agents working folder.

![1](https://user-images.githubusercontent.com/324718/58645569-89b12180-82fb-11e9-8b34-0c0487e2cfdf.png)

Does that help?

I wonder if the fact yo are working of the root of the drive is the issue as UAC could be getting involved

**Comment by Frankwin** [comment]
That's what I originally had as that's the default and that did the same thing. It would remove the repo folder if it was there and then not recreate it. Just to ensure that none of my other tasks in my release process was deleting that folder I put it on C:\repo as a test as definitely nothing else touches that and that's when I saw it was doing the same thing there.

**Comment by rfennell** [comment]
I have had no problem using those settings, have you tried using a different agent, preferably as hosted one.

The simple Git repo seems to suggest this can be seen in some cases on Windows, but there is no definitive answer. 

The logging I would expect on a VS2017 hosted agent is...

```
2019-05-29T16:55:00.9820564Z Variable: Repo [github.com/rfennell/AzurePipelines.wiki.git]
2019-05-29T16:55:00.9820718Z Variable: Filename [Version-Assemblies-and-Packages-Tasks-YAML.md]
2019-05-29T16:55:00.9821006Z Variable: Contents [null]
2019-05-29T16:55:00.9821216Z Variable: Commit Message [The readme for Version-Assemblies-and-Packages-Tasks YAML]
2019-05-29T16:55:00.9821427Z Variable: Git Username [rfennell]
2019-05-29T16:55:00.9821623Z Variable: Git Email [richard.fennell@live.co.uk]
2019-05-29T16:55:00.9821790Z Variable: Use Agent Token [false]
2019-05-29T16:55:00.9822003Z Variable: Username [rfennell]
2019-05-29T16:55:00.9822390Z Variable: Password [***]
2019-05-29T16:55:00.9822792Z Variable: Localpath [D:\a\r1\a\repo]
2019-05-29T16:55:00.9823094Z Variable: Data Is File [true]
2019-05-29T16:55:00.9823262Z Variable: SoureFile [D:\a\r1\a/VersioningExtension/vsix/out/Version-Assemblies-and-Packages-Tasks-YAML.md]
2019-05-29T16:55:01.0087854Z URL used ```
https://rfennell:***@github.com/rfennell/AzurePipelines.wiki.git
2019-05-29T16:55:01.0089883Z Cleaned D:\a\r1\a\repo
2019-05-29T16:55:05.4768086Z Cloned github.com/rfennell/AzurePipelines.wiki.git to D:\a\r1\a\repo
2019-05-29T16:55:05.5559263Z Set GIT values in D:\a\r1\a\repo
2019-05-29T16:55:05.5566197Z No sub-directory passed change to D:\a\r1\a\repo
2019-05-29T16:55:06.3118331Z Pull in case of post clone updates from other users
2019-05-29T16:55:06.3118481Z Working file name is Version-Assemblies-and-Packages-Tasks-YAML.md
2019-05-29T16:55:06.3121837Z Created the Version-Assemblies-and-Packages-Tasks-YAML.md in D:\a\r1\a\repo
2019-05-29T16:55:06.3453891Z Added Version-Assemblies-and-Packages-Tasks-YAML.md to repo D:\a\r1\a\repo
2019-05-29T16:55:06.3811788Z Committed to D:\a\r1\a\repo with message "The readme for Version-Assemblies-and-Packages-Tasks YAML
2019-05-29T16:55:07.1503613Z Pushed to github.com/rfennell/AzurePipelines.wiki.git
```

So are you trying to clone a Github or Azure DevOps repo, and what creds are being used (though I don't think it looks likes a creds issue)

**Comment by Frankwin** [comment]
I have not tried a different agent no, but I can see if that makes a difference. All my agents are local once since we deploy to our own locally hosted servers. 
I am trying to clone an Azure DevOps repo and I just have the "Run with Build Agent Credentials" checked as it has permissions do get to the repos, etc in Azure.

**Comment by rfennell** [comment]
Other thing to try is not run the agent as a the nt server account. Try a local agent runni g as a standard domain user

**Comment by Frankwin** [comment]
Ok using a hosted Azure DevOps agent it does seem to work (well at least once I provide it the correct credentials). So yeah does seem to be something w/ a local agent that makes it not work.

**Comment by rfennell** [comment]
I suspect UAC or group policies. I rarely run my on prem agents as a built in account, preferring a domain based service account

**Comment by Frankwin** [comment]
Ok. I'll try to pry a new service account out of my IT folks to see if that helps.

**Comment by Frankwin** [comment]
I guess I spoke too soon. It's still failing w/ the same error even on the hosted Agent:

> 2019-05-30T21:06:17.6594018Z ##[section]Starting: Git based WIKI Updater
> 2019-05-30T21:06:17.6695932Z ==============================================================================
> 2019-05-30T21:06:17.6695995Z Task         : Git based WIKI Updater from Black Marble
> 2019-05-30T21:06:17.6696045Z Description  : A tools to update or create a WIKI based in a Git repo
> 2019-05-30T21:06:17.6696081Z Version      : 1.3.8
> 2019-05-30T21:06:17.6696113Z Author       : Richard Fennell
> 2019-05-30T21:06:17.6696587Z Help         : Version: 1.3.8. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
> 2019-05-30T21:06:17.6696900Z ==============================================================================
> 2019-05-30T21:06:17.9113706Z Variable: Repo [dev.azure.com/TitleOne/TitleOne%20Website/_git/TitleOneWebsite.ReleaseNotes.wiki]
> 2019-05-30T21:06:17.9113831Z Variable: Filename [Release-99.md]
> 2019-05-30T21:06:17.9113895Z Variable: Contents [null]
> 2019-05-30T21:06:17.9113941Z Variable: Commit Message [Auto-Generated Release Notes]
> 2019-05-30T21:06:17.9114040Z Variable: Git Username [Frankwin Hooglander]
> 2019-05-30T21:06:17.9114233Z Variable: Git Email [------HIDDEN------]
> 2019-05-30T21:06:17.9114501Z Variable: Use Agent Token [false]
> 2019-05-30T21:06:17.9114680Z Variable: Username [------HIDDEN------]
> 2019-05-30T21:06:17.9114865Z Variable: Password [------HIDDEN------]
> 2019-05-30T21:06:17.9115037Z Variable: Localpath [$(Sytem.DefaultWorkingDirectory)\repo]
> 2019-05-30T21:06:17.9115201Z Variable: Data Is File [true]
> 2019-05-30T21:06:17.9115406Z Variable: SoureFile [D:\a\r1\a\releasenotes.md]
> 2019-05-30T21:06:17.9284196Z URL used https://uuuuuu:xxxxxx@dev.azure.com/yyyyyyyy/TitleOne%20Website/_git/TitleOneWebsite.ReleaseNotes.wiki
> 2019-05-30T21:06:17.9285447Z Cleaned $(Sytem.DefaultWorkingDirectory)\repo
> 2019-05-30T21:06:22.5015357Z Cloned dev.azure.com/TitleOne/TitleOne%20Website/_git/TitleOneWebsite.ReleaseNotes.wiki to $(Sytem.DefaultWorkingDirectory)\repo
> 2019-05-30T21:06:22.5955684Z Set GIT values in $(Sytem.DefaultWorkingDirectory)\repo
> 2019-05-30T21:06:22.5963778Z No sub-directory passed change to $(Sytem.DefaultWorkingDirectory)\repo
> 2019-05-30T21:06:22.6079772Z ##[error]Error: Error: spawn git ENOENT
> 2019-05-30T21:06:22.6088552Z     at exports._errnoException (util.js:1018:11)
> 2019-05-30T21:06:22.6088649Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 2019-05-30T21:06:22.6088707Z     at onErrorNT (internal/child_process.js:367:16)
> 2019-05-30T21:06:22.6088781Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 2019-05-30T21:06:22.6088829Z     at process._tickCallback (internal/process/next_tick.js:104:9)
> 2019-05-30T21:06:22.6089144Z ##[error]Error: Error: spawn git ENOENT
> 2019-05-30T21:06:22.6089344Z     at exports._errnoException (util.js:1018:11)
> 2019-05-30T21:06:22.6089393Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 2019-05-30T21:06:22.6089463Z     at onErrorNT (internal/child_process.js:367:16)
> 2019-05-30T21:06:22.6089521Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 2019-05-30T21:06:22.6089584Z     at process._tickCallback (internal/process/next_tick.js:104:9)
> 2019-05-30T21:06:22.6089887Z     at exports._errnoException (util.js:1018:11)
> 2019-05-30T21:06:22.6089940Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 2019-05-30T21:06:22.6089987Z     at onErrorNT (internal/child_process.js:367:16)
> 2019-05-30T21:06:22.6090049Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 2019-05-30T21:06:22.6090097Z     at process._tickCallback (internal/process/next_tick.js:104:9)
> 2019-05-30T21:06:22.6574628Z ##[section]Finishing: Git based WIKI Updater

**Comment by rfennell** [comment]
It is failing at this point

```
var workingPath = GetWorkingFolder(localpath, filename, logInfo);
process.chdir(workingPath);
// do git pull just in case the clone was slow and there have been updates since
// this is to try to reduce concurrency issues
**await git.pull();**
logInfo(`Pull in case of post clone updates from other users`);
```

Where the GetWorkingFolder will just return the localpath

```
export function GetWorkingFolder(localpath, filename, logInfo): any {
    var pathParts = path.parse(filename);
    if (pathParts.dir && pathParts.dir !== "/" && pathParts.dir !== "\\") {
        var targetPath = path.join(localpath, path.join(pathParts.dir));
        if (!fs.existsSync(targetPath)) {
            logInfo(`Creating the directory ${targetPath}`);
            mkDirByPathSync(targetPath);
        }
        return targetPath;
    } else {
        logInfo(`No sub-directory passed change to ${localpath}`);
        return localpath;
    }
}
```

So again it is the git operation failing. This is strange, as I know this task is being used by many people without a problem.

I am struggling to see what could be wrong here, so to confirm

- fails on MS hosted agent (windows based) - but work on mine using VS2017 for all my release pipeline
- fails on your private agent running as network service 
- fails on your private agent running as a domain user

What could it be? What am I missing?

**Comment by Frankwin** [comment]
It is very strange as previous git commands have already worked successfully such as the clone and whatever the function that logs the "Set GIT values in $(System.DefaultWorkingDirectory)\repo" message does. 

And yes the first 2 are true, I haven't tried #3 yet as I'm still waiting for the IT guys to create me a domain user service account.

**Comment by Frankwin** [comment]
Really the only thing that I can see cause the issue is if 
process.chdir(workingPath);
doesn't actually go to the correct folder so then the git pull basically returns a "this is not a git repo" type error message. 

As all the other parts of the code just pass the workingPath in

**Comment by Frankwin** [comment]
So I did some Googling and from all the things I see there, it looks like you're missing this line of code:
var process = require('process');    <-- this one
process.chdir(workingPath);

**Comment by rfennell** [comment]
Good find, but strange the Typescript transpile and TSlint did not complain, or any of my testing.

I have added the line and the is a release pipeline running

**Comment by Frankwin** [comment]
Awesome. Do you know how long it takes for it to update in the Azure marketplace?

**Comment by rfennell** [comment]
Depends on the complexity of the pipeline this one is fairly quick, it has just been published as 1.4.1, but it might take a few minutes to propagate out to your instance

**Comment by Frankwin** [comment]
Yep it just did :)

**Comment by Frankwin** [comment]
Well that unfortunately did not fix the issue :(

**Comment by Frankwin** [comment]
Well apparently I also suck at typing and reading:
2019-05-30T21:06:22.5955684Z Set GIT values in $(**Sytem**.DefaultWorkingDirectory)\repo

Pretty sure that's the issue now. :(

**Comment by rfennell** [comment]
Well this one is a pain, as you can see from the logs it all pass in my pipeline https://dev.azure.com/richardfennell/GitHub/_releaseProgress?releaseId=1420&_a=release-environment-logs&environmentId=3733 trying all the various config options.

I am struggling to see what to do next.

**Comment by Frankwin** [comment]
Yep typing in the correct variable name works like a charm :/ Issue resolved.

**Comment by Frankwin** [comment]
It does work on my local agent too now after the fix (the typo was introduced after I switched to the hosted agent)

**Comment by Frankwin** [comment]
So it likely always worked on the hosted agent if I would have typed the variable correctly. The fix definitely did address the issue on the local agent though, so still a good fix.

**Comment by rfennell** [comment]
Great, so we can close it?

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by andyofengland** [comment]
Hi,
I am getting this problem now on my Self-Hosted build VM conneting to an Azure DevOps GIT repo.

I've checked the credentials being used, I've checked the URL of the repo but I keep getting the error.

The YAML in use is (sensitive stuff removed):
```
    -   task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
        displayName: 'Git based WIKI Updater (TEST)'
        condition: and(succeeded(), eq(variables['EnvironmentKey'], 'test'))
        inputs:
            repo: 'dev.azure.com/xxxxxx/_git/Documentation'
            filename: ${{ 'ReleaseNotes/Environments/Test/$(Build.BuildNumber).md' }}
            dataIsFile: true
            sourceFile: '$(BUILD.SOURCESDIRECTORY)\GeneratedReleaseNotes.md'
            message: 'Auto-Generated Release Notes'
            gitname: 'Testing Here'
            gitemail: 'test@test.com'
            useAgentToken: false
            user: ${{parameters.wikiUserName}}
            password: ${{parameters.wikiPassword}}
            localpath: $(BUILD.SOURCESDIRECTORY)\Documentation
```

The error stack I get is:

```
2020-01-21T17:28:15.7967590Z ##[section]Starting: Git based WIKI Updater (TEST)
2020-01-21T17:28:15.8174974Z ==============================================================================
2020-01-21T17:28:15.8175086Z Task         : Git based WIKI Updater from Black Marble
2020-01-21T17:28:15.8175147Z Description  : A tools to update or create a WIKI based in a Git repo
2020-01-21T17:28:15.8175218Z Version      : 1.7.5
2020-01-21T17:28:15.8175261Z Author       : Richard Fennell
2020-01-21T17:28:15.8175337Z Help         : Version: 1.7.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2020-01-21T17:28:15.8175408Z ==============================================================================
2020-01-21T17:28:16.0738815Z ##[debug]agent.workFolder=C:\agent\_work
2020-01-21T17:28:16.0832394Z ##[debug]loading inputs and endpoints
2020-01-21T17:28:16.0834139Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-01-21T17:28:16.0848567Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-01-21T17:28:16.0852005Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-01-21T17:28:16.0854726Z ##[debug]loading INPUT_APPENDTOFILE
2020-01-21T17:28:16.0857240Z ##[debug]loading INPUT_DATAISFILE
2020-01-21T17:28:16.0859709Z ##[debug]loading INPUT_FILENAME
2020-01-21T17:28:16.0861557Z ##[debug]loading INPUT_GITEMAIL
2020-01-21T17:28:16.0863586Z ##[debug]loading INPUT_GITNAME
2020-01-21T17:28:16.0865331Z ##[debug]loading INPUT_LOCALPATH
2020-01-21T17:28:16.0867328Z ##[debug]loading INPUT_MESSAGE
2020-01-21T17:28:16.0869082Z ##[debug]loading INPUT_PASSWORD
2020-01-21T17:28:16.0872353Z ##[debug]loading INPUT_REPLACEFILE
2020-01-21T17:28:16.0903210Z ##[debug]loading INPUT_REPO
2020-01-21T17:28:16.0903839Z ##[debug]loading INPUT_SOURCEFILE
2020-01-21T17:28:16.0904156Z ##[debug]loading INPUT_TAGREPO
2020-01-21T17:28:16.0904403Z ##[debug]loading INPUT_USEAGENTTOKEN
2020-01-21T17:28:16.0904957Z ##[debug]loading INPUT_USER
2020-01-21T17:28:16.0905230Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2020-01-21T17:28:16.0905494Z ##[debug]loaded 18
2020-01-21T17:28:16.1045331Z ##[debug]repo=dev.azure.com/xxxx/_git/Documentation
2020-01-21T17:28:16.1050518Z ##[debug]filename=ReleaseNotes/Environments/Test/2020.01.21.20.md
2020-01-21T17:28:16.1052083Z ##[debug]localpath=C:\agent\_work\14\s\Documentation
2020-01-21T17:28:16.1060417Z ##[debug]contents=null
2020-01-21T17:28:16.1063140Z ##[debug]message=Auto-Generated Release Notes
2020-01-21T17:28:16.1065140Z ##[debug]gitname=Testing Here
2020-01-21T17:28:16.1066714Z ##[debug]gitemail=test@test.com
2020-01-21T17:28:16.1068235Z ##[debug]user=some name here
2020-01-21T17:28:16.1069799Z ##[debug]password=xxxxx
2020-01-21T17:28:16.1072097Z ##[debug]useAgentToken=false
2020-01-21T17:28:16.1073913Z ##[debug]replaceFile=True
2020-01-21T17:28:16.1076128Z ##[debug]appendToFile=True
2020-01-21T17:28:16.1085786Z ##[debug]dataIsFile=true
2020-01-21T17:28:16.1087040Z ##[debug]sourceFile=C:\agent\_work\14\s\GeneratedReleaseNotes.md
2020-01-21T17:28:16.1088831Z ##[debug]tagRepo=False
2020-01-21T17:28:16.1089177Z ##[debug]tag=null
2020-01-21T17:28:16.1105506Z Variable: Repo [dev.azure.com/xxxx/_git/Documentation]
2020-01-21T17:28:16.1105869Z Variable: Filename [ReleaseNotes/Environments/Test/2020.01.21.20.md]
2020-01-21T17:28:16.1106257Z Variable: Contents [null]
2020-01-21T17:28:16.1106489Z Variable: Commit Message [Auto-Generated Release Notes]
2020-01-21T17:28:16.1106898Z Variable: Git Username [Testing Here]
2020-01-21T17:28:16.1107063Z Variable: Git Email [test@test.com]
2020-01-21T17:28:16.1107223Z Variable: Use Agent Token [false]
2020-01-21T17:28:16.1108987Z Variable: Replace File [true]
2020-01-21T17:28:16.1109213Z Variable: Append to File [true]
2020-01-21T17:28:16.1109566Z Variable: Username [xxxx]
2020-01-21T17:28:16.1109731Z Variable: Password [xxxx]
2020-01-21T17:28:16.1110087Z Variable: Localpath [C:\agent\_work\14\s\Documentation]
2020-01-21T17:28:16.1110262Z Variable: Data Is File [true]
2020-01-21T17:28:16.1110420Z Variable: SoureFile [C:\agent\_work\14\s\GeneratedReleaseNotes.md]
2020-01-21T17:28:16.1110594Z Variable: Tag Repo [false]
2020-01-21T17:28:16.1110743Z Variable: Tag [null]
2020-01-21T17:28:16.1336716Z URL used https://xxx:***@dev.azure.com/xxx/_git/Documentation
2020-01-21T17:28:16.1337895Z Cleaned C:\agent\_work\14\s\Documentation
2020-01-21T17:28:16.1353046Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1357852Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1358463Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1358697Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1358905Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1359092Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1359286Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1359459Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1359651Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1359823Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1360013Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1360184Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1360381Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1360562Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1360754Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1361337Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1361546Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1361738Z (node:7836) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-01-21T17:28:16.1463559Z ##[error]Error: Error: spawn git ENOENT
2020-01-21T17:28:16.1463866Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT
2020-01-21T17:28:16.1464429Z     at exports._errnoException (util.js:1020:11)
2020-01-21T17:28:16.1464643Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
2020-01-21T17:28:16.1465024Z     at onErrorNT (internal/child_process.js:376:16)
2020-01-21T17:28:16.1465228Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-01-21T17:28:16.1465452Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-01-21T17:28:16.1465624Z     at Module.runMain (module.js:613:11)
2020-01-21T17:28:16.1465823Z     at run (bootstrap_node.js:394:7)
2020-01-21T17:28:16.1465991Z     at startup (bootstrap_node.js:160:9)
2020-01-21T17:28:16.1466171Z     at bootstrap_node.js:507:3
2020-01-21T17:28:16.1466509Z ##[debug]task result: Failed
2020-01-21T17:28:16.1467116Z ##[error]Error: Error: spawn git ENOENT
2020-01-21T17:28:16.1467493Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT
2020-01-21T17:28:16.1467709Z     at exports._errnoException (util.js:1020:11)
2020-01-21T17:28:16.1468060Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
2020-01-21T17:28:16.1468253Z     at onErrorNT (internal/child_process.js:376:16)
2020-01-21T17:28:16.1468756Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-01-21T17:28:16.1469718Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-01-21T17:28:16.1469886Z     at Module.runMain (module.js:613:11)
2020-01-21T17:28:16.1470067Z     at run (bootstrap_node.js:394:7)
2020-01-21T17:28:16.1470236Z     at startup (bootstrap_node.js:160:9)
2020-01-21T17:28:16.1470412Z     at bootstrap_node.js:507:3
2020-01-21T17:28:16.1497673Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: spawn git ENOENT
2020-01-21T17:28:16.1497987Z     at exports._errnoException (util.js:1020:11)
2020-01-21T17:28:16.1498169Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
2020-01-21T17:28:16.1498368Z     at onErrorNT (internal/child_process.js:376:16)
2020-01-21T17:28:16.1498533Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-01-21T17:28:16.1498715Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-01-21T17:28:16.1499056Z     at Module.runMain (module.js:613:11)
2020-01-21T17:28:16.1499418Z     at run (bootstrap_node.js:394:7)
2020-01-21T17:28:16.1499600Z     at startup (bootstrap_node.js:160:9)
2020-01-21T17:28:16.1499781Z     at bootstrap_node.js:507:3
2020-01-21T17:28:16.1528948Z ##[section]Finishing: Git based WIKI Updater (TEST)
```

The build server itself is an Azure hosted VM; has many things installed to meet the requirements of the build chain (MSBuild, VS, GIT, Docker etc etc.)

The YAML file is a part of a multi-stage pipeline and the above block is from the release phase.

It all seems to work (I think, not executed a release lately) from a visual pipeline; this is the first of the YAML ones.

Any assistance is most welcome.

Cheers

**Comment by rfennell** [comment]
@andyofengland so it is easier to track I have  created a dedicated issue #613
