### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by philcarbone** [rfennell/AzurePipelines#515]
### Azure DevOps Extension you are using
XplatGeneratReleaseNotes

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version 2

### Expected behaviour and actual behaviour
That no error is thrown ;)

### Steps to reproduce the problem

1. Used the template provided at in the documentation:
```
# Release notes
## Notes for release  ${releaseDetails.releaseDefinition.name}
**Release Number**  : ${releaseDetails.name}
**Release completed** : ${releaseDetails.modifiedOn}
**Compared Release Number**  : ${compareReleaseDetails.name}

### All associated work items
@@WILOOP@@
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}
@@WILOOP@@

### Associated work items that have both the tags 'Tag 1' and 'Tag2'
@@WILOOP:Tag 1:Tag2@@
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}
@@WILOOP:Tag 1:Tag2@@

### Associated commits
@@CSLOOP@@
* **ID ${csdetail.id} ** ${csdetail.message}
@@CSLOOP@@
```

2. Run the build on Ubuntu hosted agent
3. Build fails with the following error:
```
TypeError: Cannot read property 'toLowerCase' of undefined
```
---
Here is the output from the build step:
```

##[debug]Evaluating condition for step: 'XplatGenerateReleaseNotes' |  
-- | --
  | ##[debug]Evaluating: SucceededNode() |  
  | ##[debug]Evaluating SucceededNode: |  
  | ##[debug]=> True |  
 
  | ##[debug]agent.TempDirectory=/home/vsts/work/_temp |  
  | ##[debug]loading inputs and endpoints |  
  | ##[debug]loading INPUT_OUTPUTFILE |  
  | ##[debug]loading INPUT_TEMPLATELOCATION |  
  | ##[debug]loading INPUT_TEMPLATEFILE |  
  | ##[debug]loading INPUT_EMPTYSETTEXT |  
  | ##[debug]loading INPUT_DELIMITER |  
  | ##[debug]loading INPUT_STOPONREDEPLOY |  
  | ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION |  
  | ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION |  
  | ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN |  
  | ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN |  
  | ##[debug]loaded 10 |  
  | ##[debug]Agent.ProxyUrl=undefined |  
  | ##[debug]Agent.CAInfo=undefined |  
  | ##[debug]Agent.ClientCert=undefined |  
  | ##[debug]Agent.SkipCertValidation=undefined |  
  | ##[debug]Starting Tag XplatGenerateReleaseNotes task |  
  | ##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/onshift/ |  
  | ##[debug]System.TeamProject=ProductDevelopment |  
  | ##[debug]Release.ReleaseId=undefined |  
  | ##[debug]Release.DefinitionId=undefined |  
  | ##[debug]overrideStageName=null |  
  | ##[debug]Release_EnvironmentName=undefined |  
  | ##[error]TypeError: Cannot read property 'toLowerCase' of undefined |  
  | ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'toLowerCase' of undefined |  
  | ##[debug]SYSTEM.HOSTTYPE=build |  
  | ##[debug]BUILD.DEFINITIONNAME=Denali.API (1) |  
  | ##[debug]BUILD.BUILDID=3167 |  
  | ##[debug]SYSTEM.TEAMFOUNDATIONSERVERURI=https://dev.azure.com/onshift/ |  
  | ##[debug]SYSTEM.TEAMPROJECT=ProductDevelopment |  
  | ##[debug]BUILD.BUILDID=3167 |  
  | ##[debug]TASK.DISPLAYNAME=XplatGenerateReleaseNotes |  
  | ##[debug]SYSTEM.JOBID=12f1170f-54f2-53f3-20dd-22fc7dff55f9 |  
  | ##[debug]AGENT.VERSION=2.154.3 |  
  | ##[debug]Processed: ##vso[telemetry.publish area=XplatGenerateReleaseNotes;feature=reliability]{"hostType":"build","definitionName":"Denali.API (1)","processId":"3167","processUrl":"https://dev.azure.com/onshift/ProductDevelopment/_build?buildId=3167","taskDisplayName":"XplatGenerateReleaseNotes","jobid":"12f1170f-54f2-53f3-20dd-22fc7dff55f9","agentVersion":"2.154.3","version":{"Major":"2","Minor":"9","Patch":"6"},"issueType":"error","errorMessage":"{\"stack\":\"TypeError: Cannot read property 'toLowerCase' of undefined\\n    at /home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:28:118\\n    at next (native)\\n    at /home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:7:71\\n    at __awaiter (/home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:3:12)\\n    at Promise (/home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:20:56)\\n    at /home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:20:23\\n    at next (native)\\n    at /home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:7:71\\n    at __awaiter (/home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:3:12)\\n    at run (/home/vsts/work/_tasks/XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb/2.9.6/GenerateReleaseNotes.js:19:12)\",\"message\":\"Cannot read property 'toLowerCase' of undefined\"}"} |  
  | ##[debug]task result: Failed |  
  | ##[error]TypeError: Cannot read property 'toLowerCase' of undefined |  
  | ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'toLowerCase' of undefined |  
  | ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'toLowerCase' of undefined |  
  | Finishing: XplatGenerateReleaseNotes

```

**Comment by rfennell** [comment]
I have check a log on my test Ubuntu agent

```
019-07-24T21:00:11.3399492Z Help : Version: 2.10.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task/)
2019-07-24T21:00:11.3399649Z ==============================================================================
2019-07-24T21:00:11.5050854Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2019-07-24T21:00:11.5078434Z ##[debug]loading inputs and endpoints
2019-07-24T21:00:11.5083186Z ##[debug]loading INPUT_OUTPUTFILE
2019-07-24T21:00:11.5093294Z ##[debug]loading INPUT_OUTPUTVARIABLENAME
2019-07-24T21:00:11.5095196Z ##[debug]loading INPUT_TEMPLATELOCATION
2019-07-24T21:00:11.5096884Z ##[debug]loading INPUT_TEMPLATEFILE
2019-07-24T21:00:11.5098235Z ##[debug]loading INPUT_INLINETEMPLATE
2019-07-24T21:00:11.5099663Z ##[debug]loading INPUT_EMPTYSETTEXT
2019-07-24T21:00:11.5101171Z ##[debug]loading INPUT_DELIMITER
2019-07-24T21:00:11.5102840Z ##[debug]loading INPUT_STOPONREDEPLOY
2019-07-24T21:00:11.5104392Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-07-24T21:00:11.5105874Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-07-24T21:00:11.5107327Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-07-24T21:00:11.5115339Z ##[debug]loading SECRET_GITHUBPAT
2019-07-24T21:00:11.5115496Z ##[debug]loading SECRET_FUNCTIONKEY
2019-07-24T21:00:11.5117014Z ##[debug]loading SECRET_PAT
2019-07-24T21:00:11.5117957Z ##[debug]loaded 14
2019-07-24T21:00:11.5140697Z ##[debug]Agent.ProxyUrl=undefined
2019-07-24T21:00:11.5145518Z ##[debug]Agent.CAInfo=undefined
2019-07-24T21:00:11.5145742Z ##[debug]Agent.ClientCert=undefined
2019-07-24T21:00:11.5145919Z ##[debug]Agent.SkipCertValidation=undefined
2019-07-24T21:00:11.6666121Z ##[debug]Starting Tag XplatGenerateReleaseNotes task
2019-07-24T21:00:11.6666527Z ##[debug]System.TeamFoundationCollectionUri=https://richardfennell.visualstudio.com/
2019-07-24T21:00:11.6666762Z ##[debug]System.TeamProject=GitHub
2019-07-24T21:00:11.6666941Z ##[debug]Release.ReleaseId=1447
2019-07-24T21:00:11.6667161Z ##[debug]Release.DefinitionId=13
2019-07-24T21:00:11.6670578Z ##[debug]overrideStageName=null
2019-07-24T21:00:11.6671594Z ##[debug]Release_EnvironmentName=Tests - Linux
2019-07-24T21:00:11.6678909Z ##[debug]templateLocation=InLine
2019-07-24T21:00:11.6708459Z ##[debug]templatefile=/home/vsts/work/r1/a
2019-07-24T21:00:11.6710495Z ##[debug]inlinetemplate=# Release notes
```

I think the issue is that you don't have any a number of the variable set such as release_environment, release.releaseID  these are essential for the task to work.

The strange thing is I am not sure how you can get into this state as all these fields are automatically populated from environment variable.

Can you give me any context on your usage, any idea why the setting may not be set

As a reference you can see my test release at https://dev.azure.com/richardfennell/GitHub/_releaseProgress?releaseId=1447&_a=release-pipeline-progress

**Comment by philcarbone** [comment]
Hi @rfennell - I was using it in a build pipeline (not a release pipeline). It works as expected in a release pipeline. Thank you!

**Comment by rfennell** [comment]
Initially thought you can't do that , but with YAML of course it is. Glad you are sorted

**Comment by scottrmathews** [comment]
I also hit this when running it a build pipeline vs release pipeline. YAML is the default for Azure DevOps pipelines now, so I imagine other folks will start hitting this more frequently.

**Comment by rfennell** [comment]
Yes I need to put a message to give a better user experience
