### ISSUE TITLE
Wiki Updater Git Error

### ISSUE THREAD

**Issue by lisabaker1966** [rfennell/AzurePipelines#685]
### Azure DevOps Extension you are using
Wiki Updater

### Where are you running it?
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
currently public version

Error:
2020-04-17T16:27:10.6272206Z ##[section]Starting: Git based WIKI Updater
2020-04-17T16:27:10.6412544Z ==============================================================================
2020-04-17T16:27:10.6412641Z Task         : Git based WIKI Updater from Black Marble
2020-04-17T16:27:10.6412682Z Description  : A tools to update or create a WIKI based in a Git repo
2020-04-17T16:27:10.6412723Z Version      : 1.8.7
2020-04-17T16:27:10.6412759Z Author       : Richard Fennell
2020-04-17T16:27:10.6412800Z Help         : Version: 1.8.7. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2020-04-17T16:27:10.6412836Z ==============================================================================
2020-04-17T16:27:11.0491566Z Variable: Repo [qtsnasazdops01/DefaultCollection/BeneFACT%20Legacy%20Code/_git/BeneFACT-Legacy-Code.wiki]
2020-04-17T16:27:11.0491874Z Variable: Filename [Releases.md]
2020-04-17T16:27:11.0492197Z Variable: Contents [null]
2020-04-17T16:27:11.0492469Z Variable: Commit Message [Release Notes]
2020-04-17T16:27:11.0492946Z Variable: Git Username [lisa baker]
2020-04-17T16:27:11.0493121Z Variable: Git Email [lisa.baker@nasco.com]
2020-04-17T16:27:11.0493172Z Variable: Use Agent Token [true]
2020-04-17T16:27:11.0493393Z Variable: Replace File [true]
2020-04-17T16:27:11.0493701Z Variable: Append to File [false]
2020-04-17T16:27:11.0493983Z Variable: Username [nasco\lbaker]
2020-04-17T16:27:11.0494116Z Variable: Password [nlzeewxtwbup662ssqcc5mds6ni2tfo3dpqp5kkdeudnlc75cgta]
2020-04-17T16:27:11.0494332Z Variable: Localpath [G:\Agents\Agent.2019.1\_work\r1\a\repo]
2020-04-17T16:27:11.0494455Z Variable: Data Is File [true]
2020-04-17T16:27:11.0494825Z Variable: SoureFile [G:\Agents\Agent.2019.1\_work\r1\a\releasenotes.md]
2020-04-17T16:27:11.0495050Z Variable: Tag Repo [false]
2020-04-17T16:27:11.0495138Z Variable: Tag [null]
2020-04-17T16:27:11.0495384Z Variable: InjectExtraHeader [false]
2020-04-17T16:27:11.0495692Z Using OAUTH Agent Token, overriding username and password
2020-04-17T16:27:11.0500136Z SYSTEMVSSCONNECTION exists true
2020-04-17T16:27:11.0691639Z URL used <removed for security purposes>
2020-04-17T16:27:11.0693404Z Cleaned G:\Agents\Agent.2019.1\_work\r1\a\repo
2020-04-17T16:27:11.0880524Z ##[error]Error: Error: spawn git ENOENT
2020-04-17T16:27:11.0888638Z     at exports._errnoException (util.js:1018:11)
2020-04-17T16:27:11.0888740Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2020-04-17T16:27:11.0888792Z     at onErrorNT (internal/child_process.js:367:16)
2020-04-17T16:27:11.0888858Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-04-17T16:27:11.0888946Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-04-17T16:27:11.0888992Z     at Module.runMain (module.js:606:11)
2020-04-17T16:27:11.0889033Z     at run (bootstrap_node.js:390:7)
2020-04-17T16:27:11.0889084Z     at startup (bootstrap_node.js:150:9)
2020-04-17T16:27:11.0889141Z     at bootstrap_node.js:505:3
2020-04-17T16:27:11.0889397Z ##[error]Error: Error: spawn git ENOENT
2020-04-17T16:27:11.0889567Z     at exports._errnoException (util.js:1018:11)
2020-04-17T16:27:11.0889978Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2020-04-17T16:27:11.0890091Z     at onErrorNT (internal/child_process.js:367:16)
2020-04-17T16:27:11.0890178Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-04-17T16:27:11.0890260Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-04-17T16:27:11.0890337Z     at Module.runMain (module.js:606:11)
2020-04-17T16:27:11.0890430Z     at run (bootstrap_node.js:390:7)
2020-04-17T16:27:11.0890512Z     at startup (bootstrap_node.js:150:9)
2020-04-17T16:27:11.0890558Z     at bootstrap_node.js:505:3
2020-04-17T16:27:11.0890866Z     at exports._errnoException (util.js:1018:11)
2020-04-17T16:27:11.0890943Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
2020-04-17T16:27:11.0891943Z     at onErrorNT (internal/child_process.js:367:16)
2020-04-17T16:27:11.0891995Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2020-04-17T16:27:11.0892046Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2020-04-17T16:27:11.0892092Z     at Module.runMain (module.js:606:11)
2020-04-17T16:27:11.0892159Z     at run (bootstrap_node.js:390:7)
2020-04-17T16:27:11.0892205Z     at startup (bootstrap_node.js:150:9)
2020-04-17T16:27:11.0892246Z     at bootstrap_node.js:505:3
2020-04-17T16:27:11.0893401Z ##[section]Finishing: Git based WIKI Updater

**Comment by lisabaker1966** [comment]
I have "allow oath" set to true; i have use buildagent set to true;

**Comment by rfennell** [comment]
Not sure of the issue off the top of my head. I will have to spin up a Azure DevOps Server VM locally and give it a test.

**Comment by lisabaker1966** [comment]
ok. thanks

**Comment by rfennell** [comment]
Ok remember this solution to this issue, and tested it on a default install Azure DevOps Server 2019.1.

You need to select 

- Allow access to OUATH for the agent phase
- Make sure the Project Collection Build User has contribute rights to the WIKI
- UseAgentToken enabled
- injectExtraHeader is enabled

The injectExtraHeader flag was added to address issue issue such as this (See #613)

This seems to work, but does assume that the server is accessed via HTTPS as this is hard coded for the URL in the task..

If you only have your server using HTTP this will fail as the task will always try to swap to HTTPS

The YAML is

```
- task: richardfennellBM.BM-VSTS-WIKIUpdater-Tasks.WikiUpdaterTask.WikiUpdaterTask@1
  displayName: 'Git based WIKI Updater'
  inputs:
    repo: 'tfs2019.mydomain.com/tfs/DefaultCollection/Test1/_git/Test1.wiki'
    filename: page.md
    contents: '$(build.buildnumber)'
    message: 'A commit message'
    gitname: dummy
    gitemail: 'dummy@domain
    useAgentToken: true
    injectExtraHeader: true
```

Let me know if that works for you, if it does I will update the documentation to make it a little clearer

**Comment by rfennell** [comment]
I have just [update the documentation for this task](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks). Hopefully that is a bit clearer

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by lisabaker1966** [comment]
Thanks Richard.
I was missing the "injectextraheader". it's working now.  Great tool. thanks again
