### ISSUE TITLE
##[error]TypeError: Cannot read property 'releaseDefinition' of undefined

### ISSUE THREAD

**Issue by dgarima** [rfennell/AzurePipelines#714]
I am using the below sample template and observing that during the build below error is being reported every time.Can you pleas elt me know how is -releaseDefinition being populated in the below sample template.
##[error]TypeError: Cannot read property 'releaseDefinition' of undefined

**SAMPLE TEMPLATE** 
# Release notes
## Notes for release  ${releaseDetails.releaseDefinition.name}
**Release Number**  : ${releaseDetails.name}
**Release completed** : ${releaseDetails.modifiedOn}
**Compared Release Number**  : ${compareReleaseDetails.name}
**Build Trigger PR Number**: ${buildDetails.triggerInfo['pr.number']}
**PR Details Title **: ${prDetails.title}

### All associated work items
@@WILOOP@@
* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}
@@WILOOP@@

### Associated commits
@@CSLOOP@@
* **ID ${csdetail.id} ** ${csdetail.message}
@@CSLOOP@@

### Associated commits with regex filter in form 'Merged PR #1234'
@@CSLOOP[^Merged PR #.+]@@
* **ID ${csdetail.id} ** ${csdetail.message}
@@CSLOOP[^Merged PR  #.+]@@

**Comment by rfennell** [comment]
Where are you running this task? Is it in Release or a Build/YAML Pipeline? The reason I ask is because the `releaseDetails` is only set in a release.

To see what has been set run a release/build again with a variable `system.debug=true` to get a debug log of all the data discovery.

Also I would recommend you consider looking at the newer Handlebars based templates as opposed to the legacy template format you are using. This won't effect this issue, but Handles is the future of this task, all new features will use this template format

**Comment by dgarima** [comment]
Hi 
I added it as part of the release pipeline and i am now getting the below error in the wiki updater task.Can you please let me know where do i need to add system.debug=true variable in the pipeline?Do i need to add it at the task level ?
Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by rfennell** [comment]
I am a bit confused, am I right in understanding are you saying now that the release notes are working and generating a file, and you now have problems with uploading it to a WIKI?

Most issues with the WIKI Updater are down to authentication - please check the [documentation (at the bottom of the page)](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks) for how to set permissions and the accounts to use.

As to getting debug, in either a build or a release to set debug information create a variable called `system.debug` with the value `true`, this will show debug details for the task.

**Comment by dgarima** [comment]
Yes ,now the release notes are getting generated fine and i used the below steps to set up the authentication --
ow the pipeline to access the OAUTH Token
Grant contribute access on the target Azure DevOps WIKI to the Project Collection Build Service user (assuming this is the account the pipeline is running as).
Set the task's UseAgentToken parameter to true
Set the task's InjectExtraHeader parameter to true

and now i am still getting the below exception -

2020-05-14T23:34:05.4731489Z ##[debug]Getting credentials the agent is running as
2020-05-14T23:34:05.4733942Z ##[debug]SYSTEMVSSCONNECTION exists ***
2020-05-14T23:34:05.4734383Z ##[debug]Found an OAUTH token
2020-05-14T23:34:05.4854001Z Injecting the authentication via the clone command using paramter -c http.extraheader='AUTHORIZATION: bearer ***'
2020-05-14T23:34:05.4854355Z URL used **<URL>**
2020-05-14T23:34:05.4854413Z Cleaned /opt/azure/agent1/_work/r2/a\repo
2020-05-14T23:34:05.5033119Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-14T23:34:05.5042626Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-14T23:34:05.5042963Z ##[debug]task result: Failed
2020-05-14T23:34:05.5043368Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-14T23:34:05.5043696Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-14T23:34:05.5044306Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-14T23:34:05.5045433Z ##[section]Finishing: WIKI Updater

**Comment by rfennell** [comment]
If you are running in Azure DevOps Services you should not need the set the task's `InjectExtraHeader` parameter enabled as this was added to address problems some people were seeing with on premises TFS/Azure Server Server issues.

I normally find the best way to debug is to use a PAT generated for you main user with the rights, get that working and then move using OAUTH and build agent.

if that does not help can you add a full debug log to this issue for me to check

**Comment by dgarima** [comment]
I removed the InjectExtraHeader option  for OAUTH and below are the debug logs for the error.

2020-05-15T22:13:17.6311539Z ##[debug]Evaluating condition for step: 'WIKI Updater'
2020-05-15T22:13:17.6312103Z ##[debug]Evaluating: succeeded()
2020-05-15T22:13:17.6312217Z ##[debug]Evaluating succeeded:
2020-05-15T22:13:17.6312377Z ##[debug]=> True
2020-05-15T22:13:17.6312660Z ##[debug]Result: True
2020-05-15T22:13:17.6312882Z ##[section]Starting: WIKI Updater
2020-05-15T22:13:17.6316503Z ==============================================================================
2020-05-15T22:13:17.6316575Z Task         : Git based WIKI Single File Updater from Black Marble
2020-05-15T22:13:17.6316615Z Description  : A tools to update or create a file in a WIKI based in a Git repo 
2020-05-15T22:13:17.6316667Z Version      : 1.10.21
2020-05-15T22:13:17.6316703Z Author       : Richard Fennell
2020-05-15T22:13:17.6316768Z Help         : Version: 1.10.21. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2020-05-15T22:13:17.6316808Z ==============================================================================
2020-05-15T22:13:17.8753922Z ##[debug]agent.TempDirectory=/opt/azure/agent1/_work/_temp
2020-05-15T22:13:17.8773213Z ##[debug]loading inputs and endpoints
2020-05-15T22:13:17.8777336Z ##[debug]loading INPUT_REPO
2020-05-15T22:13:17.8787473Z ##[debug]loading INPUT_BRANCH
2020-05-15T22:13:17.8789841Z ##[debug]loading INPUT_FILENAME
2020-05-15T22:13:17.8791182Z ##[debug]loading INPUT_REPLACEFILE
2020-05-15T22:13:17.8792249Z ##[debug]loading INPUT_APPENDTOFILE
2020-05-15T22:13:17.8793332Z ##[debug]loading INPUT_DATAISFILE
2020-05-15T22:13:17.8794714Z ##[debug]loading INPUT_SOURCEFILE
2020-05-15T22:13:17.8795116Z ##[debug]loading INPUT_MESSAGE
2020-05-15T22:13:17.8796303Z ##[debug]loading INPUT_TAGREPO
2020-05-15T22:13:17.8797277Z ##[debug]loading INPUT_GITNAME
2020-05-15T22:13:17.8798231Z ##[debug]loading INPUT_GITEMAIL
2020-05-15T22:13:17.8799182Z ##[debug]loading INPUT_USEAGENTTOKEN
2020-05-15T22:13:17.8800137Z ##[debug]loading INPUT_USER
2020-05-15T22:13:17.8801159Z ##[debug]loading INPUT_PASSWORD
2020-05-15T22:13:17.8802348Z ##[debug]loading INPUT_LOCALPATH
2020-05-15T22:13:17.8803195Z ##[debug]loading INPUT_INJECTEXTRAHEADER
2020-05-15T22:13:17.8804242Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-05-15T22:13:17.8805246Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-05-15T22:13:17.8806254Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-05-15T22:13:17.8812174Z ##[debug]loading SECRET_SYSTEM_DEBUG
2020-05-15T22:13:17.8813442Z ##[debug]loaded 20
2020-05-15T22:13:17.8821289Z ##[debug]Agent.ProxyUrl=undefined
2020-05-15T22:13:17.8822599Z ##[debug]Agent.CAInfo=undefined
2020-05-15T22:13:17.8822729Z ##[debug]Agent.ClientCert=undefined
2020-05-15T22:13:17.8822838Z ##[debug]Agent.SkipCertValidation=undefined
2020-05-15T22:13:17.8951991Z ##[debug]repo=E-Commerce/_git/E-Commerce.wiki
2020-05-15T22:13:17.8953916Z ##[debug]filename=ReleaseNotes/$(Release.ReleaseName.md)
2020-05-15T22:13:17.8955047Z ##[debug]localpath=/opt/azure/agent1/_work/r2/a\repo
2020-05-15T22:13:17.8955421Z ##[debug]contents=undefined
2020-05-15T22:13:17.8956813Z ##[debug]message=Auto-Generated Release Notes
2020-05-15T22:13:17.8957264Z ##[debug]gitname=Garima Dubey
2020-05-15T22:13:17.8958227Z ##[debug]gitemail=gadubey@deloitte.com
2020-05-15T22:13:17.8965323Z ##[debug]user=gadubey@deloitte.com
2020-05-15T22:13:17.8965689Z ##[debug]password=nn2vrfb2mnnolth77tyzmtg6j6nnitk6roue7ljfgtv4blcg4pka
2020-05-15T22:13:17.8965875Z ##[debug]useAgentToken=***
2020-05-15T22:13:17.8970436Z ##[debug]replaceFile=false
2020-05-15T22:13:17.8971468Z ##[debug]appendToFile=***
2020-05-15T22:13:17.8972622Z ##[debug]dataIsFile=***
2020-05-15T22:13:17.8973579Z ##[debug]sourceFile=/opt/azure/agent1/_work/r2/a\releasenotes.md.
2020-05-15T22:13:17.8974481Z ##[debug]tagRepo=false
2020-05-15T22:13:17.8974575Z ##[debug]tag=undefined
2020-05-15T22:13:17.8986671Z ##[debug]branch=develop
2020-05-15T22:13:17.8986811Z ##[debug]injectExtraHeader=false
2020-05-15T22:13:17.8994885Z Variable: Repo [E-Commerce/_git/E-Commerce.wiki]
2020-05-15T22:13:17.8995231Z Variable: Filename [ReleaseNotes/$(Release.ReleaseName.md)]
2020-05-15T22:13:17.8995274Z Variable: Contents [undefined]
2020-05-15T22:13:17.8995568Z Variable: Commit Message [Auto-Generated Release Notes]
2020-05-15T22:13:17.8995660Z Variable: Git Username [Garima Dubey]
2020-05-15T22:13:17.8995704Z Variable: Git Email [gadubey@deloitte.com]
2020-05-15T22:13:17.8995812Z Variable: Use Agent Token [***]
2020-05-15T22:13:17.8995895Z Variable: Replace File [false]
2020-05-15T22:13:17.8995948Z Variable: Append to File [***]
2020-05-15T22:13:17.8995989Z Variable: Username [gadubey@deloitte.com]
2020-05-15T22:13:17.8996058Z Variable: Password [nn2vrfb2mnnolth77tyzmtg6j6nnitk6roue7ljfgtv4blcg4pka]
2020-05-15T22:13:17.8996141Z Variable: Localpath [/opt/azure/agent1/_work/r2/a\repo]
2020-05-15T22:13:17.8996253Z Variable: Data Is File [***]
2020-05-15T22:13:17.8996360Z Variable: SoureFile [/opt/azure/agent1/_work/r2/a\releasenotes.md.]
2020-05-15T22:13:17.8996645Z Variable: Tag Repo [false]
2020-05-15T22:13:17.8996745Z Variable: Tag [undefined]
2020-05-15T22:13:17.8996793Z Variable: Branch [develop]
2020-05-15T22:13:17.8996832Z Variable: InjectExtraHeader [false]
2020-05-15T22:13:17.8996914Z Using OAUTH Agent Token, overriding username and password
2020-05-15T22:13:17.8998116Z ##[debug]Getting credentials the agent is running as
2020-05-15T22:13:17.9000384Z ##[debug]SYSTEMVSSCONNECTION exists ***
2020-05-15T22:13:17.9000517Z ##[debug]Found an OAUTH token
2020-05-15T22:13:17.9120215Z URL used https://buildagent:***@E-Commerce/_git/E-Commerce.wiki
2020-05-15T22:13:17.9120798Z Cleaned /opt/azure/agent1/_work/r2/a\repo
2020-05-15T22:13:17.9303574Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-15T22:13:17.9312916Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:13:17.9313231Z ##[debug]task result: Failed
2020-05-15T22:13:17.9313729Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-15T22:13:17.9314014Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:13:17.9314586Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:13:17.9315633Z ##[section]Finishing: WIKI Updater

**Comment by dgarima** [comment]
I tried it with username and PAT as well and getting the below error-

2020-05-15T22:26:51.1426392Z ##[debug]Evaluating condition for step: 'WIKI Updater'
2020-05-15T22:26:51.1426997Z ##[debug]Evaluating: succeeded()
2020-05-15T22:26:51.1427140Z ##[debug]Evaluating succeeded:
2020-05-15T22:26:51.1427345Z ##[debug]=> True
2020-05-15T22:26:51.1427810Z ##[debug]Result: True
2020-05-15T22:26:51.1428032Z ##[section]Starting: WIKI Updater
2020-05-15T22:26:51.1432057Z ==============================================================================
2020-05-15T22:26:51.1432125Z Task         : Git based WIKI Single File Updater from Black Marble
2020-05-15T22:26:51.1432169Z Description  : A tools to update or create a file in a WIKI based in a Git repo 
2020-05-15T22:26:51.1432207Z Version      : 1.10.21
2020-05-15T22:26:51.1432279Z Author       : Richard Fennell
2020-05-15T22:26:51.1432320Z Help         : Version: 1.10.21. [More Information](https://github.com/rfennell/vNextBuild/wiki/Wiki-Updater-Task/)
2020-05-15T22:26:51.1432362Z ==============================================================================
2020-05-15T22:26:51.5161465Z ##[debug]agent.TempDirectory=/opt/azure/agent1/_work/_temp
2020-05-15T22:26:51.5204801Z ##[debug]loading inputs and endpoints
2020-05-15T22:26:51.5210939Z ##[debug]loading INPUT_REPO
2020-05-15T22:26:51.5253120Z ##[debug]loading INPUT_BRANCH
2020-05-15T22:26:51.5257348Z ##[debug]loading INPUT_FILENAME
2020-05-15T22:26:51.5260048Z ##[debug]loading INPUT_REPLACEFILE
2020-05-15T22:26:51.5262663Z ##[debug]loading INPUT_APPENDTOFILE
2020-05-15T22:26:51.5265052Z ##[debug]loading INPUT_DATAISFILE
2020-05-15T22:26:51.5267298Z ##[debug]loading INPUT_SOURCEFILE
2020-05-15T22:26:51.5269646Z ##[debug]loading INPUT_MESSAGE
2020-05-15T22:26:51.5271781Z ##[debug]loading INPUT_TAGREPO
2020-05-15T22:26:51.5273932Z ##[debug]loading INPUT_GITNAME
2020-05-15T22:26:51.5276075Z ##[debug]loading INPUT_GITEMAIL
2020-05-15T22:26:51.5278385Z ##[debug]loading INPUT_USEAGENTTOKEN
2020-05-15T22:26:51.5280519Z ##[debug]loading INPUT_USER
2020-05-15T22:26:51.5323079Z ##[debug]loading INPUT_PASSWORD
2020-05-15T22:26:51.5325802Z ##[debug]loading INPUT_LOCALPATH
2020-05-15T22:26:51.5328347Z ##[debug]loading INPUT_INJECTEXTRAHEADER
2020-05-15T22:26:51.5330849Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-05-15T22:26:51.5333463Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-05-15T22:26:51.5335936Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-05-15T22:26:51.5343099Z ##[debug]loading SECRET_SYSTEM_DEBUG
2020-05-15T22:26:51.5346095Z ##[debug]loaded 20
2020-05-15T22:26:51.5358134Z ##[debug]Agent.ProxyUrl=undefined
2020-05-15T22:26:51.5363929Z ##[debug]Agent.CAInfo=undefined
2020-05-15T22:26:51.5364843Z ##[debug]Agent.ClientCert=undefined
2020-05-15T22:26:51.5364992Z ##[debug]Agent.SkipCertValidation=undefined
2020-05-15T22:26:51.5620210Z ##[debug]repo=E-Commerce/_git/E-Commerce.wiki
2020-05-15T22:26:51.5622274Z ##[debug]filename=ReleaseNotes/$(Release.ReleaseName.md)
2020-05-15T22:26:51.5623905Z ##[debug]localpath=/opt/azure/agent1/_work/r2/a\repo
2020-05-15T22:26:51.5624701Z ##[debug]contents=undefined
2020-05-15T22:26:51.5626480Z ##[debug]message=Auto-Generated Release Notes
2020-05-15T22:26:51.5627918Z ##[debug]gitname=Garima Dubey
2020-05-15T22:26:51.5629424Z ##[debug]gitemail=gadubey@deloitte.com
2020-05-15T22:26:51.5645921Z ##[debug]user=gadubey@deloitte.com
2020-05-15T22:26:51.5647744Z ##[debug]password=qqv2do2tyrvcf4dvqpzka7pklx3wm4ujavkfhet7cd2bnuc7a34q
2020-05-15T22:26:51.5651261Z ##[debug]useAgentToken=false
2020-05-15T22:26:51.5666508Z ##[debug]replaceFile=false
2020-05-15T22:26:51.5669594Z ##[debug]appendToFile=***
2020-05-15T22:26:51.5669870Z ##[debug]dataIsFile=***
2020-05-15T22:26:51.5671936Z ##[debug]sourceFile=/opt/azure/agent1/_work/r2/a\releasenotes.md.
2020-05-15T22:26:51.5674132Z ##[debug]tagRepo=false
2020-05-15T22:26:51.5682171Z ##[debug]tag=undefined
2020-05-15T22:26:51.5689977Z ##[debug]branch=develop
2020-05-15T22:26:51.5725030Z ##[debug]injectExtraHeader=false
2020-05-15T22:26:51.5746835Z Variable: Repo [E-Commerce/_git/E-Commerce.wiki]
2020-05-15T22:26:51.5747918Z Variable: Filename [ReleaseNotes/$(Release.ReleaseName.md)]
2020-05-15T22:26:51.5749276Z Variable: Contents [undefined]
2020-05-15T22:26:51.5750765Z Variable: Commit Message [Auto-Generated Release Notes]
2020-05-15T22:26:51.5751442Z Variable: Git Username [Garima Dubey]
2020-05-15T22:26:51.5752642Z Variable: Git Email [gadubey@deloitte.com]
2020-05-15T22:26:51.5753864Z Variable: Use Agent Token [false]
2020-05-15T22:26:51.5754942Z Variable: Replace File [false]
2020-05-15T22:26:51.5756143Z Variable: Append to File [***]
2020-05-15T22:26:51.5757260Z Variable: Username [gadubey@deloitte.com]
2020-05-15T22:26:51.5758340Z Variable: Password [qqv2do2tyrvcf4dvqpzka7pklx3wm4ujavkfhet7cd2bnuc7a34q]
2020-05-15T22:26:51.5759499Z Variable: Localpath [/opt/azure/agent1/_work/r2/a\repo]
2020-05-15T22:26:51.5760734Z Variable: Data Is File [***]
2020-05-15T22:26:51.5761977Z Variable: SoureFile [/opt/azure/agent1/_work/r2/a\releasenotes.md.]
2020-05-15T22:26:51.5763111Z Variable: Tag Repo [false]
2020-05-15T22:26:51.5764295Z Variable: Tag [undefined]
2020-05-15T22:26:51.5765678Z Variable: Branch [develop]
2020-05-15T22:26:51.5767151Z Variable: InjectExtraHeader [false]
2020-05-15T22:26:51.6030163Z URL used https://gadubey@deloitte.com:***@E-Commerce/_git/E-Commerce.wiki
2020-05-15T22:26:51.6043483Z Cleaned /opt/azure/agent1/_work/r2/a\repo
2020-05-15T22:26:51.6332532Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-15T22:26:51.6342893Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:26:51.6343257Z ##[debug]task result: Failed
2020-05-15T22:26:51.6343752Z ##[error]Error: Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
2020-05-15T22:26:51.6344020Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:26:51.6344409Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: spawn git ENOENT%0A    at exports._errnoException (util.js:1018:11)%0A    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)%0A    at onErrorNT (internal/child_process.js:367:16)%0A    at _combinedTickCallback (internal/process/next_tick.js:80:11)%0A    at process._tickCallback (internal/process/next_tick.js:104:9)%0A    at Module.runMain (module.js:606:11)%0A    at run (bootstrap_node.js:390:7)%0A    at startup (bootstrap_node.js:150:9)%0A    at bootstrap_node.js:505:3
2020-05-15T22:26:51.6378739Z ##[section]Finishing: WIKI Updater

**Comment by rfennell** [comment]
> Firstly, a comment, you should always pass secrets, such as PAT, into builds and releases as a secret variable, the value is then obfuscated in the logs. As you did not do this I can read your PAT. I would strongly recommend you revoke the PAT you used, if you have not already done so,  as it appearing in this log which is a security risk.

Looking at the log I think you have some parameters wrong, please re-check the [WIKI documentation](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks) for details on how to authenticate with different Git based WIKIs (towards the end of the document)

- Your repo value is `repo=E-Commerce/_git/E-Commerce.wiki' There is no server name in the url I would expect something like `dev.azure.com/richardfennell/MyProject/_git/Git-project.wiki`
- Your username is an email address, depending upon the host service of your WIKI and your authentication method this is most commonly the organisation name, but certainly is not an email address.

So I suggest you re-read the documentation section specific to the system you are hosting your WIKI Git repo to check your values. As a minimum your repo parameter is wrong

**Comment by dgarima** [comment]
Hi ,
I regenerated the url using the steps mentioned ,while clicking on the clone link in the Azure Dev ops wiki - i am getting the below url 
https://<organization name>.visualstudio.com/E-Commerce/_git/E-Commerce.wiki.
The url is not in the format you have mentioned.Is there anything that i am missing.

**Comment by rfennell** [comment]
The format that is required for the repo variable for the task is  
```
dev.azure.com/<your org>/<your project>/_git/<reponame>.wiki
```
or if still using the old URL format

```
<your org>.visualstudio.com/<your project>/_git/<reponame>.wiki
```
However in the information you provide is missing the organisation name 

```
https://YOUR-ORG-HERE.visualstudio.com/E-Commerce/_git/E-Commerce.wiki
```

There are instruction in the WIKI documentation that explain how to get this value and the format required

**Comment by kodejack** [comment]
Are there any plans for this to work with new YAML pipelines using the deployment step?  

I'm working on this ATM but as you say it won't know what this is `${releaseDetails.releaseDefinition.name}`

Is there a way to get this from the - deployment step?

```
  jobs:
  - deployment: Deploy_Android_AppCenter
    displayName: Deploy Android ${{ variables.buildClassification }} build to AppCenter 
    environment: Umbrella_App_${{ variables.buildClassification }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download - Android-${{ variables.buildClassification }}
            artifact: Android-${{ variables.buildClassification }}
          - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@2
            displayName: 'Generate Release Notes based on Release Comparision API'
            inputs:
              outputfile: ${{ parameters.releaseNotesFile }}
              templateLocation: InLine
              inlinetemplate: |
              ### Notes for release  **${releaseDetails.releaseDefinition.name}**
              Release Number : **${releaseDetails.name}**
              Release completed : ${releaseDetails.modifiedOn}
              Compared Release Number : ** ${compareReleaseDetails.name} **
              
              ### Associated work items  
              @@WILOOP@@  
              * ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** ${widetail.fields['System.Title']}  
              @@WILOOP@@  
              emptySetText: 'There are no specific changes (or at least generated release notes) in this version'
              sortWi: true

          ...
```

**Comment by rfennell** [comment]
The task already fully supports YAML pipelines, it is just a case of using only the objects that are available in your template i.e. not the `releaseDetails` object as this is specific to the releases, multi-stage YAML is always considered a built, so you can only access the `buildDetails`

You can find a list of objects available in the [documentationWIKI](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) for 
- builds
- release
- and objects common to both

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
