### ISSUE TITLE
When "Azure DevOps services are currently unavailable", task fails but returns success

### ISSUE THREAD

**Issue by 0x4AMiller** [rfennell/AzurePipelines#816]
**Azure DevOps Extension you are using**
Generate Release Notes (Crossplatform)

**Where are you running it?**
Azure DevOps Service (VSTS) hosted

**Version of Extension/Task**
Version: 3.11.2

**Expected behaviour and actual behaviour**
return fail for task if it is unsuccessful

**Any idea on how to fix or circumvent it?**
  I think a catch may be missing but revewing the code it appeared to all be wrapped in catch blocks so not sure how it wasn't caught yet

**log from task:**
2020-09-15T22:14:36.5372252Z ##[section]Starting: XplatGenerateReleaseNotes
2020-09-15T22:14:36.5635285Z ==============================================================================
2020-09-15T22:14:36.5637151Z Task         : Generate Release Notes (Crossplatform)
2020-09-15T22:14:36.5637777Z Description  : Generates a release notes file in a format of your choice from the build or release history
2020-09-15T22:14:36.5639683Z Version      : 3.11.2
2020-09-15T22:14:36.5640047Z Author       : Black Marble
2020-09-15T22:14:36.5640773Z Help         : Version: 3.11.2. [More Information](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task/)
2020-09-15T22:14:36.5642418Z ==============================================================================
2020-09-15T22:14:40.1635041Z Getting the current build details
2020-09-15T22:14:40.7928221Z Getting items associated with only the current build
2020-09-15T22:14:41.0160283Z Get the file details associated with the commits
2020-09-15T22:14:41.0162159Z Enriched change e26e5051a769220c0d155c13c505f5bc58651864 of type TfsGit
2020-09-15T22:14:41.0162863Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0163343Z Enriched change 502eff42dc1da75d9370b76297e8e75119bce9da of type TfsGit
2020-09-15T22:14:41.0163826Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0164387Z Enriched change 7d2b74aa619b715a677f6337c9ff26865b5de825 of type TfsGit
2020-09-15T22:14:41.0164891Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0165415Z Enriched change 36ea878c8c719eddb321cece14e158e004ff6dfb of type TfsGit
2020-09-15T22:14:41.0165989Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0166501Z Enriched change d762a5e0a7e7197db965c17c2443bc857f5058cb of type TfsGit
2020-09-15T22:14:41.0167037Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0167585Z Enriched change 4ca37cdaebfd8cebf48261e7c312a48f6b6c9c69 of type TfsGit
2020-09-15T22:14:41.0168142Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0168657Z Enriched change 895991d9d7989073911c56e252a4bfcb20c4ea0f of type TfsGit
2020-09-15T22:14:41.0170134Z Cannot enriched as location URL not in dev.azure.com format
2020-09-15T22:14:41.0170741Z Get any test details associated with the build
2020-09-15T22:14:41.1851597Z (node:5328) UnhandledPromiseRejectionWarning: Error: TF10216: Azure DevOps services are currently unavailable. Try again later. Activity Id: c7f5ca1b-a27c-49fc-9af8-299ad6ee656b
2020-09-15T22:14:41.1853012Z     at RestClient.<anonymous> (D:\a\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.11.2\node_modules\azure-devops-node-api\node_modules\typed-rest-client\RestClient.js:200:31)
2020-09-15T22:14:41.1853622Z     at Generator.next (<anonymous>)
2020-09-15T22:14:41.1854197Z     at fulfilled (D:\a\_tasks\XplatGenerateReleaseNotes_7b0a5887-75c4-4ade-a915-f92a93c934cb\3.11.2\node_modules\azure-devops-node-api\node_modules\typed-rest-client\RestClient.js:6:58)
2020-09-15T22:14:41.1854803Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-15T22:14:41.1855914Z (node:5328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-09-15T22:14:41.1856902Z (node:5328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-09-15T22:14:41.2412134Z ##[section]Finishing: XplatGenerateReleaseNotes

**Comment by rfennell** [comment]
Strange I would have expected the try/catch in the outer main function to trap that, I suspect an async issue. I guess I need to add an extra try/catch in the inner `generateReleaseNotes` function.

However, before I had that your trace does a little strange, it seem you managed to make the first set of calls to get the WI/CS, but fell over when looking for test. Do you think Azure DevOps went down half through the run?

**Comment by rfennell** [comment]
Will be shipped as 3.13.2 with the extra try/catch

**Comment by 0x4AMiller** [comment]
> Strange I would have expected the try/catch in the outer main function to trap that, I suspect an async issue. I guess I need to add an extra try/catch in the inner `generateReleaseNotes` function.
> 
> However, before I had that your trace does a little strange, it seem you managed to make the first set of calls to get the WI/CS, but fell over when looking for test. Do you think Azure DevOps went down half through the run?

I agree it was odd - I suspect the only explanation was that it went down right at the time of that specific step and the task is fairly fast.  I was also confused at the outer catch not handling that faliure as the code looked pretty defensive so I am not sure why it bubbled all the way up as unhandled.
