### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by NmathieuAdista** [rfennell/AzurePipelines#842]
Hello
I use the last version of Azure Devos
But i have a problem !!

Help me plz 

```
Task         : Generate Release Notes (Crossplatform)
Description  : Generates a release notes file in a format of your choice from the build or release history
Version      : 3.21.3
Author       : Black Marble
Help         : Version: 3.21.3. [More Information](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task/)
==============================================================================
(node:9992) UnhandledPromiseRejectionWarning: c
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
(node:9992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Creating the credential handler from the OAUTH token
##[section]Finishing: Generate Release Notes based on Release Comparison API
```

**Comment by rfennell** [comment]
A couple questions

1. Are you using Azure DevOps Server i.e. the on premise version?
2. Is this a new installation of my extension, or has it worked in the past?

**Comment by NmathieuAdista** [comment]
Thank you for your prompt response!

Azure DevOps Server and this is a new installation.

**Comment by rfennell** [comment]
This is I think a duplicate of #801. It seems to be down to the use of self signed certificate ?

Anyway I added some steps to try at the end of #801 i.e  Azure DevOps variable `NODE_TLS_REJECT_UNAUTHORIZED=0` - have a read f that issue and give the steps a try

**Comment by rfennell** [comment]
You can also set a variable `system.debug=true` this will give a more detailed error log that might show something.

I have retested on my Azure DevOps Server 17.153.29522.3 (AzureDevOps2019.Update1.1) with `system.debug=true` on, and (after it lists the input parameters) it shows  

```
##[debug]Getting System.AccessToken
##[debug]Getting credentials the agent is running as
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Found an OAUTH token
Creating the credential handler from the OAUTH token
Getting the current build details
Getting items associated with only the current build
Get the file details associated with the commits
Get any test details associated with the build
```

**Comment by NmathieuAdista** [comment]
Problem solved, my self signed certificate was only in the IIS storage but not in the windows storage.
Thx 👍
