### ISSUE TITLE
Error "Deserialize" with "2" argument(s): "Invalid JSON primitive: ."

### ISSUE THREAD

**Issue by Svetlana-Kovalev** [rfennell/AzurePipelines#854]
**Describe the bug**

```
2020-10-20T18:18:29.4163763Z ##[debug]Evaluating condition for step: 'Generate release notes copy'
2020-10-20T18:18:29.4164527Z ##[debug]Evaluating: succeeded()
2020-10-20T18:18:29.4164646Z ##[debug]Evaluating succeeded:
2020-10-20T18:18:29.4164811Z ##[debug]=> True
2020-10-20T18:18:29.4165082Z ##[debug]Result: True
2020-10-20T18:18:29.4165320Z ##[section]Starting: Generate release notes copy
2020-10-20T18:18:29.4505028Z ==============================================================================
2020-10-20T18:18:29.4505101Z Task         : Generate Release Notes for Pipeline Builds or Releases (PowerShell)
2020-10-20T18:18:29.4505157Z Description  : Generates a release notes file in a format of your choice for Azure DevOps Pipeline Builds or Releases. Windows based agents only
2020-10-20T18:18:29.4505212Z Version      : 3.8.1
2020-10-20T18:18:29.4505246Z Author       : Black Marble
2020-10-20T18:18:29.4505295Z Help         : Version: 3.8.1. [More Information](https://github.com/rfennell/vNextBuild/wiki/GenerateReleaseNotes%20-Tasks/)
2020-10-20T18:18:29.4505341Z ==============================================================================
2020-10-20T18:18:31.0264959Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-10-20T18:18:31.2098750Z ##[debug]Loading module from path 'C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.psm1'.
2020-10-20T18:18:31.2442597Z ##[debug]Loading module from path 'C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\Get-CallerPreference.ps1'.
2020-10-20T18:18:31.2523113Z ##[debug]Dot-sourcing the script file 'C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\Get-CallerPreference.ps1'.
2020-10-20T18:18:31.2617793Z ##[debug]
2020-10-20T18:18:31.2633785Z ##[debug]	 public enum Mode
2020-10-20T18:18:31.2649152Z ##[debug]	 {
2020-10-20T18:18:31.2664855Z ##[debug]			BODY,
2020-10-20T18:18:31.2681273Z ##[debug]			WI,
2020-10-20T18:18:31.2696561Z ##[debug]			CS,
2020-10-20T18:18:31.2715315Z ##[debug]			BUILD
2020-10-20T18:18:31.2730912Z ##[debug]	 }
2020-10-20T18:18:31.5750710Z ##[debug]Exporting function 'Get-CallerPreference'.
2020-10-20T18:18:31.5773910Z ##[debug]Exporting function 'Use-SystemWebProxy'.
2020-10-20T18:18:31.5795731Z ##[debug]Exporting function 'Get-WorkItemDataFromBuild'.
2020-10-20T18:18:31.5817423Z ##[debug]Exporting function 'Get-CommitInfoFromGitRepo'.
2020-10-20T18:18:31.5839769Z ##[debug]Exporting function 'Expand-WorkItemData'.
2020-10-20T18:18:31.5862945Z ##[debug]Exporting function 'Get-BuildChangeSets'.
2020-10-20T18:18:31.5886460Z ##[debug]Exporting function 'Get-Detail'.
2020-10-20T18:18:31.5913421Z ##[debug]Exporting function 'Get-Build'.
2020-10-20T18:18:31.5935473Z ##[debug]Exporting function 'Get-BuildsByDefinitionId'.
2020-10-20T18:18:31.5956933Z ##[debug]Exporting function 'Get-ReleaseDefinitionByName'.
2020-10-20T18:18:31.5978524Z ##[debug]Exporting function 'Get-Release'.
2020-10-20T18:18:31.5999997Z ##[debug]Exporting function 'Get-BuildReleaseArtifacts'.
2020-10-20T18:18:31.6021775Z ##[debug]Exporting function 'ConvertFrom-JsonUsingDOTNET'.
2020-10-20T18:18:31.6043212Z ##[debug]Exporting function 'Expand-Tree'.
2020-10-20T18:18:31.6064832Z ##[debug]Exporting function 'Add-Space'.
2020-10-20T18:18:31.6086649Z ##[debug]Exporting function 'Invoke-GetCommand'.
2020-10-20T18:18:31.6108240Z ##[debug]Exporting function 'Invoke-PostCommand'.
2020-10-20T18:18:31.6129921Z ##[debug]Exporting function 'Render'.
2020-10-20T18:18:31.6153172Z ##[debug]Exporting function 'Get-Template'.
2020-10-20T18:18:31.6175807Z ##[debug]Exporting function 'Get-Mode'.
2020-10-20T18:18:31.6201387Z ##[debug]Exporting function 'Add-StackItem'.
2020-10-20T18:18:31.6224597Z ##[debug]Exporting function 'Invoke-Template'.
2020-10-20T18:18:31.6247085Z ##[debug]Exporting function 'Get-BuildDataSet'.
2020-10-20T18:18:31.6613125Z ##[debug]Exporting function 'Convert-ToReleaseAPIURL'.
2020-10-20T18:18:31.6639571Z ##[debug]Exporting function 'Get-ReleaseByDefinitionId'.
2020-10-20T18:18:31.6653212Z ##[debug]Importing function 'Add-Space'.
2020-10-20T18:18:31.6671885Z ##[debug]Importing function 'Add-StackItem'.
2020-10-20T18:18:31.8163614Z ##[debug]Importing function 'Convert-ToReleaseAPIURL'.
2020-10-20T18:18:31.8187913Z ##[debug]Importing function 'ConvertFrom-JsonUsingDOTNET'.
2020-10-20T18:18:31.8210267Z ##[debug]Importing function 'Expand-Tree'.
2020-10-20T18:18:31.8230023Z ##[debug]Importing function 'Expand-WorkItemData'.
2020-10-20T18:18:31.8251291Z ##[debug]Importing function 'Get-Build'.
2020-10-20T18:18:31.8273090Z ##[debug]Importing function 'Get-BuildChangeSets'.
2020-10-20T18:18:31.8295118Z ##[debug]Importing function 'Get-BuildDataSet'.
2020-10-20T18:18:31.8331966Z ##[debug]Importing function 'Get-BuildReleaseArtifacts'.
2020-10-20T18:18:31.8351060Z ##[debug]Importing function 'Get-BuildsByDefinitionId'.
2020-10-20T18:18:31.8371412Z ##[debug]Importing function 'Get-CallerPreference'.
2020-10-20T18:18:31.8390847Z ##[debug]Importing function 'Get-CommitInfoFromGitRepo'.
2020-10-20T18:18:31.8410275Z ##[debug]Importing function 'Get-Detail'.
2020-10-20T18:18:31.8429329Z ##[debug]Importing function 'Get-Mode'.
2020-10-20T18:18:31.8449570Z ##[debug]Importing function 'Get-Release'.
2020-10-20T18:18:31.8468618Z ##[debug]Importing function 'Get-ReleaseByDefinitionId'.
2020-10-20T18:18:31.8489516Z ##[debug]Importing function 'Get-ReleaseDefinitionByName'.
2020-10-20T18:18:31.8509737Z ##[debug]Importing function 'Get-Template'.
2020-10-20T18:18:31.8529039Z ##[debug]Importing function 'Get-WorkItemDataFromBuild'.
2020-10-20T18:18:31.8547906Z ##[debug]Importing function 'Invoke-GetCommand'.
2020-10-20T18:18:31.8566949Z ##[debug]Importing function 'Invoke-PostCommand'.
2020-10-20T18:18:31.8586689Z ##[debug]Importing function 'Invoke-Template'.
2020-10-20T18:18:31.8605954Z ##[debug]Importing function 'Render'.
2020-10-20T18:18:31.8624870Z ##[debug]Importing function 'Use-SystemWebProxy'.
2020-10-20T18:18:31.8671257Z ##[debug]Using system web proxy.
2020-10-20T18:18:31.9171650Z ##[debug]INPUT_OUTPUTFILE: 'C:\agent\_work\117\a\releasenotes.md'
2020-10-20T18:18:31.9199071Z ##[debug]INPUT_OUTPUTVARIABLENAME: 'Test1'
2020-10-20T18:18:31.9223966Z ##[debug]INPUT_TEMPLATEFILE: 'C:\agent\_work\117\s\Common\bin\Release'
2020-10-20T18:18:31.9249597Z ##[debug]INPUT_INLINETEMPLATE: '# Release notes 
2020-10-20T18:18:31.9262738Z ##[debug]## Notes for release  ${releaseDetails.releaseDefinition.name}
2020-10-20T18:18:31.9276192Z ##[debug]**Release Number**  : ${releaseDetails.name} 
2020-10-20T18:18:31.9289701Z ##[debug]**Release completed** : ${releaseDetails.modifiedOn} 
2020-10-20T18:18:31.9303012Z ##[debug]**Compared Release Number**  : ${compareReleaseDetails.name} 
2020-10-20T18:18:31.9316386Z ##[debug]
2020-10-20T18:18:31.9329866Z ##[debug]### Associated work items  
2020-10-20T18:18:31.9343570Z ##[debug]@@WILOOP@@  
2020-10-20T18:18:31.9356938Z ##[debug]* ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
2020-10-20T18:18:31.9370498Z ##[debug]@@WILOOP@@  
2020-10-20T18:18:31.9384106Z ##[debug]  
2020-10-20T18:18:31.9397664Z ##[debug]### Associated commits
2020-10-20T18:18:31.9411603Z ##[debug]@@CSLOOP@@  
2020-10-20T18:18:31.9424953Z ##[debug]* **ID ${csdetail.commitId} ** ${csdetail.comment}    
2020-10-20T18:18:31.9438283Z ##[debug]@@CSLOOP@@'
2020-10-20T18:18:31.9463360Z ##[debug]INPUT_TEMPLATELOCATION: 'InLine'
2020-10-20T18:18:31.9488611Z ##[debug]INPUT_USEDEFAULTCREDS: 'true'
2020-10-20T18:18:31.9514102Z ##[debug]INPUT_GENERATEFORONLYPRIMARY: 'true'
2020-10-20T18:18:31.9541124Z ##[debug]INPUT_GENERATEFORONLYTRIGGERARTIFACT: 'False'
2020-10-20T18:18:31.9567376Z ##[debug]INPUT_GENERATEFORCURRENTRELEASE: 'True'
2020-10-20T18:18:31.9593204Z ##[debug]INPUT_OVERRIDESTAGENAME (empty)
2020-10-20T18:18:31.9667160Z ##[debug]INPUT_EMPTYSETTEXT: 'None'
2020-10-20T18:18:31.9693756Z ##[debug]INPUT_MAXCHANGES: '50'
2020-10-20T18:18:31.9720239Z ##[debug]INPUT_MAXWI: '50'
2020-10-20T18:18:31.9745765Z ##[debug]INPUT_WIFILTER (empty)
2020-10-20T18:18:31.9770406Z ##[debug]INPUT_WISTATEFILTER (empty)
2020-10-20T18:18:31.9796975Z ##[debug]INPUT_SHOWPARENTS: 'false'
2020-10-20T18:18:31.9824638Z ##[debug]INPUT_APPENDTOFILE: 'true'
2020-10-20T18:18:31.9852549Z ##[debug]INPUT_UNIFIEDLIST: 'true'
2020-10-20T18:18:31.9878250Z ##[debug]INPUT_BUILDTAGS (empty)
2020-10-20T18:18:31.9960719Z ##[debug]collectionUrl = [https://company.visualstudio.com/]
2020-10-20T18:18:31.9979801Z ##[debug]teamproject = [Company]
2020-10-20T18:18:32.0008398Z ##[debug]releaseid = []
2020-10-20T18:18:32.0027615Z ##[debug]releasedefid = []
2020-10-20T18:18:32.0046081Z ##[debug]stageName = []
2020-10-20T18:18:32.0065343Z ##[debug]overrideStageName = []
2020-10-20T18:18:32.0084894Z ##[debug]buildid = [4946]
2020-10-20T18:18:32.0104406Z ##[debug]builddefname = [WorkFlow Test New]
2020-10-20T18:18:32.0122785Z ##[debug]releasedefname = []
2020-10-20T18:18:32.0141643Z ##[debug]buildnumber = [NewIntegration2019_.11]
2020-10-20T18:18:32.0160079Z ##[debug]outputVariableName = [Test1]
2020-10-20T18:18:32.0179124Z ##[debug]generateForOnlyPrimary = [true]
2020-10-20T18:18:32.0198752Z ##[debug]generateForOnlyTriggerArtifact = [False]
2020-10-20T18:18:32.0218091Z ##[debug]generateForCurrentRelease = [True]
2020-10-20T18:18:32.0237483Z ##[debug]maxWi = [50]
2020-10-20T18:18:32.0256317Z ##[debug]maxChanges = [50]
2020-10-20T18:18:32.0275302Z ##[debug]showParents  =[false]
2020-10-20T18:18:32.0294477Z ##[debug]wiFilter = []
2020-10-20T18:18:32.0313389Z ##[debug]wiStateFilter = []
2020-10-20T18:18:32.0332420Z ##[debug]appendToFile = [true]
2020-10-20T18:18:32.0351746Z ##[debug]In Build mode
2020-10-20T18:18:32.0959033Z ##[debug]    Getting build details for BuildID [4946]
2020-10-20T18:18:32.1192667Z ##[debug]Using default credentials
2020-10-20T18:18:32.3921865Z ##[debug]Caught exception from task script.
2020-10-20T18:18:32.3955811Z ##[debug]Error record:
2020-10-20T18:18:32.4623829Z ##[debug]ConvertFrom-JsonUsingDOTNET : Exception calling "Deserialize" with "2" argument(s): "Invalid JSON primitive: ."
2020-10-20T18:18:32.4638024Z ##[debug]At C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.psm1:254 char:81
2020-10-20T18:18:32.4652339Z ##[debug]+ ...  $uri -usedefaultcreds $usedefaultcreds | ConvertFrom-JsonUsingDOTNET
2020-10-20T18:18:32.4666624Z ##[debug]+                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-10-20T18:18:32.4681766Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-JsonUsingDOTNET], MethodInvocationException
2020-10-20T18:18:32.4695899Z ##[debug]    + FullyQualifiedErrorId : ArgumentException,ConvertFrom-JsonUsingDOTNET
2020-10-20T18:18:32.4709496Z ##[debug] 
2020-10-20T18:18:32.4729767Z ##[debug]Script stack trace:
2020-10-20T18:18:32.4766356Z ##[debug]at ConvertFrom-JsonUsingDOTNET, C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.psm1: line 341
2020-10-20T18:18:32.4780277Z ##[debug]at Get-Build, C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.psm1: line 254
2020-10-20T18:18:32.4795252Z ##[debug]at Get-BuildDataSet, C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.psm1: line 703
2020-10-20T18:18:32.4809119Z ##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\GenerateReleaseNotes_661bc005-61be-430f-b994-065bf08c0f39\3.8.1\GenerateReleaseNotes.ps1: line 103
2020-10-20T18:18:32.4822325Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-20T18:18:32.4835706Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-10-20T18:18:32.4849151Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-10-20T18:18:32.4862591Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-20T18:18:32.4883357Z ##[debug]Exception:
2020-10-20T18:18:32.4927445Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "Deserialize" with "2" argument(s): "Invalid JSON primitive: ." ---> System.ArgumentException: Invalid JSON primitive: .
2020-10-20T18:18:32.4941201Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2020-10-20T18:18:32.4954663Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2020-10-20T18:18:32.4968254Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2020-10-20T18:18:32.4982333Z ##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2020-10-20T18:18:32.4997952Z ##[debug]   at CallSite.Target(Closure , CallSite , Object , Object , Type )
2020-10-20T18:18:32.5011279Z ##[debug]   --- End of inner exception stack trace ---
2020-10-20T18:18:32.5024415Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-10-20T18:18:32.5038181Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2020-10-20T18:18:32.5052286Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-10-20T18:18:32.5065794Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-10-20T18:18:32.5079644Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-10-20T18:18:32.5092965Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-10-20T18:18:32.5106466Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2020-10-20T18:18:32.5120315Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2020-10-20T18:18:32.5133748Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-10-20T18:18:32.5435396Z ##[error]Exception calling "Deserialize" with "2" argument(s): "Invalid JSON primitive: ."
2020-10-20T18:18:32.5444744Z ##[debug]Processed: ##vso[task.logissue type=error]Exception calling "Deserialize" with "2" argument(s): "Invalid JSON primitive: ."
2020-10-20T18:18:32.5459738Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-10-20T18:18:32.5721330Z ##[section]Finishing: Generate release notes copy
```

**Comment by rfennell** [comment]
My first comment is that I would strongly recommend that you don't use my `PowerShell Release Notes` extension, but rather use the much newer and more flexible [Cross Platform Release Notes](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes). My plan is to deprecate the older PowerShell version in the not to distant future.

Anyway, to look at your problem, assuming you plan to stay on the older PowerShell task..

1. Has the task ever worked for you, or is it a new install?
1. From the logs it looks as if the failing on the first REST call. The PowerShell line is `$uri = "$($tfsUri)/$($teamproject)/_apis/build/builds/$($buildid)?api-version=2.0"` where the `$buildid` is 4946 and the `$tfsuri` and `$teamproject` are your organisation and project details. So what do you see when you run this REST call (replacing your values) in a browser? It should return details of the build as detailed [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-6.0)

**Comment by Svetlana-Kovalev** [comment]
It was disabled and I work to enable "release notes" building.

Link ```https://company.visualstudio.com/project/_apis/build/builds/4946?api-version=2.0``` returns correct json file in browser:
sample of received json:
```json
{
	"properties": {},
	"tags": [],
	"validationResults": [],
	"plans": [
		{
			"planId": "1a4e60be-465e-4551-857e-b4d5a741071b"
		}
	],
	"triggerInfo": {},
	"id": 4946,
	"status": "completed",
	"result": "canceled",
	"queueTime": "2020-10-20T18:16:43.347876Z",
	"startTime": "2020-10-20T18:16:47.0428353Z",
	"finishTime": "2020-10-20T18:19:30.1415742Z",
	"keepForever": false,
	"retainedByRelease": false,
	"triggeredByBuild": null
}
```

**Comment by rfennell** [comment]
Well that looks OK, after that call the task tries to get WI and CS data. the way it does this depends on the source control type

```
  [string] $activateFix = $Env:RELEASENOTES_FIX349
    if (($build.repository.type -eq "TfsGit") -and ![string]::IsNullOrEmpty($activateFix) -and ($activateFix.ToLower() -eq $true)) {
        $commitInfo = Get-CommitInfoFromGitRepo -tfsUri $tfsUri -teamproject $teamproject -build $build -usedefaultcreds $usedefaultcreds -maxWi $maxWi -maxCommits $maxChanges
        $changesets = $commitInfo.commits
        $workItemData = $commitInfo.workItems
    }
    else {
        $changesets = Get-BuildChangeSets -tfsUri $tfsUri -teamproject $teamproject -buildid $buildid -usedefaultcreds $usedefaultcreds -maxItems $maxChanges
        $workItemData = Get-WorkItemDataFromBuild -tfsUri $tfsUri -teamproject $teamproject -buildid $buildid -usedefaultcreds $usedefaultcreds -maxItems $maxWi
    }
```

But it feels like the basic REST call is failing. Is there any proxy between your agent and your server?

Does the [Cross Platform Release Notes Task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) run? As I said this is a much more functional and flexible task
